import json

# 這是我為您精心準備的前 50 個高品質單字對應表
enriched_data = {
    "recruit": {"phonetic": "/rɪˈkruːt/", "pos": "v.", "meaning": "招募；徵聘", "phrases": ["recruit new talent", "campus recruitment"], "synonyms": ["hire", "employ"], "antonyms": ["dismiss", "fire"], "example": "The tech giant plans to recruit more software engineers this year."},
    "candidate": {"phonetic": "/ˈkændɪdət/", "pos": "n.", "meaning": "候選人；應徵者", "phrases": ["ideal candidate", "job candidate"], "synonyms": ["applicant", "contender"], "antonyms": [], "example": "We interviewed several candidates for the sales manager position."},
    "stationery": {"phonetic": "/ˈsteɪʃəneri/", "pos": "n.", "meaning": "文具；信紙", "phrases": ["office stationery", "stationery supplier"], "synonyms": ["writing materials"], "antonyms": [], "example": "Please order some stationery, including pens and notebooks."},
    "maintenance": {"phonetic": "/ˈmeɪntənəns/", "pos": "n.", "meaning": "維修；保養", "phrases": ["regular maintenance", "maintenance department"], "synonyms": ["upkeep", "repair"], "antonyms": ["neglect"], "example": "The building requires regular maintenance to stay in good condition."},
    "facility": {"phonetic": "/fəˈsɪləti/", "pos": "n.", "meaning": "設施；設備", "phrases": ["production facility", "recreational facilities"], "synonyms": ["amenity", "equipment"], "antonyms": [], "example": "The company is investing in a new research and development facility."},
    "administrative": {"phonetic": "/ədˈmɪnɪstreɪtɪv/", "pos": "adj.", "meaning": "行政的；管理的", "phrases": ["administrative task", "administrative assistant"], "synonyms": ["managerial", "executive"], "antonyms": [], "example": "The manager is busy with various administrative duties today."},
    "briefing": {"phonetic": "/ˈbriːfɪŋ/", "pos": "n.", "meaning": "簡報；說明會", "phrases": ["daily briefing", "press briefing"], "synonyms": ["summary", "instruction"], "antonyms": [], "example": "All staff members must attend the morning briefing in the conference room."},
    "inventory": {"phonetic": "/ˈɪnvəntɔːri/", "pos": "n.", "meaning": "存貨；盤點", "phrases": ["inventory management", "take inventory"], "synonyms": ["stock", "supply"], "antonyms": [], "example": "The warehouse staff is conducting an annual inventory count."},
    "precaution": {"phonetic": "/prɪˈkɔːʃn/", "pos": "n.", "meaning": "預防措施", "phrases": ["safety precaution", "take precautions"], "synonyms": ["safeguard", "preventive measure"], "antonyms": [], "example": "As a precaution, the building was evacuated during the fire alarm."},
    "orientation": {"phonetic": "/ˌɔːriənˈteɪʃn/", "pos": "n.", "meaning": "新人入職訓練", "phrases": ["new employee orientation", "orientation program"], "synonyms": ["induction", "introduction"], "antonyms": [], "example": "The orientation for new hires will begin next Monday morning."},
    "personnel": {"phonetic": "/ˌpɜːrsəˈnel/", "pos": "n.", "meaning": "全體人員；人事", "phrases": ["personnel department", "medical personnel"], "synonyms": ["staff", "workforce"], "antonyms": [], "example": "All personnel are required to wear identification badges at all times."},
    "procedure": {"phonetic": "/prəˈsiːdʒər/", "pos": "n.", "meaning": "程序；步驟", "phrases": ["standard procedure", "operating procedure"], "synonyms": ["process", "step"], "antonyms": [], "example": "Please follow the correct procedure for filing an expense report."},
    "vacancy": {"phonetic": "/ˈveɪkənsi/", "pos": "n.", "meaning": "空缺；職缺", "phrases": ["job vacancy", "current vacancies"], "synonyms": ["opening", "gap"], "antonyms": [], "example": "There is a job vacancy for a senior accountant in our department."},
    "available": {"phonetic": "/əˈveɪləbl/", "pos": "adj.", "meaning": "可得到的；有空的", "phrases": ["readily available", "available for comment"], "synonyms": ["accessible", "obtainable"], "antonyms": ["unavailable", "occupied"], "example": "The manager is currently available to meet with you in her office."},
    "confirm": {"phonetic": "/kənˈfɜːrm/", "pos": "v.", "meaning": "確認；證實", "phrases": ["confirm a reservation", "confirm the details"], "synonyms": ["verify", "validate"], "antonyms": ["deny", "refute"], "example": "Please call the airline to confirm your flight departure time."},
    "remind": {"phonetic": "/rɪˈmaɪnd/", "pos": "v.", "meaning": "提醒", "phrases": ["remind someone of", "remind someone to do"], "synonyms": ["prompt", "alert"], "antonyms": ["forget"], "example": "Could you please remind me to call the client this afternoon?"},
    "deadline": {"phonetic": "/ˈdedlaɪn/", "pos": "n.", "meaning": "截止日期；期限", "phrases": ["meet a deadline", "strict deadline"], "synonyms": ["limit", "cutoff"], "antonyms": [], "example": "The deadline for submitting the project proposal is Friday at 5 PM."},
    "benefit": {"phonetic": "/ˈbenɪfɪt/", "pos": "n.", "meaning": "福利；益處", "phrases": ["employee benefits", "mutual benefit"], "synonyms": ["advantage", "perk"], "antonyms": ["drawback", "disadvantage"], "example": "A generous pension scheme is one of the many benefits of working here."},
    "colleague": {"phonetic": "/ˈkɑːliːɡ/", "pos": "n.", "meaning": "同事", "phrases": ["trusted colleague", "work colleague"], "synonyms": ["coworker", "peer"], "antonyms": [], "example": "I will discuss the matter with my colleagues and get back to you."},
    "promotion": {"phonetic": "/prəˈmoʊʃn/", "pos": "n.", "meaning": "晉升；促銷", "phrases": ["earn a promotion", "sales promotion"], "synonyms": ["advancement", "boost"], "antonyms": ["demotion"], "example": "He was delighted to receive a promotion to senior manager."},
    "submit": {"phonetic": "/səbˈmɪt/", "pos": "v.", "meaning": "提交；呈遞", "phrases": ["submit an application", "submit a report"], "synonyms": ["present", "tender"], "antonyms": ["withdraw"], "example": "All applications must be submitted online before the closing date."},
    "update": {"phonetic": "/ˌʌpˈdeɪt/", "pos": "v./n.", "meaning": "更新；最新消息", "phrases": ["status update", "software update"], "synonyms": ["revise", "refresh"], "antonyms": [], "example": "We will provide you with a status update at the end of the week."},
    "notify": {"phonetic": "/ˈnoʊtɪfaɪ/", "pos": "v.", "meaning": "正式通知", "phrases": ["notify someone of", "official notification"], "synonyms": ["inform", "announce"], "antonyms": ["conceal"], "example": "We will notify all successful candidates by the end of the month."},
    "arrangement": {"phonetic": "/əˈreɪndʒmənt/", "pos": "n.", "meaning": "安排；準備", "phrases": ["travel arrangements", "seating arrangement"], "synonyms": ["setup", "organization"], "antonyms": [], "example": "I need to make travel arrangements for my business trip to Japan."},
    "attendance": {"phonetic": "/əˈtendəns/", "pos": "n.", "meaning": "出席；到場人數", "phrases": ["record of attendance", "mandatory attendance"], "synonyms": ["presence"], "antonyms": ["absence"], "example": "Attendance at the monthly safety meeting is compulsory for all staff."},
    "clerk": {"phonetic": "/klɜːrk/", "pos": "n.", "meaning": "職員；店員", "phrases": ["office clerk", "sales clerk"], "synonyms": ["assistant", "staff"], "antonyms": [], "example": "The hotel clerk gave us the keys to our room on the fifth floor."},
    "complaint": {"phonetic": "/kəmˈpleɪnt/", "pos": "n.", "meaning": "抱怨；投訴", "phrases": ["customer complaint", "file a complaint"], "synonyms": ["objection", "grievance"], "antonyms": ["compliment", "praise"], "example": "The manager is currently dealing with a serious customer complaint."},
    "extension": {"phonetic": "/ɪkˈstenʃn/", "pos": "n.", "meaning": "分機；延期", "phrases": ["phone extension", "deadline extension"], "synonyms": ["addition", "prolongation"], "antonyms": ["shortening", "reduction"], "example": "If you have any questions, please call me at extension 214."},
    "invoice": {"phonetic": "/ˈɪnvɔɪs/", "pos": "n.", "meaning": "發票；請款單", "phrases": ["issue an invoice", "pay the invoice"], "synonyms": ["bill", "statement"], "antonyms": [], "example": "We will send you an invoice for the total amount due next week."},
    "membership": {"phonetic": "/ˈmembərʃɪp/", "pos": "n.", "meaning": "會員身分", "phrases": ["membership fee", "lifetime membership"], "synonyms": ["association", "belonging"], "antonyms": [], "example": "Membership in the professional association offers many networking opportunities."},
    "proposal": {"phonetic": "/prəˈpoʊzl/", "pos": "n.", "meaning": "提議；計畫書", "phrases": ["business proposal", "submit a proposal"], "synonyms": ["suggestion", "offer"], "antonyms": ["rejection"], "example": "The board of directors is currently considering our latest project proposal."},
    "reception": {"phonetic": "/rɪˈsepʃn/", "pos": "n.", "meaning": "接待處；歡迎會", "phrases": ["reception desk", "wedding reception"], "synonyms": ["lobby", "welcome"], "antonyms": [], "example": "Please leave your room keys at the reception desk when you check out."},
    "requirement": {"phonetic": "/rɪˈkwaɪərmənt/", "pos": "n.", "meaning": "要求；必要條件", "phrases": ["minimum requirement", "safety requirement"], "synonyms": ["necessity", "condition"], "antonyms": [], "example": "Good communication skills are a basic requirement for this job."},
    "reservation": {"phonetic": "/ˌrezərˈveɪʃn/", "pos": "n.", "meaning": "預約；保留", "phrases": ["make a reservation", "confirm a reservation"], "synonyms": ["booking", "engagement"], "antonyms": ["cancellation"], "example": "I'd like to make a hotel reservation for two nights next week."},
    "refund": {"phonetic": "/ˈriːfʌnd/", "pos": "n.", "meaning": "退款", "phrases": ["full refund", "request a refund"], "synonyms": ["repayment", "reimbursement"], "antonyms": ["payment"], "example": "The store offers a full refund for any defective merchandise."},
    "receipt": {"phonetic": "/rɪˈsiːt/", "pos": "n.", "meaning": "收據；收到", "phrases": ["sales receipt", "upon receipt of"], "synonyms": ["proof of purchase", "voucher"], "antonyms": [], "example": "Always keep your receipt in case you need to return the item."},
    "discount": {"phonetic": "/ˈdɪskaʊnt/", "pos": "n.", "meaning": "折扣", "phrases": ["special discount", "offer a discount"], "synonyms": ["reduction", "markdown"], "antonyms": ["markup", "surcharge"], "example": "We are offering a 20% discount on all winter clothing this week."},
    "agenda": {"phonetic": "/əˈdʒendə/", "pos": "n.", "meaning": "議程", "phrases": ["meeting agenda", "top of the agenda"], "synonyms": ["schedule", "program"], "antonyms": [], "example": "The first item on the agenda for today's meeting is the budget."},
    "minutes": {"phonetic": "/ˈmɪnɪts/", "pos": "n.", "meaning": "會議記錄", "phrases": ["take the minutes", "distribute the minutes"], "synonyms": ["records", "notes"], "antonyms": [], "example": "The secretary is responsible for taking the minutes during the board meeting."},
    "supervisor": {"phonetic": "/ˈsuːpərvaɪzər/", "pos": "n.", "meaning": "主管；監督者", "phrases": ["immediate supervisor", "shift supervisor"], "synonyms": ["manager", "boss"], "antonyms": ["subordinate", "employee"], "example": "Please report any technical problems to your immediate supervisor."},
    "department": {"phonetic": "/dɪˈpɑːrtmənt/", "pos": "n.", "meaning": "部門", "phrases": ["marketing department", "human resources department"], "synonyms": ["division", "section"], "antonyms": [], "example": "The finance department is located on the third floor of the building."},
    "branch": {"phonetic": "/bræntʃ/", "pos": "n.", "meaning": "分店；分支機構", "phrases": ["local branch", "branch office"], "synonyms": ["office", "outlet"], "antonyms": ["headquarters"], "example": "The bank plans to open several new branches in the suburban area."},
    "attachment": {"phonetic": "/əˈtætʃmənt/", "pos": "n.", "meaning": "附件", "phrases": ["email attachment", "see the attachment"], "synonyms": ["enclosure", "addition"], "antonyms": [], "example": "Please see the attached file for more details about the contract."},
    "forward": {"phonetic": "/ˈfɔːrwərd/", "pos": "v.", "meaning": "轉寄；發送", "phrases": ["forward an email", "look forward to"], "synonyms": ["send", "redirect"], "antonyms": [], "example": "Could you please forward the meeting request to the rest of the team?"},
    "response": {"phonetic": "/rɪˈspɑːns/", "pos": "n.", "meaning": "回覆；反應", "phrases": ["in response to", "official response"], "synonyms": ["answer", "reply"], "antonyms": ["inquiry", "question"], "example": "We are still waiting for a formal response from the supplier."},
    "boarding": {"phonetic": "/ˈbɔːrdɪŋ/", "pos": "n.", "meaning": "登機", "phrases": ["boarding pass", "boarding gate"], "synonyms": ["embarkation"], "antonyms": ["disembarkation"], "example": "Boarding for the flight will commence approximately 30 minutes before departure."},
    "departure": {"phonetic": "/dɪˈpɑːrtʃər/", "pos": "n.", "meaning": "出發；離開", "phrases": ["scheduled departure", "departure gate"], "synonyms": ["leaving", "exit"], "antonyms": ["arrival"], "example": "The sudden departure of the CEO surprised everyone in the company."},
    "arrival": {"phonetic": "/əˈraɪvl/", "pos": "n.", "meaning": "抵達", "phrases": ["estimated time of arrival", "late arrival"], "synonyms": ["coming", "reaching"], "antonyms": ["departure"], "example": "Please notify us of your expected arrival time at the airport."},
    "shuttle": {"phonetic": "/ˈʃʌtl/", "pos": "n.", "meaning": "接駁車", "phrases": ["airport shuttle", "shuttle bus"], "synonyms": ["transport"], "antonyms": [], "example": "A complimentary shuttle bus runs between the hotel and the city center."},
    "rent": {"phonetic": "/rent/", "pos": "n./v.", "meaning": "租金；租用", "phrases": ["monthly rent", "rent a car"], "synonyms": ["lease", "hire"], "antonyms": [], "example": "The monthly rent for the office space is two thousand dollars."}
}

with open('data_green.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data:
        # 更新內容
        item.update(enriched_data[word])

with open('data_green.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修前 50 個高品質單字。")
