import json
import os

def update_vocab():
    # 第十一批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Unanimous", "phonetic": "/juˈnænɪməs/", "pos": "adj.", "meaning": "全體一致的", "level": "blue", "phrases": ["unanimous decision", "unanimous support"], "synonyms": ["agreed", "united"], "antonyms": ["divided", "split"], "example": "The board of directors reached a unanimous decision to appoint the new CEO."},
        {"word": "Underestimate", "phonetic": "/ˌʌndərˈestɪmeɪt/", "pos": "v./n.", "meaning": "低估", "level": "blue", "phrases": ["underestimate the cost", "grossly underestimate"], "synonyms": ["undervalue"], "antonyms": ["overestimate"], "example": "We should not underestimate the impact of the new regulations on our international operations."},
        {"word": "Undergo", "phonetic": "/ˌʌndərˈɡoʊ/", "pos": "v.", "meaning": "經歷, 遭受, 接受(檢查/手術)", "level": "blue", "phrases": ["undergo training", "undergo a change"], "synonyms": ["experience", "endure"], "antonyms": [], "example": "All new recruits are required to undergo a rigorous three-week training program."},
        {"word": "Undermine", "phonetic": "/ˌʌndərˈmaɪn/", "pos": "v.", "meaning": "削弱, 暗中破壞", "level": "blue", "phrases": ["undermine authority", "undermine confidence"], "synonyms": ["weaken", "sabotage"], "antonyms": ["strengthen", "support"], "example": "Constant criticism from management can seriously undermine employee morale."},
        {"word": "Undertake", "phonetic": "/ˌʌndərˈteɪk/", "pos": "v.", "meaning": "承擔, 著手, 答應", "level": "blue", "phrases": ["undertake a project", "undertake a task"], "synonyms": ["embark on", "assume"], "antonyms": [], "example": "The consulting firm has agreed to undertake a comprehensive review of our IT infrastructure."},
        {"word": "Unilateral", "phonetic": "/ˌjuːnɪˈlætrəl/", "pos": "adj.", "meaning": "單方面的", "level": "blue", "phrases": ["unilateral decision", "unilateral action"], "synonyms": ["one-sided"], "antonyms": ["bilateral", "multilateral"], "example": "The company's unilateral decision to cut benefits led to widespread employee dissatisfaction."},
        {"word": "Unprecedented", "phonetic": "/ʌnˈpresɪdentɪd/", "pos": "adj.", "meaning": "史無前例的", "level": "blue", "phrases": ["unprecedented growth", "unprecedented demand"], "synonyms": ["extraordinary", "unparalleled"], "antonyms": ["common", "normal"], "example": "The tech industry is currently experiencing an unprecedented level of innovation and change."},
        {"word": "Unveil", "phonetic": "/ˌʌnˈveɪl/", "pos": "v.", "meaning": "揭幕, 公布, 推出", "level": "blue", "phrases": ["unveil a plan", "unveil a product"], "synonyms": ["reveal", "disclose"], "antonyms": ["conceal", "hide"], "example": "The automobile manufacturer is planning to unveil its latest electric SUV at the international auto show."},
        {"word": "Upgrade", "phonetic": "/ˌʌpˈɡreɪd/", "pos": "v./n.", "meaning": "升級, 提升", "level": "blue", "phrases": ["software upgrade", "upgrade the facility"], "synonyms": ["enhance", "improve"], "antonyms": ["downgrade"], "example": "We need to upgrade our internal server system to handle the increasing volume of data traffic."},
        {"word": "Utility", "phonetic": "/juːˈtɪləti/", "pos": "n.", "meaning": "公共設施(如電/水), 效用", "level": "blue", "phrases": ["utility bill", "public utility"], "synonyms": ["usefulness", "service"], "antonyms": [], "example": "The cost of utilities, especially electricity and water, has risen significantly this year."},
        {"word": "Utilize", "phonetic": "/ˈjuːtəlaɪz/", "pos": "v.", "meaning": "利用, 運用", "level": "blue", "phrases": ["utilize resources", "fully utilize"], "synonyms": ["employ", "exploit"], "antonyms": [], "example": "The marketing team plans to utilize social media platforms to reach a wider target audience."},
        {"word": "Vacancy", "phonetic": "/ˈveɪkənsi/", "pos": "n.", "meaning": "空缺, 職缺, 空房", "level": "blue", "phrases": ["job vacancy", "no vacancies"], "synonyms": ["opening", "gap"], "antonyms": [], "example": "There is currently a vacancy for a senior accountant in our financial department."},
        {"word": "Validate", "phonetic": "/ˈvælɪdeɪt/", "pos": "v.", "meaning": "驗證, 使生效, 批准", "level": "blue", "phrases": ["validate a ticket", "validate the data"], "synonyms": ["verify", "confirm"], "antonyms": ["invalidate"], "example": "Please remember to validate your parking ticket at the reception desk before you leave."},
        {"word": "Valuation", "phonetic": "/ˌvæljuˈeɪʃn/", "pos": "n.", "meaning": "估價, 評價", "level": "blue", "phrases": ["market valuation", "property valuation"], "synonyms": ["assessment", "appraisal"], "antonyms": [], "example": "The company's current market valuation has reached a record high of ten billion dollars."},
        {"word": "Variable", "phonetic": "/ˈverieɪbl/", "pos": "adj./n.", "meaning": "易變的, 變數", "level": "blue", "phrases": ["variable costs", "independent variable"], "synonyms": ["fluctuating", "changeable"], "antonyms": ["constant", "fixed"], "example": "Raw material prices are a key variable that can significantly affect our annual profit margins."},
        {"word": "Variance", "phonetic": "/ˈveriens/", "pos": "n.", "meaning": "差異, 不一致, 變異數", "level": "blue", "phrases": ["at variance with", "budget variance"], "synonyms": ["discrepancy", "difference"], "antonyms": ["agreement", "consistency"], "example": "The accountant noticed a significant variance between the actual spending and the initial budget."},
        {"word": "Vendor", "phonetic": "/ˈvendər/", "pos": "n.", "meaning": "供應商, 賣主", "level": "blue", "phrases": ["approved vendor", "street vendor"], "synonyms": ["supplier", "seller"], "antonyms": ["buyer", "customer"], "example": "We are currently evaluating several new vendors to supply components for our production line."},
        {"word": "Venue", "phonetic": "/ˈvenjuː/", "pos": "n.", "meaning": "會場, 地點", "level": "blue", "phrases": ["conference venue", "wedding venue"], "synonyms": ["location", "site"], "antonyms": [], "example": "The convention center has been chosen as the venue for next year's international trade fair."},
        {"word": "Verdict", "phonetic": "/ˈvɜːrdɪkt/", "pos": "n.", "meaning": "裁決, 判決, 定論", "level": "blue", "phrases": ["reach a verdict", "final verdict"], "synonyms": ["judgment", "decision"], "antonyms": [], "example": "The jury is expected to reach a verdict in the high-profile fraud case by the end of the week."},
        {"word": "Versatile", "phonetic": "/ˈvɜːrsətl/", "pos": "adj.", "meaning": "多才多藝的, 多功能的", "level": "blue", "phrases": ["versatile tool", "versatile employee"], "synonyms": ["adaptable", "flexible"], "antonyms": [], "example": "We are looking for a versatile individual who can handle both administrative and marketing tasks."},
        {"word": "Viable", "phonetic": "/ˈvaɪəbl/", "pos": "adj.", "meaning": "可行的, 能活下去的", "level": "blue", "phrases": ["commercially viable", "economically viable"], "synonyms": ["feasible", "workable"], "antonyms": ["unfeasible", "impossible"], "example": "The board is conducting a study to see if the new project is commercially viable in the long term."},
        {"word": "Vicinity", "phonetic": "/vəˈsɪnəti/", "pos": "n.", "meaning": "鄰近, 附近", "level": "blue", "phrases": ["in the vicinity of", "immediate vicinity"], "synonyms": ["neighborhood", "proximity"], "antonyms": [], "example": "There are several high-quality hotels and restaurants in the immediate vicinity of the airport."},
        {"word": "Violate", "phonetic": "/ˈvaɪəleɪt/", "pos": "v.", "meaning": "違反, 侵犯", "level": "blue", "phrases": ["violate the law", "violate a contract"], "synonyms": ["breach", "infringe"], "antonyms": ["comply", "observe"], "example": "Companies that violate environmental regulations may face heavy fines and legal action."},
        {"word": "Virtual", "phonetic": "/ˈvɜːrtʃuəl/", "pos": "adj.", "meaning": "虛擬的, 實質上的", "level": "blue", "phrases": ["virtual meeting", "virtual reality"], "synonyms": [], "antonyms": ["real", "physical"], "example": "The company has decided to hold its annual general meeting as a virtual event this year."},
        {"word": "Vocational", "phonetic": "/voʊˈkeɪʃənl/", "pos": "adj.", "meaning": "職業的, 職業技術的", "level": "blue", "phrases": ["vocational training", "vocational school"], "synonyms": ["professional", "occupational"], "antonyms": ["academic"], "example": "The government is increasing funding for vocational training programs to help reduce unemployment."},
        {"word": "Volatile", "phonetic": "/ˈvɑːlətl/", "pos": "adj.", "meaning": "不穩定的, 易揮發的", "level": "blue", "phrases": ["volatile market", "highly volatile"], "synonyms": ["unstable", "unpredictable"], "antonyms": ["stable", "steady"], "example": "Investors are cautious because of the current volatile situation in the global stock market."},
        {"word": "Voucher", "phonetic": "/ˈvaʊtʃər/", "pos": "n.", "meaning": "禮券, 憑證", "level": "blue", "phrases": ["gift voucher", "travel voucher"], "synonyms": ["coupon", "token"], "antonyms": [], "example": "The airline provided passengers with meal vouchers following the four-hour flight delay."},
        {"word": "Vulnerable", "phonetic": "/ˈvʌlnərəbl/", "pos": "adj.", "meaning": "易受傷的, 脆弱的", "level": "blue", "phrases": ["vulnerable to attack", "economically vulnerable"], "synonyms": ["defenseless", "exposed"], "antonyms": ["invulnerable", "secure"], "example": "Small businesses are particularly vulnerable to economic downturns and fluctuations in the market."},
        {"word": "Waive", "phonetic": "/weɪv/", "pos": "v.", "meaning": "放棄(權利), 免除(費用)", "level": "blue", "phrases": ["waive a fee", "waive a right"], "synonyms": ["relinquish", "forgo"], "antonyms": ["enforce", "claim"], "example": "The bank agreed to waive the late payment fee as a gesture of goodwill to the long-term customer."},
        {"word": "Warranty", "phonetic": "/ˈwɔːrənti/", "pos": "n.", "meaning": "保固, 保證書", "level": "blue", "phrases": ["under warranty", "extended warranty"], "synonyms": ["guarantee"], "antonyms": [], "example": "All electronic products sold in this store come with a standard one-year manufacturer's warranty."},
        {"word": "Withdrawal", "phonetic": "/wɪðˈdrɔːəl/", "pos": "n.", "meaning": "提款, 撤回, 退出", "level": "blue", "phrases": ["cash withdrawal", "withdrawal of funds"], "synonyms": ["removal", "retirement"], "antonyms": ["deposit", "insertion"], "example": "The sudden withdrawal of the primary sponsor has left the event's organizers in a difficult position."},
        {"word": "Workforce", "phonetic": "/ˈwɜːrkfɔːrs/", "pos": "n.", "meaning": "勞動力, 全體員工", "level": "blue", "phrases": ["skilled workforce", "diverse workforce"], "synonyms": ["personnel", "staff"], "antonyms": [], "example": "The company is committed to building a diverse workforce that reflects the global market it serves."},
        {"word": "Yield", "phonetic": "/jiːld/", "pos": "v./n.", "meaning": "產出, 獲利, 屈服", "level": "blue", "phrases": ["high yield", "yield to pressure"], "synonyms": ["produce", "generate", "return"], "antonyms": [], "example": "The new manufacturing process is expected to significantly increase the overall yield of the production line."},
        {"word": "Abstract", "phonetic": "/ˈæbstrækt/", "pos": "n./adj.", "meaning": "摘要, 抽象的", "level": "blue", "phrases": ["extended abstract", "abstract idea"], "synonyms": ["summary", "synopsis"], "antonyms": ["concrete"], "example": "Please submit a 200-word abstract of your research proposal by the end of the month."},
        {"word": "Accumulate", "phonetic": "/əˈkjuːmjəleɪt/", "pos": "v.", "meaning": "累積, 堆積", "level": "blue", "phrases": ["accumulate wealth", "accumulate data"], "synonyms": ["amass", "collect"], "antonyms": ["disperse", "dissipate"], "example": "Over time, even small monthly savings can accumulate into a significant amount of money."},
        {"word": "Acknowledge", "phonetic": "/əkˈnɑːlɪdʒ/", "pos": "v.", "meaning": "承認, 確認(收悉), 感謝", "level": "blue", "phrases": ["acknowledge receipt", "fully acknowledge"], "synonyms": ["admit", "recognize"], "antonyms": ["deny", "ignore"], "example": "We would like to acknowledge the generous support provided by our corporate sponsors this year."},
        {"word": "Adapt", "phonetic": "/əˈdæpt/", "pos": "v.", "meaning": "適應, 改編, 調整", "level": "blue", "phrases": ["adapt to change", "adapt for a movie"], "synonyms": ["adjust", "modify"], "antonyms": [], "example": "Successful businesses are those that are able to adapt quickly to changing market conditions."},
        {"word": "Adequate", "phonetic": "/ˈædɪkwət/", "pos": "adj.", "meaning": "充足的, 適當的", "level": "blue", "phrases": ["adequate funding", "adequate preparation"], "synonyms": ["sufficient", "enough"], "antonyms": ["inadequate", "insufficient"], "example": "Please ensure that you have adequate insurance coverage before you embark on your international trip."},
        {"word": "Adjacent", "phonetic": "/əˈdʒeɪsnt/", "pos": "adj.", "meaning": "鄰近的, 毗連的", "level": "blue", "phrases": ["adjacent building", "adjacent to the park"], "synonyms": ["neighboring", "adjoining"], "antonyms": ["distant", "remote"], "example": "The marketing department is located in the building adjacent to the main headquarters."},
        {"word": "Administrate", "phonetic": "/ədˈmɪnɪstreɪt/", "pos": "v.", "meaning": "管理, 執行", "level": "blue", "phrases": ["administrate the fund", "administrate justice"], "synonyms": ["manage", "direct"], "antonyms": [], "example": "She was hired to administrate the new employee benefits program across all regional offices."},
        {"word": "Advocate", "phonetic": "/ˈædvəkeɪt/", "pos": "v./n.", "meaning": "提倡, 主張, 擁護者", "level": "blue", "phrases": ["advocate for change", "consumer advocate"], "synonyms": ["support", "promote"], "antonyms": ["oppose", "criticize"], "example": "Many health professionals advocate for a balanced diet and regular exercise to improve overall well-being."},
        {"word": "Aggregate", "phonetic": "/ˈæɡrɪɡət/", "pos": "adj./n./v.", "meaning": "總計的, 集合體, 合計", "level": "blue", "phrases": ["aggregate demand", "in the aggregate"], "synonyms": ["total", "cumulative"], "antonyms": ["individual", "separate"], "example": "The aggregate annual revenue of the group exceeded ten billion dollars for the first time."},
        {"word": "Albeit", "phonetic": "/ˌɔːlˈbiːɪt/", "pos": "conj.", "meaning": "儘管, 雖然", "level": "blue", "phrases": ["albeit slowly", "albeit briefly"], "synonyms": ["although", "even though"], "antonyms": [], "example": "The company is making steady progress, albeit at a slower pace than initially expected."},
        {"word": "Allocate", "phonetic": "/ˈæləkeɪt/", "pos": "v.", "meaning": "分配, 撥款", "level": "blue", "phrases": ["allocate resources", "allocate funds"], "synonyms": ["assign", "distribute"], "antonyms": [], "example": "The committee decided to allocate more resources to the research and development department this year."},
        {"word": "Alternative", "phonetic": "/ɔːlˈtɜːrnətɪv/", "pos": "n./adj.", "meaning": "替代方案, 另類的", "level": "blue", "phrases": ["alternative energy", "no alternative"], "synonyms": ["option", "substitute"], "antonyms": [], "example": "Solar and wind power are increasingly being seen as viable alternatives to fossil fuels."},
        {"word": "Ambiguous", "phonetic": "/æmˈbɪɡjuəs/", "pos": "adj.", "meaning": "含糊不清的, 有歧義的", "level": "blue", "phrases": ["ambiguous statement", "ambiguous wording"], "synonyms": ["vague", "unclear"], "antonyms": ["clear", "explicit"], "example": "The wording of the contract is somewhat ambiguous and could lead to potential disputes in the future."},
        {"word": "Analogy", "phonetic": "/əˈnælədʒi/", "pos": "n.", "meaning": "類比, 類推", "level": "blue", "phrases": ["draw an analogy", "by analogy"], "synonyms": ["comparison", "similarity"], "antonyms": [], "example": "The presenter used an interesting analogy to explain the complex concepts of the new software system."},
        {"word": "Analyze", "phonetic": "/ˈænəlaɪz/", "pos": "v.", "meaning": "分析", "level": "blue", "phrases": ["analyze data", "analyze the situation"], "synonyms": ["examine", "investigate"], "antonyms": [], "example": "We need to carefully analyze the latest market trends before making a final decision on the expansion."},
        {"word": "Anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "pos": "v.", "meaning": "預期, 預料", "level": "blue", "phrases": ["anticipate problems", "eagerly anticipate"], "synonyms": ["expect", "foresee"], "antonyms": [], "example": "The company is anticipating a significant increase in sales during the upcoming holiday season."},
        {"word": "Apparent", "phonetic": "/əˈpærənt/", "pos": "adj.", "meaning": "明顯的, 表面上的", "level": "blue", "phrases": ["become apparent", "for no apparent reason"], "synonyms": ["obvious", "evident"], "antonyms": ["hidden", "obscure"], "example": "It soon became apparent that the initial projections for the project were far too optimistic."},
        {"word": "Append", "phonetic": "/əˈpend/", "pos": "v.", "meaning": "附加, 增補", "level": "blue", "phrases": ["append a file", "append a signature"], "synonyms": ["attach", "add"], "antonyms": [], "example": "Please remember to append a copy of your resume to the online application form."},
        {"word": "Appreciate", "phonetic": "/əˈpriːʃieɪt/", "pos": "v.", "meaning": "欣賞, 感謝, 增值", "level": "blue", "phrases": ["fully appreciate", "greatly appreciate"], "synonyms": ["value", "thank"], "antonyms": ["depreciate"], "example": "We greatly appreciate your patience and understanding while we resolve the technical issues."},
        {"word": "Appropriate", "phonetic": "/əˈproʊpriət/", "pos": "adj./v.", "meaning": "適當的, 撥款, 盜用", "level": "blue", "phrases": ["appropriate action", "appropriate funds"], "synonyms": ["suitable", "proper"], "antonyms": ["inappropriate", "unsuitable"], "example": "The committee will take appropriate action once the full investigation has been completed."},
        {"word": "Approximate", "phonetic": "/əˈprɑːksɪmət/", "pos": "adj./v.", "meaning": "大約的, 接近", "level": "blue", "phrases": ["approximate cost", "approximate time"], "synonyms": ["rough", "estimated"], "antonyms": ["exact", "precise"], "example": "The approximate cost of the renovation project is expected to be around fifty thousand dollars."},
        {"word": "Arbitrary", "phonetic": "/ˈɑːrbɪtreri/", "pos": "adj.", "meaning": "隨意的, 專斷的", "level": "blue", "phrases": ["arbitrary decision", "arbitrary rule"], "synonyms": ["random", "capricious"], "antonyms": ["rational", "logical"], "example": "The decision to cut the budget seemed arbitrary and was not based on any clear financial data."},
        {"word": "Aspect", "phonetic": "/ˈæspekt/", "pos": "n.", "meaning": "方面, 面貌, 朝向", "level": "blue", "phrases": ["key aspect", "every aspect of"], "synonyms": ["facet", "feature"], "antonyms": [], "example": "Safety is a key aspect of our operations that is never compromised for any reason."},
        {"word": "Assemble", "phonetic": "/əˈsembl/", "pos": "v.", "meaning": "組裝, 集合", "level": "blue", "phrases": ["assemble a team", "easily assembled"], "synonyms": ["gather", "collect", "build"], "antonyms": ["disassemble", "scatter"], "example": "The marketing manager is trying to assemble a team of experts to handle the new campaign."},
        {"word": "Assess", "phonetic": "/əˈses/", "pos": "v.", "meaning": "評估, 估定(價值/稅額)", "level": "blue", "phrases": ["assess the risk", "assess performance"], "synonyms": ["evaluate", "appraise"], "antonyms": [], "example": "The independent firm was hired to assess the potential environmental impact of the new factory."},
        {"word": "Assign", "phonetic": "/əˈsaɪn/", "pos": "v.", "meaning": "指派, 分配", "level": "blue", "phrases": ["assign a task", "assign a value"], "synonyms": ["allocate", "allot"], "antonyms": [], "example": "The manager decided to assign the project to the most experienced members of the team."},
        {"word": "Assist", "phonetic": "/əˈsɪst/", "pos": "v.", "meaning": "協助, 幫助", "level": "blue", "phrases": ["assist with", "ready to assist"], "synonyms": ["help", "aid"], "antonyms": ["hinder", "obstruct"], "example": "The local government is providing grants to assist small businesses during the economic recovery."},
        {"word": "Assume", "phonetic": "/əˈsuːm/", "pos": "v.", "meaning": "假設, 承擔(責任), 呈現(特徵)", "level": "blue", "phrases": ["assume responsibility", "assume the role"], "synonyms": ["presume", "undertake"], "antonyms": [], "example": "She is prepared to assume the role of acting manager while her supervisor is on maternity leave."},
        {"word": "Assure", "phonetic": "/əˈʃʊr/", "pos": "v.", "meaning": "向...保證, 使放心", "level": "blue", "phrases": ["assure someone of", "rest assured"], "synonyms": ["guarantee", "promise"], "antonyms": [], "example": "The technician assured us that the server issues would be resolved by the end of the day."},
        {"word": "Attach", "phonetic": "/əˈtætʃ/", "pos": "v.", "meaning": "附上, 繫住", "level": "blue", "phrases": ["attach a file", "firmly attached"], "synonyms": ["append", "connect"], "antonyms": ["detach", "separate"], "example": "Please remember to attach a copy of the receipt to your expense reimbursement form."},
        {"word": "Attain", "phonetic": "/əˈteɪn/", "pos": "v.", "meaning": "達成, 獲得", "level": "blue", "phrases": ["attain a goal", "attain success"], "synonyms": ["achieve", "reach"], "antonyms": ["fail", "lose"], "example": "The company has attained a significant share of the domestic market in just three years."},
        {"word": "Attitude", "phonetic": "/ˈætɪtuːd/", "pos": "n.", "meaning": "態度, 看法", "level": "blue", "phrases": ["positive attitude", "professional attitude"], "synonyms": ["outlook", "mindset"], "antonyms": [], "example": "A positive and professional attitude is essential for success in any customer-facing role."},
        {"word": "Attribute", "phonetic": "/əˈtrɪbjuːt/", "pos": "v./n.", "meaning": "歸因於, 特質", "level": "blue", "phrases": ["attribute to", "key attribute"], "synonyms": ["ascribe", "feature"], "antonyms": [], "example": "The CEO attributes the company's recent success to the hard work and dedication of all its employees."},
        {"word": "Audit", "phonetic": "/ˈɔːdɪt/", "pos": "n./v.", "meaning": "審計, 查帳", "level": "blue", "phrases": ["internal audit", "financial audit"], "synonyms": ["inspection", "scrutiny"], "antonyms": [], "example": "The company undergoes a thorough financial audit by an independent firm every year."},
        {"word": "Author", "phonetic": "/ˈɔːθər/", "pos": "n./v.", "meaning": "作者, 創始者, 撰寫", "level": "blue", "phrases": ["best-selling author", "author a report"], "synonyms": ["writer", "creator"], "antonyms": [], "example": "He has authored several influential books on modern marketing and management strategies."},
        {"word": "Authority", "phonetic": "/əˈθɔːrəti/", "pos": "n.", "meaning": "權威, 當局, 授權", "level": "blue", "phrases": ["local authority", "position of authority"], "synonyms": ["power", "jurisdiction"], "antonyms": [], "example": "The matter has been referred to the relevant authorities for further investigation."},
        {"word": "Automate", "phonetic": "/ˈɔːtəmeɪt/", "pos": "v.", "meaning": "使自動化", "level": "blue", "phrases": ["fully automate", "automate the process"], "synonyms": [], "antonyms": ["manual"], "example": "The company plans to automate its production line to increase efficiency and reduce costs."},
        {"word": "Available", "phonetic": "/əˈveɪləbl/", "pos": "adj.", "meaning": "可獲得的, 有空的", "level": "blue", "phrases": ["readily available", "available for comment"], "synonyms": ["accessible", "free"], "antonyms": ["unavailable", "busy"], "example": "The latest version of the software is now available for download on our official website."},
        {"word": "Aware", "phonetic": "/əˈwer/", "pos": "adj.", "meaning": "意識到的, 知道的", "level": "blue", "phrases": ["become aware of", "fully aware"], "synonyms": ["conscious", "informed"], "antonyms": ["unaware", "ignorant"], "example": "Management is fully aware of the issues and is working hard to find a solution."},
        {"word": "Behalf", "phonetic": "/bɪˈhæf/", "pos": "n.", "meaning": "代表, 利益", "level": "blue", "phrases": ["on behalf of", "in behalf of"], "synonyms": [], "antonyms": [], "example": "I am writing to you on behalf of the board of directors regarding the upcoming annual general meeting."},
        {"word": "Beneficial", "phonetic": "/ˌbenɪˈfɪʃl/", "pos": "adj.", "meaning": "有益的, 有利的", "level": "blue", "phrases": ["mutually beneficial", "highly beneficial"], "synonyms": ["advantageous", "helpful"], "antonyms": ["detrimental", "harmful"], "example": "The new trade agreement is expected to be mutually beneficial for both participating countries."},
        {"word": "Benefit", "phonetic": "/ˈbenɪfɪt/", "pos": "n./v.", "meaning": "利益, 福利, 得益於", "level": "blue", "phrases": ["employee benefits", "benefit from"], "synonyms": ["advantage", "profit"], "antonyms": ["disadvantage", "drawback"], "example": "The company offers a comprehensive range of benefits, including health insurance and pension plans."},
        {"word": "Bias", "phonetic": "/ˈbaɪəs/", "pos": "n./v.", "meaning": "偏見, 偏袒", "level": "blue", "phrases": ["personal bias", "gender bias"], "synonyms": ["prejudice", "partiality"], "antonyms": ["objectivity", "impartiality"], "example": "The hiring committee must ensure that there is no bias in the recruitment and selection process."},
        {"word": "Bond", "phonetic": "/bɑːnd/", "pos": "n./v.", "meaning": "債券, 聯繫, 結合", "level": "blue", "phrases": ["government bond", "strong bond"], "synonyms": ["tie", "connection", "security"], "antonyms": [], "example": "The company issued several long-term bonds to raise funds for its international expansion."},
        {"word": "Brief", "phonetic": "/briːf/", "pos": "adj./v./n.", "meaning": "簡短的, 簡報", "level": "blue", "phrases": ["in brief", "brief meeting"], "synonyms": ["short", "concise"], "antonyms": ["long", "extended"], "example": "The manager gave a brief summary of the project's progress at the Monday morning meeting."},
        {"word": "Bulk", "phonetic": "/bʌlk/", "pos": "n./adj.", "meaning": "體積, 大多數, 大宗的", "level": "blue", "phrases": ["in bulk", "bulk purchase"], "synonyms": ["mass", "majority"], "antonyms": ["minority"], "example": "Buying office supplies in bulk can lead to significant cost savings over the long term."},
        {"word": "Capability", "phonetic": "/ˌkeɪpəˈbɪləti/", "pos": "n.", "meaning": "能力, 才能", "level": "blue", "phrases": ["technical capability", "beyond one's capability"], "synonyms": ["ability", "capacity"], "antonyms": ["inability", "incapacity"], "example": "The new software system has enhanced our overall data processing and analysis capabilities."},
        {"word": "Capacity", "phonetic": "/kəˈpæsəti/", "pos": "n.", "meaning": "容量, 能力, 職位", "level": "blue", "phrases": ["production capacity", "in one's capacity as"], "synonyms": ["volume", "ability"], "antonyms": [], "example": "The factory is currently operating at full capacity to meet the increasing demand for its products."},
        {"word": "Category", "phonetic": "/ˈkætəɡɔːri/", "pos": "n.", "meaning": "類別, 範疇", "level": "blue", "phrases": ["broad category", "fall into a category"], "synonyms": ["class", "group"], "antonyms": [], "example": "These products fall into the broad category of sustainable and eco-friendly home goods."},
        {"word": "Cease", "phonetic": "/siːs/", "pos": "v.", "meaning": "停止, 終止", "level": "blue", "phrases": ["cease operations", "cease to exist"], "synonyms": ["stop", "terminate"], "antonyms": ["commence", "start"], "example": "The company was forced to cease its operations following the sudden withdrawal of its primary investor."},
        {"word": "Challenge", "phonetic": "/ˈtʃælɪndʒ/", "pos": "n./v.", "meaning": "挑戰, 質疑", "level": "blue", "phrases": ["face a challenge", "major challenge"], "synonyms": ["obstacle", "difficulty", "dispute"], "antonyms": [], "example": "One of the major challenges facing the industry is the rapid pace of technological change."},
        {"word": "Channel", "phonetic": "/ˈtʃænl/", "pos": "n./v.", "meaning": "管道, 頻道, 引導", "level": "blue", "phrases": ["distribution channel", "communication channel"], "synonyms": ["way", "means"], "antonyms": [], "example": "We are currently evaluating several new distribution channels to expand our reach in the Asian market."},
        {"word": "Chapter", "phonetic": "/ˈtʃæptər/", "pos": "n.", "meaning": "章節, 階段, 分會", "level": "blue", "phrases": ["local chapter", "final chapter"], "synonyms": ["section", "phase"], "antonyms": [], "example": "The local chapter of the international professional association will hold its annual meeting next month."},
        {"word": "Chart", "phonetic": "/tʃɑːrt/", "pos": "n./v.", "meaning": "圖表, 繪製", "level": "blue", "phrases": ["organization chart", "pie chart"], "synonyms": ["diagram", "graph"], "antonyms": [], "example": "The presentation included several charts and graphs to illustrate the company's recent financial performance."},
        {"word": "Chemical", "phonetic": "/ˈkemɪkl/", "pos": "n./adj.", "meaning": "化學物質, 化學的", "level": "blue", "phrases": ["chemical industry", "hazardous chemicals"], "synonyms": [], "antonyms": [], "example": "The company specializes in the development and manufacture of high-quality industrial chemicals."},
        {"word": "Circumstance", "phonetic": "/ˈsɜːrkəmstæns/", "pos": "n.", "meaning": "情況, 環境", "level": "blue", "phrases": ["under the circumstances", "unforeseen circumstances"], "synonyms": ["situation", "condition"], "antonyms": [], "example": "Due to unforeseen circumstances, we have been forced to postpone the conference until further notice."},
        {"word": "Civil", "phonetic": "/ˈsɪvl/", "pos": "adj.", "meaning": "民事的, 公民的, 有禮貌的", "level": "blue", "phrases": ["civil law", "civil rights"], "synonyms": ["public", "polite"], "antonyms": ["military", "criminal"], "example": "The case has been referred to the civil court for resolution following the failure of arbitration."},
        {"word": "Clarify", "phonetic": "/ˈklærəfaɪ/", "pos": "v.", "meaning": "澄清, 闡明", "level": "blue", "phrases": ["clarify a point", "need to clarify"], "synonyms": ["explain", "elucidate"], "antonyms": ["confuse", "obscure"], "example": "Could you please clarify your earlier statement regarding the proposed budget for next year?"}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
