import json
import os

def update_vocab():
    # 第十三批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Coherent", "phonetic": "/koʊˈhɪrənt/", "pos": "adj.", "meaning": "連貫的, 有條理的", "level": "blue", "phrases": ["coherent strategy", "coherent argument"], "synonyms": ["logical", "consistent"], "antonyms": ["incoherent"], "example": "The marketing team needs to develop a more coherent strategy to unify our brand image across all platforms."},
        {"word": "Cohesion", "phonetic": "/koʊˈhiːʒn/", "pos": "n.", "meaning": "凝聚力, 結合", "level": "blue", "phrases": ["social cohesion", "team cohesion"], "synonyms": ["unity", "solidarity"], "antonyms": ["division"], "example": "Team-building exercises are designed to improve cohesion and trust among employees in the department."},
        {"word": "Coincide", "phonetic": "/ˌkoʊɪnˈsaɪd/", "pos": "v.", "meaning": "同時發生, 符合, 一致", "level": "blue", "phrases": ["coincide with", "dates coincide"], "synonyms": ["concur", "clash"], "antonyms": [], "example": "The launch of our new product is timed to coincide with the opening of the international trade fair."},
        {"word": "Coincidence", "phonetic": "/koʊˈɪnsɪdəns/", "pos": "n.", "meaning": "巧合", "level": "blue", "phrases": ["by coincidence", "remarkable coincidence"], "synonyms": ["chance", "accident"], "antonyms": [], "example": "By a remarkable coincidence, I met our former sales director at the airport in London yesterday."},
        {"word": "Collaborate", "phonetic": "/kəˈlæbəreɪt/", "pos": "v.", "meaning": "合作, 協作", "level": "blue", "phrases": ["collaborate on a project", "closely collaborate"], "synonyms": ["cooperate", "partner"], "antonyms": [], "example": "We are looking for opportunities to collaborate with international research institutions on this new project."},
        {"word": "Collaboration", "phonetic": "/kəˌlæbəˈreɪʃn/", "pos": "n.", "meaning": "合作, 協作", "level": "blue", "phrases": ["in collaboration with", "fruitful collaboration"], "synonyms": ["partnership", "cooperation"], "antonyms": [], "example": "The success of the campaign was the result of a fruitful collaboration between the creative and data teams."},
        {"word": "Collaborative", "phonetic": "/kəˈlæbəreɪtɪv/", "pos": "adj.", "meaning": "合作的, 協作的", "level": "blue", "phrases": ["collaborative effort", "collaborative environment"], "synonyms": ["joint", "communal"], "antonyms": [], "example": "The new office layout is designed to foster a more collaborative environment for software development."},
        {"word": "Collapse", "phonetic": "/kəˈlæps/", "pos": "v./n.", "meaning": "倒塌, 崩潰, 暴跌", "level": "blue", "phrases": ["market collapse", "economic collapse"], "synonyms": ["breakdown", "failure"], "antonyms": ["rise", "recovery"], "example": "Several small banks were forced to close following the sudden collapse of the local real estate market."},
        {"word": "Colleague", "phonetic": "/ˈkɑːliːɡ/", "pos": "n.", "meaning": "同事, 同僚", "level": "blue", "phrases": ["respected colleague", "former colleague"], "synonyms": ["coworker", "associate"], "antonyms": [], "example": "I would like to introduce you to my colleague, Sarah, who manages our regional distribution center."},
        {"word": "Collective", "phonetic": "/kəˈlektɪv/", "pos": "adj./n.", "meaning": "集體的, 共同的", "level": "blue", "phrases": ["collective effort", "collective bargaining"], "synonyms": ["joint", "combined"], "antonyms": ["individual"], "example": "The company's success is a reflection of the collective effort and dedication of all our staff members."},
        {"word": "Collision", "phonetic": "/kəˈlɪʒn/", "pos": "n.", "meaning": "碰撞, 衝突", "level": "blue", "phrases": ["head-on collision", "collision of interests"], "synonyms": ["impact", "crash", "conflict"], "antonyms": [], "example": "There was a significant collision of interests between the shareholders and the board regarding the new investment."},
        {"word": "Columnist", "phonetic": "/ˈkɑːləmnɪst/", "pos": "n.", "meaning": "專欄作家", "level": "blue", "phrases": ["political columnist", "financial columnist"], "synonyms": [], "antonyms": [], "example": "The financial columnist provided a critical analysis of the government's new economic policy in this morning's paper."},
        {"word": "Combat", "phonetic": "/ˈkɑːmbæt/", "pos": "v./n.", "meaning": "戰鬥, 打擊, 反對", "level": "blue", "phrases": ["combat inflation", "combat corruption"], "synonyms": ["fight", "oppose"], "antonyms": [], "example": "The central bank has introduced several measures to combat rising inflation and stabilize the economy."},
        {"word": "Combination", "phonetic": "/ˌkɑːmbɪˈneɪʃn/", "pos": "n.", "meaning": "結合, 組合", "level": "blue", "phrases": ["in combination with", "powerful combination"], "synonyms": ["mixture", "blend"], "antonyms": [], "example": "The new smartphone offers a powerful combination of high-end features and an affordable price tag."},
        {"word": "Combine", "phonetic": "/kəmˈbaɪn/", "pos": "v.", "meaning": "結合, 聯合", "level": "blue", "phrases": ["combine resources", "combine efforts"], "synonyms": ["unite", "merge"], "antonyms": ["separate", "divide"], "example": "The two departments decided to combine their resources to better manage the large-scale international project."},
        {"word": "Combustion", "phonetic": "/kəmˈbʌstʃən/", "pos": "n.", "meaning": "燃燒", "level": "blue", "phrases": ["internal combustion engine", "spontaneous combustion"], "synonyms": ["burning"], "antonyms": [], "example": "The transition to electric vehicles is reducing the reliance on internal combustion engines worldwide."},
        {"word": "Commemorate", "phonetic": "/kəˈmeməreɪt/", "pos": "v.", "meaning": "紀念, 慶祝", "level": "blue", "phrases": ["commemorate an anniversary", "commemorate the event"], "synonyms": ["honor", "celebrate"], "antonyms": [], "example": "The company held a special gala dinner to commemorate its 50th anniversary in the manufacturing industry."},
        {"word": "Commemorative", "phonetic": "/kəˈmeməreɪtɪv/", "pos": "adj.", "meaning": "紀念的", "level": "blue", "phrases": ["commemorative plaque", "commemorative event"], "synonyms": [], "antonyms": [], "example": "A commemorative plaque was unveiled at the factory entrance to honor the company's founder."},
        {"word": "Commencement", "phonetic": "/kəˈmensmənt/", "pos": "n.", "meaning": "開始, 畢業典禮", "level": "blue", "phrases": ["commencement date", "commencement speech"], "synonyms": ["beginning", "start", "graduation"], "antonyms": ["conclusion", "end"], "example": "The commencement date for the new highway construction project has been set for early next month."},
        {"word": "Commend", "phonetic": "/kəˈmend/", "pos": "v.", "meaning": "稱讚, 推薦", "level": "blue", "phrases": ["highly commend", "commend someone for"], "synonyms": ["praise", "applaud"], "antonyms": ["criticize", "condemn"], "example": "I would like to commend the entire sales team for their outstanding performance during the last quarter."},
        {"word": "Commendable", "phonetic": "/kəˈmendəbl/", "pos": "adj.", "meaning": "值得讚揚的", "level": "blue", "phrases": ["commendable effort", "highly commendable"], "synonyms": ["praiseworthy", "admirable"], "antonyms": ["disgraceful"], "example": "The employee's quick thinking and decisive action during the emergency were truly commendable."},
        {"word": "Commensurate", "phonetic": "/kəˈmenʃərət/", "pos": "adj.", "meaning": "相稱的, 相當的", "level": "blue", "phrases": ["commensurate with", "salary commensurate with experience"], "synonyms": ["proportionate", "equivalent"], "antonyms": ["inadequate"], "example": "The successful candidate will receive a salary that is commensurate with their experience and qualifications."},
        {"word": "Commentary", "phonetic": "/ˈkɑːmənteri/", "pos": "n.", "meaning": "評論, 解說", "level": "blue", "phrases": ["running commentary", "social commentary"], "synonyms": ["explanation", "analysis"], "antonyms": [], "example": "The evening news included an expert commentary on the potential impact of the new trade agreement."},
        {"word": "Commentator", "phonetic": "/ˈkɑːmənteɪtər/", "pos": "n.", "meaning": "時事評論員, 廣播解說員", "level": "blue", "phrases": ["financial commentator", "sports commentator"], "synonyms": ["analyst", "critic"], "antonyms": [], "example": "The financial commentator suggested that the central bank might raise interest rates later this year."},
        {"word": "Commercialize", "phonetic": "/kəˈmɜːrʃəlaɪz/", "pos": "v.", "meaning": "使商業化", "level": "blue", "phrases": ["commercialize a product", "fully commercialize"], "synonyms": [], "antonyms": [], "example": "The university is working with several private firms to commercialize its latest research in renewable energy."},
        {"word": "Commissioner", "phonetic": "/kəˈmɪʃənər/", "pos": "n.", "meaning": "委員, 專員, 長官", "level": "blue", "phrases": ["police commissioner", "trade commissioner"], "synonyms": [], "antonyms": [], "example": "The European Trade Commissioner is visiting Asia to discuss the terms of a new free trade agreement."},
        {"word": "Commitment", "phonetic": "/kəˈmɪtmənt/", "pos": "n.", "meaning": "承諾, 奉獻, 投入", "level": "blue", "phrases": ["long-term commitment", "show commitment"], "synonyms": ["dedication", "promise"], "antonyms": [], "example": "The company's commitment to environmental sustainability is reflected in its new carbon-neutral manufacturing process."},
        {"word": "Committee", "phonetic": "/kəˈmɪti/", "pos": "n.", "meaning": "委員會", "level": "blue", "phrases": ["steering committee", "advisory committee"], "synonyms": ["board", "panel"], "antonyms": [], "example": "An advisory committee has been established to provide expert guidance on the company's expansion plans."},
        {"word": "Communal", "phonetic": "/kəˈmjuːnl/", "pos": "adj.", "meaning": "公用的, 集體的", "level": "blue", "phrases": ["communal area", "communal living"], "synonyms": ["public", "shared"], "antonyms": ["private", "individual"], "example": "The new office building includes several communal areas where employees from different teams can interact and collaborate."},
        {"word": "Communicative", "phonetic": "/kəˈmjuːnɪkeɪtɪv/", "pos": "adj.", "meaning": "愛說話的, 暢談的, 通訊的", "level": "blue", "phrases": ["communicative skills", "highly communicative"], "synonyms": ["expressive", "open"], "antonyms": ["reserved", "uncommunicative"], "example": "Effective leaders are usually highly communicative and able to express their ideas clearly to their team."},
        {"word": "Communique", "phonetic": "/kəˈmjuːnɪkeɪ/", "pos": "n.", "meaning": "公報, 官方聲明", "level": "blue", "phrases": ["joint communique", "official communique"], "synonyms": ["bulletin", "statement"], "antonyms": [], "example": "A joint communique was issued following the high-level meeting between the two heads of government."},
        {"word": "Communism", "phonetic": "/ˈkɑːmjənɪzəm/", "pos": "n.", "meaning": "共產主義", "level": "blue", "phrases": ["rise of communism"], "synonyms": [], "antonyms": ["capitalism"], "example": "Historians have studied the impact of communism on the economic development of Eastern European countries."},
        {"word": "Community", "phonetic": "/kəˈmjuːnəti/", "pos": "n.", "meaning": "社區, 社群, 共同體", "level": "blue", "phrases": ["local community", "business community"], "synonyms": ["society", "group"], "antonyms": [], "example": "The company is committed to supporting the local community through various charity and volunteer programs."},
        {"word": "Companion", "phonetic": "/kəmˈpæniən/", "pos": "n.", "meaning": "同伴, 夥伴", "level": "blue", "phrases": ["traveling companion", "constant companion"], "synonyms": ["associate", "partner"], "antonyms": [], "example": "His years of experience in the industry made him a valuable companion during the complex negotiations."},
        {"word": "Comparable", "phonetic": "/ˈkɑːmpərəbl/", "pos": "adj.", "meaning": "可比較的, 相當的", "level": "blue", "phrases": ["comparable quality", "at a comparable price"], "synonyms": ["equivalent", "similar"], "antonyms": ["incomparable", "different"], "example": "The quality of our new products is comparable to that of our main competitors, but at a lower price."},
        {"word": "Comparative", "phonetic": "/kəmˈpærətɪv/", "pos": "adj.", "meaning": "比較的, 相對的", "level": "blue", "phrases": ["comparative study", "comparative advantage"], "synonyms": ["relative"], "antonyms": ["absolute"], "example": "The company is conducting a comparative study of the different tax systems in Southeast Asian countries."},
        {"word": "Comparison", "phonetic": "/kəmˈpærɪsn/", "pos": "n.", "meaning": "比較, 對照", "level": "blue", "phrases": ["in comparison with", "make a comparison"], "synonyms": ["contrast", "analogy"], "antonyms": [], "example": "In comparison with the previous fiscal year, our annual revenue has increased by nearly 20%."},
        {"word": "Compassion", "phonetic": "/kəmˈpæʃn/", "pos": "n.", "meaning": "同情, 憐憫", "level": "blue", "phrases": ["show compassion", "feel compassion"], "synonyms": ["pity", "sympathy"], "antonyms": ["indifference", "cruelty"], "example": "The CEO's compassion for the employees affected by the layoffs was appreciated by the entire workforce."},
        {"word": "Compassionate", "phonetic": "/kəmˈpæʃənət/", "pos": "adj.", "meaning": "有同情心的, 慈悲的", "level": "blue", "phrases": ["compassionate leave", "compassionate person"], "synonyms": ["sympathetic", "kind"], "antonyms": ["heartless", "cold"], "example": "The company provides compassionate leave to employees who need time off to deal with a family emergency."},
        {"word": "Compatibility", "phonetic": "/kəmˌpætəˈbɪləti/", "pos": "n.", "meaning": "相容性, 兼容性", "level": "blue", "phrases": ["software compatibility", "test compatibility"], "synonyms": [], "antonyms": ["incompatibility"], "example": "Please ensure that the new hardware is compatible with our existing internal software systems."},
        {"word": "Compatible", "phonetic": "/kəmˈpætəbl/", "pos": "adj.", "meaning": "相容的, 兼容的, 和睦相處的", "level": "blue", "phrases": ["fully compatible", "backward compatible"], "synonyms": ["consistent", "harmonious"], "antonyms": ["incompatible"], "example": "The new smartphone application is compatible with both iOS and Android operating systems."},
        {"word": "Compel", "phonetic": "/kəmˈpel/", "pos": "v.", "meaning": "強迫, 迫使", "level": "blue", "phrases": ["feel compelled to", "compel someone to do"], "synonyms": ["force", "obligate"], "antonyms": [], "example": "The government felt compelled to introduce new regulations to protect consumer rights in the digital market."},
        {"word": "Compelling", "phonetic": "/kəmˈpelɪŋ/", "pos": "adj.", "meaning": "引人入勝的, 令人信服的, 強制的", "level": "blue", "phrases": ["compelling argument", "compelling evidence"], "synonyms": ["persuasive", "convincing"], "antonyms": ["unconvincing"], "example": "The marketing team presented a compelling argument for expanding our operations into the European market."},
        {"word": "Compensate", "phonetic": "/ˈkɑːmpenseɪt/", "pos": "v.", "meaning": "補償, 賠償, 酬報", "level": "blue", "phrases": ["compensate for loss", "adequately compensate"], "synonyms": ["reimburse", "repay"], "antonyms": [], "example": "The airline offered meal vouchers to compensate for the inconvenience caused by the long flight delay."},
        {"word": "Compensation", "phonetic": "/ˌkɑːmpenˈseɪʃn/", "pos": "n.", "meaning": "補償, 賠償, 薪酬", "level": "blue", "phrases": ["executive compensation", "financial compensation"], "synonyms": ["remuneration", "restitution"], "antonyms": [], "example": "The company offers a highly competitive compensation package, including health insurance and stock options."},
        {"word": "Compete", "phonetic": "/kəmˈpiːt/", "pos": "v.", "meaning": "競爭, 對抗", "level": "blue", "phrases": ["compete for a prize", "effectively compete"], "synonyms": ["contend", "rival"], "antonyms": [], "example": "Small businesses are struggling to compete with larger corporations that have much bigger marketing budgets."},
        {"word": "Competence", "phonetic": "/ˈkɑːmpɪtəns/", "pos": "n.", "meaning": "能力, 勝任, 權限", "level": "blue", "phrases": ["professional competence", "core competence"], "synonyms": ["ability", "capability"], "antonyms": ["incompetence"], "example": "Candidates are expected to demonstrate a high level of professional competence in their chosen field."},
        {"word": "Competency", "phonetic": "/ˈkɑːmpɪtənsi/", "pos": "n.", "meaning": "能力, 技能", "level": "blue", "phrases": ["core competencies", "competency framework"], "synonyms": ["skill", "expertise"], "antonyms": [], "example": "Developing new digital competencies is essential for employees to stay relevant in the evolving job market."},
        {"word": "Competent", "phonetic": "/ˈkɑːmpɪtənt/", "pos": "adj.", "meaning": "有能力的, 能勝任的", "level": "blue", "phrases": ["highly competent", "competent authority"], "synonyms": ["capable", "proficient"], "antonyms": ["incompetent"], "example": "We are looking for a competent individual to manage our newly established customer support department."},
        {"word": "Competition", "phonetic": "/ˌkɑːmpəˈtɪʃn/", "pos": "n.", "meaning": "競爭, 比賽", "level": "blue", "phrases": ["fierce competition", "stiff competition"], "synonyms": ["rivalry", "contest"], "antonyms": [], "example": "There is fierce competition among tech firms to develop the next breakthrough in artificial intelligence."},
        {"word": "Competitive", "phonetic": "/kəmˈpetətɪv/", "pos": "adj.", "meaning": "競爭的, 有競爭力的", "level": "blue", "phrases": ["competitive advantage", "highly competitive"], "synonyms": ["ambitious"], "antonyms": [], "example": "To maintain a competitive advantage, we must continue to invest in research and development and innovation."},
        {"word": "Competitor", "phonetic": "/kəmˈpetɪtər/", "pos": "n.", "meaning": "競爭者, 對手", "level": "blue", "phrases": ["major competitor", "closest competitor"], "synonyms": ["rival", "opponent"], "antonyms": ["ally", "partner"], "example": "Our closest competitor has recently launched a new advertising campaign targeting our primary customer base."},
        {"word": "Compilation", "phonetic": "/ˌkɑːmpɪˈleɪʃn/", "pos": "n.", "meaning": "編輯, 編纂, 編輯物", "level": "blue", "phrases": ["data compilation", "best-of compilation"], "synonyms": ["collection", "anthology"], "antonyms": [], "example": "The annual report includes a comprehensive compilation of all major projects completed by the firm this year."},
        {"word": "Compile", "phonetic": "/kəmˈpaɪl/", "pos": "v.", "meaning": "編輯, 編纂, 收集(資料)", "level": "blue", "phrases": ["compile data", "compile a list"], "synonyms": ["gather", "collect"], "antonyms": [], "example": "The marketing department is trying to compile a list of potential clients for the upcoming international campaign."},
        {"word": "Complacency", "phonetic": "/kəmˈpleɪsnsi/", "pos": "n.", "meaning": "自滿, 得意", "level": "blue", "phrases": ["avoid complacency", "dangerous complacency"], "synonyms": ["satisfaction", "smugness"], "antonyms": ["dissatisfaction"], "example": "Management warned employees against complacency following the company's recent record-breaking profits."},
        {"word": "Complacent", "phonetic": "/kəmˈpleɪsnt/", "pos": "adj.", "meaning": "自滿的, 得意的", "level": "blue", "phrases": ["become complacent", "complacent attitude"], "synonyms": ["smug", "satisfied"], "antonyms": ["humble"], "example": "We cannot afford to become complacent despite our strong position in the current market."},
        {"word": "Complement", "phonetic": "/ˈkɑːmplɪment/", "pos": "v./n.", "meaning": "補充, 補足, 補足物", "level": "blue", "phrases": ["complement each other", "full complement"], "synonyms": ["supplement", "balance"], "antonyms": [], "example": "The two companies' strengths complement each other perfectly, making them ideal partners for the joint venture."},
        {"word": "Complementary", "phonetic": "/ˌkɑːmplɪˈmentri/", "pos": "adj.", "meaning": "補充的, 互補的", "level": "blue", "phrases": ["complementary roles", "complementary colors"], "synonyms": ["interdependent"], "antonyms": [], "example": "The marketing and sales departments play complementary roles in ensuring the company's overall success."},
        {"word": "Completion", "phonetic": "/kəmˈpliːʃn/", "pos": "n.", "meaning": "完成, 結束", "level": "blue", "phrases": ["near completion", "successful completion"], "synonyms": ["conclusion", "finish"], "antonyms": ["beginning", "start"], "example": "Significant investment is still needed to ensure the successful completion of the infrastructure project on time."},
        {"word": "Complex", "phonetic": "/kəmˈpleks/", "pos": "adj./n.", "meaning": "複雜的, 建築群, 複合體", "level": "blue", "phrases": ["highly complex", "industrial complex"], "synonyms": ["complicated", "intricate"], "antonyms": ["simple"], "example": "The legal team is working to simplify the wording of the highly complex service agreement."},
        {"word": "Complexity", "phonetic": "/kəmˈpleksəti/", "pos": "n.", "meaning": "複雜性, 複雜度", "level": "blue", "phrases": ["added complexity", "level of complexity"], "synonyms": ["intricacy"], "antonyms": ["simplicity"], "example": "The increasing complexity of the global market requires businesses to be more agile and adaptable."},
        {"word": "Complicate", "phonetic": "/ˈkɑːmplɪkeɪt/", "pos": "v.", "meaning": "使複雜化", "level": "blue", "phrases": ["unnecessarily complicate", "complicate the issue"], "synonyms": ["confuse", "entangle"], "antonyms": ["simplify"], "example": "The sudden change in government policy will only serve to complicate the ongoing negotiations with our partners."},
        {"word": "Complicated", "phonetic": "/ˈkɑːmplɪkeɪtɪd/", "pos": "adj.", "meaning": "複雜的, 難懂的", "level": "blue", "phrases": ["highly complicated", "overly complicated"], "synonyms": ["complex", "intricate"], "antonyms": ["simple", "easy"], "example": "The new tax regulations are so complicated that many small businesses are struggling to comply with them."},
        {"word": "Complication", "phonetic": "/ˌkɑːmplɪˈkeɪʃn/", "pos": "n.", "meaning": "併發症, 複雜化, 難題", "level": "blue", "phrases": ["added complication", "unforeseen complications"], "synonyms": ["difficulty", "problem"], "antonyms": [], "example": "The project was delayed by several weeks due to unforeseen complications during the construction process."},
        {"word": "Compliment", "phonetic": "/ˈkɑːmplɪmənt/", "pos": "n./v.", "meaning": "稱讚, 讚美", "level": "blue", "phrases": ["pay a compliment", "take it as a compliment"], "synonyms": ["praise", "flatter"], "antonyms": ["insult", "criticize"], "example": "The manager paid the team a generous compliment for their hard work and dedication during the audit."},
        {"word": "Complimentary", "phonetic": "/ˌkɑːmplɪˈmentri/", "pos": "adj.", "meaning": "稱讚的, 贈送的, 免費的", "level": "blue", "phrases": ["complimentary tickets", "highly complimentary"], "synonyms": ["free", "gratuitous"], "antonyms": ["critical"], "example": "The hotel provided complimentary breakfast and airport shuttle service for all international conference delegates."},
        {"word": "Comply", "phonetic": "/kəmˈplaɪ/", "pos": "v.", "meaning": "遵守, 照做", "level": "blue", "phrases": ["comply with regulations", "strictly comply"], "synonyms": ["observe", "follow", "adhere"], "antonyms": ["violate", "defy"], "example": "All factory operations must strictly comply with the latest health and safety regulations introduced by the government."},
        {"word": "Component", "phonetic": "/kəmˈpoʊnənt/", "pos": "n./adj.", "meaning": "零件, 組成部分, 構成的", "level": "blue", "phrases": ["key component", "electronic components"], "synonyms": ["element", "part", "constituent"], "antonyms": ["whole"], "example": "High-quality electronic components are essential for the production of our reliable medical devices."},
        {"word": "Compose", "phonetic": "/kəmˈpoʊz/", "pos": "v.", "meaning": "組成, 寫作, 使鎮定", "level": "blue", "phrases": ["be composed of", "compose an email"], "synonyms": ["constitute", "create"], "antonyms": [], "example": "The board of directors is composed of ten members with diverse backgrounds in finance and management."},
        {"word": "Composer", "phonetic": "/kəmˈpoʊzər/", "pos": "n.", "meaning": "作曲家", "level": "blue", "phrases": ["famous composer", "classical composer"], "synonyms": [], "antonyms": [], "example": "The company hired a famous composer to create an original score for its new advertising campaign."},
        {"word": "Composite", "phonetic": "/kəmˈpɑːzət/", "pos": "adj./n.", "meaning": "合成的, 複合的, 合成物", "level": "blue", "phrases": ["composite material", "composite index"], "synonyms": ["combined", "mixed"], "antonyms": ["simple", "pure"], "example": "The new aircraft is made from highly durable and lightweight composite materials to improve fuel efficiency."},
        {"word": "Composition", "phonetic": "/ˌkɑːmpəˈzɪʃn/", "pos": "n.", "meaning": "成分, 構成, 寫作, 作品", "level": "blue", "phrases": ["chemical composition", "musical composition"], "synonyms": ["makeup", "structure"], "antonyms": [], "example": "Auditors are carefully reviewing the composition of the company's annual research and development budget."},
        {"word": "Compound", "phonetic": "/ˈkɑːmpaʊnd/", "pos": "n./v./adj.", "meaning": "化合物, 複合物, 使加重, 複合的", "level": "blue", "phrases": ["chemical compound", "compound interest"], "synonyms": ["mixture", "complex"], "antonyms": [], "example": "The sudden increase in fuel prices will only compound the difficulties already faced by the transportation industry."},
        {"word": "Comprehend", "phonetic": "/ˌkɑːmprɪˈhend/", "pos": "v.", "meaning": "理解, 領會", "level": "blue", "phrases": ["fully comprehend", "fail to comprehend"], "synonyms": ["understand", "grasp"], "antonyms": ["misunderstand"], "example": "It took several meetings for the board to fully comprehend the implications of the new international trade policy."},
        {"word": "Comprehension", "phonetic": "/ˌkɑːmprɪˈhenʃn/", "pos": "n.", "meaning": "理解, 理解力", "level": "blue", "phrases": ["reading comprehension", "beyond one's comprehension"], "synonyms": ["understanding"], "antonyms": [], "example": "The training program is designed to improve employees' comprehension of the complex new security protocols."},
        {"word": "Comprehensive", "phonetic": "/ˌkɑːmprɪˈhensɪv/", "pos": "adj.", "meaning": "全面的, 廣泛的, 綜合的", "level": "blue", "phrases": ["comprehensive insurance", "comprehensive report"], "synonyms": ["thorough", "extensive"], "antonyms": ["partial", "limited"], "example": "The consultant provided a comprehensive review of the company's internal marketing and distribution processes."},
        {"word": "Compress", "phonetic": "/kəmˈpres/", "pos": "v.", "meaning": "壓縮, 壓緊", "level": "blue", "phrases": ["compress a file", "compress the data"], "synonyms": ["squeeze", "condense"], "antonyms": ["expand", "stretch"], "example": "Large data files are often compressed to make them easier to send via email and save storage space."},
        {"word": "Compression", "phonetic": "/kəmˈpreʃn/", "pos": "n.", "meaning": "壓縮", "level": "blue", "phrases": ["data compression", "engine compression"], "synonyms": [], "antonyms": ["expansion"], "example": "Advanced data compression techniques are used to improve the performance of our online streaming service."},
        {"word": "Comprise", "phonetic": "/kəmˈpraɪz/", "pos": "v.", "meaning": "包含, 由...組成", "level": "blue", "phrases": ["comprise of", "be comprised of"], "synonyms": ["include", "contain", "consist of"], "antonyms": [], "example": "The proposed expansion will comprise the establishment of ten new regional distribution centers across Asia."},
        {"word": "Compromise", "phonetic": "/ˈkɑːmprəmaɪz/", "pos": "v./n.", "meaning": "妥協, 讓步, 危害", "level": "blue", "phrases": ["reach a compromise", "compromise safety"], "synonyms": ["settlement", "concession"], "antonyms": ["disagreement", "clash"], "example": "After hours of intense negotiation, the two parties finally managed to reach a fair compromise on the price."},
        {"word": "Compulsion", "phonetic": "/kəmˈpʌlʃn/", "pos": "n.", "meaning": "強迫, 衝動", "level": "blue", "phrases": ["feel a compulsion", "under compulsion"], "synonyms": ["obligation", "urge"], "antonyms": [], "example": "Many employees felt a compulsion to work longer hours to meet the ambitious new project deadlines."},
        {"word": "Computation", "phonetic": "/ˌkɑːmpjuˈteɪʃn/", "pos": "n.", "meaning": "計算, 估算", "level": "blue", "phrases": ["accurate computation", "performing computation"], "synonyms": ["calculation", "reckoning"], "antonyms": [], "example": "The accuracy of the financial projections depends on the correct computation of the latest market trends and data."},
        {"word": "Compute", "phonetic": "/kəmˈpjuːt/", "pos": "v.", "meaning": "計算, 估算", "level": "blue", "phrases": ["compute the total", "compute the average"], "synonyms": ["calculate", "reckon"], "antonyms": [], "example": "The software is designed to automatically compute the taxes and shipping charges for every online order."},
        {"word": "Computerize", "phonetic": "/kəmˈpjuːtəraɪz/", "pos": "v.", "meaning": "使電腦化", "level": "blue", "phrases": ["fully computerize", "computerize the system"], "synonyms": [], "antonyms": ["manual"], "example": "The organization plans to fully computerize its library and archive system to improve access for researchers."},
        {"word": "Conceal", "phonetic": "/kənˈsiːl/", "pos": "v.", "meaning": "隱瞞, 隱藏", "level": "blue", "phrases": ["conceal information", "conceal the truth"], "synonyms": ["hide", "disguise"], "antonyms": ["reveal", "disclose"], "example": "The firm was accused of trying to conceal its true financial position from the national competition authority."},
        {"word": "Concede", "phonetic": "/kənˈsiːd/", "pos": "v.", "meaning": "承認, 讓步, 屈服", "level": "blue", "phrases": ["concede defeat", "concede a point"], "synonyms": ["admit", "yield"], "antonyms": ["deny", "refuse"], "example": "The management was forced to concede several points to the union during the intense wage negotiations."},
        {"word": "Conceit", "phonetic": "/kənˈsiːt/", "pos": "n.", "meaning": "自負, 自大", "level": "blue", "phrases": ["full of conceit"], "synonyms": ["vanity", "pride"], "antonyms": ["humility", "modesty"], "example": "His overwhelming conceit made it difficult for him to work effectively with other members of the team."},
        {"word": "Conceivable", "phonetic": "/kənˈsiːvəbl/", "pos": "adj.", "meaning": "可想像的, 可信的", "level": "blue", "phrases": ["every conceivable way", "hardly conceivable"], "synonyms": ["possible", "imaginable"], "antonyms": ["inconceivable", "impossible"], "example": "The committee is exploring every conceivable way to reduce the project's overall annual operating costs."},
        {"word": "Conceive", "phonetic": "/kənˈsiːv/", "pos": "v.", "meaning": "構思, 懷孕, 持有(想法)", "level": "blue", "phrases": ["conceive a plan", "conceive an idea"], "synonyms": ["devise", "formulate"], "antonyms": [], "example": "The marketing team is working to conceive a new advertising campaign that will appeal to a younger audience."},
        {"word": "Concentrate", "phonetic": "/ˈkɑːnsntreɪt/", "pos": "v./n.", "meaning": "專心, 集中, 濃縮物", "level": "blue", "phrases": ["concentrate on", "highly concentrated"], "synonyms": ["focus", "center"], "antonyms": ["disperse", "distract"], "example": "We need to concentrate our efforts on improving our online presence to attract more customers worldwide."},
        {"word": "Concentration", "phonetic": "/ˌkɑːnsnˈtreɪʃn/", "pos": "n.", "meaning": "集中, 專注力, 濃度", "level": "blue", "phrases": ["lack of concentration", "market concentration"], "synonyms": ["focus", "density"], "antonyms": ["dispersion"], "example": "Greater market concentration in the hands of a few large firms can lead to less competition and higher prices."},
        {"word": "Concept", "phonetic": "/ˈkɑːnsept/", "pos": "n.", "meaning": "概念, 觀念", "level": "blue", "phrases": ["basic concept", "new concept"], "synonyms": ["idea", "notion"], "antonyms": [], "example": "The engineer introduced a revolutionary new concept for a modular and energy-efficient office building."},
        {"word": "Conception", "phonetic": "/kənˈsepʃn/", "pos": "n.", "meaning": "概念, 構想, 懷孕", "level": "blue", "phrases": ["clear conception", "original conception"], "synonyms": ["understanding", "view"], "antonyms": [], "example": "Our original conception of the project was quite different from the final version that was implemented."},
        {"word": "Conceptual", "phonetic": "/kənˈseptʃuəl/", "pos": "adj.", "meaning": "觀念的, 概念的", "level": "blue", "phrases": ["conceptual framework", "conceptual design"], "synonyms": ["theoretical"], "antonyms": ["concrete", "practical"], "example": "The team is currently working on the conceptual design phase of the new product development process."},
        {"word": "Concerned", "phonetic": "/kənˈsɜːrnd/", "pos": "adj.", "meaning": "擔心的, 有關的", "level": "blue", "phrases": ["concerned about", "as far as I am concerned"], "synonyms": ["worried", "involved"], "antonyms": ["indifferent", "unconcerned"], "example": "Management is deeply concerned about the steady decline in quarterly sales figures over the last year."},
        {"word": "Concerted", "phonetic": "/kənˈsɜːrtɪd/", "pos": "adj.", "meaning": "共同籌劃的, 協定的, 齊心協力的", "level": "blue", "phrases": ["concerted effort", "concerted action"], "synonyms": ["joint", "combined"], "antonyms": ["unilateral", "individual"], "example": "A concerted effort from all departments is needed to ensure the successful completion of the infrastructure project."},
        {"word": "Concession", "phonetic": "/kənˈseʃn/", "pos": "n.", "meaning": "讓步, 特許權", "level": "blue", "phrases": ["make concessions", "mining concession"], "synonyms": ["compromise", "allowance", "grant"], "antonyms": [], "example": "The government granted the foreign firm a 20-year concession to manage the city's new container port."},
        {"word": "Concise", "phonetic": "/kənˈsaɪs/", "pos": "adj.", "meaning": "簡潔的, 扼要的", "level": "blue", "phrases": ["concise summary", "brief and concise"], "synonyms": ["brief", "succinct"], "antonyms": ["lengthy", "wordy"], "example": "Please provide a concise summary of the project's key findings and recommendations for the board of directors."},
        {"word": "Conclude", "phonetic": "/kənˈkluːd/", "pos": "v.", "meaning": "結束, 斷定, 締結", "level": "blue", "phrases": ["conclude a deal", "conclude a speech"], "synonyms": ["end", "finish", "deduce"], "antonyms": ["commence", "start"], "example": "After several weeks of negotiation, the two firms have finally managed to conclude a major trade agreement."},
        {"word": "Conclusion", "phonetic": "/kənˈkluːʒn/", "pos": "n.", "meaning": "結論, 結束", "level": "blue", "phrases": ["reach a conclusion", "logical conclusion"], "synonyms": ["deduction", "end"], "antonyms": ["beginning", "start"], "example": "The final report's conclusion suggests that further market research is needed before we decide on expansion."},
        {"word": "Concrete", "phonetic": "/ˈkɑːnkriːt/", "pos": "adj./n.", "meaning": "具體的, 混凝土", "level": "blue", "phrases": ["concrete evidence", "reinforced concrete"], "synonyms": ["solid", "substantial", "real"], "antonyms": ["abstract", "vague"], "example": "We need more concrete evidence of market demand before we invest millions of dollars in the new project."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
