import json
import os

def update_vocab():
    # 第十批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Redundant", "phonetic": "/rɪˈdʌndənt/", "pos": "adj.", "meaning": "多餘的, 被解僱的", "level": "blue", "phrases": ["redundant data", "be made redundant"], "synonyms": ["superfluous", "unemployed"], "antonyms": ["essential", "necessary"], "example": "The new automation system has made several manual clerical roles redundant."},
        {"word": "Referral", "phonetic": "/rɪˈfɜːrəl/", "pos": "n.", "meaning": "推薦, 轉介", "level": "blue", "phrases": ["employee referral", "doctor's referral"], "synonyms": ["recommendation"], "antonyms": [], "example": "The company offers a bonus to any employee whose referral leads to a successful hire."},
        {"word": "Refundable", "phonetic": "/rɪˈfʌndəbl/", "pos": "adj.", "meaning": "可退還的", "level": "blue", "phrases": ["fully refundable", "non-refundable deposit"], "synonyms": [], "antonyms": ["non-refundable"], "example": "The airline ticket is fully refundable if cancelled at least 48 hours before departure."},
        {"word": "Refurbish", "phonetic": "/ˌriːˈfɜːrbɪʃ/", "pos": "v.", "meaning": "整修, 翻新", "level": "blue", "phrases": ["refurbished electronics", "completely refurbished"], "synonyms": ["renovate", "restore"], "antonyms": [], "example": "The hotel is currently closed while the guest rooms are being refurbished."},
        {"word": "Regulate", "phonetic": "/ˈreɡjuleɪt/", "pos": "v.", "meaning": "管制, 調節", "level": "blue", "phrases": ["regulate the market", "tightly regulated"], "synonyms": ["control", "govern"], "antonyms": ["deregulate"], "example": "New laws have been introduced to regulate the disposal of hazardous industrial waste."},
        {"word": "Reimburse", "phonetic": "/ˌriːɪmˈbɜːrs/", "pos": "v.", "meaning": "報銷, 償還", "level": "blue", "phrases": ["reimburse expenses", "fully reimbursed"], "synonyms": ["repay", "compensate"], "antonyms": [], "example": "The company will reimburse you for any travel expenses incurred during the business trip."},
        {"word": "Relocation", "phonetic": "/ˌriːloʊˈkeɪʃn/", "pos": "n.", "meaning": "搬遷, 重新安置", "level": "blue", "phrases": ["relocation package", "business relocation"], "synonyms": ["move", "transfer"], "antonyms": [], "example": "The firm is offering a generous relocation package to employees moving to the new branch."},
        {"word": "Remittance", "phonetic": "/rɪˈmɪtəns/", "pos": "n.", "meaning": "匯款, 匯寄之款", "level": "blue", "phrases": ["foreign remittance", "prompt remittance"], "synonyms": ["payment", "transfer"], "antonyms": [], "example": "Please include the invoice number with your remittance to ensure proper processing."},
        {"word": "Remuneration", "phonetic": "/rɪˌmjuːnəˈreɪʃn/", "pos": "n.", "meaning": "酬報, 薪資", "level": "blue", "phrases": ["remuneration package", "fair remuneration"], "synonyms": ["salary", "compensation"], "antonyms": [], "example": "The committee is reviewing the executive remuneration policy to ensure it remains competitive."},
        {"word": "Renovate", "phonetic": "/ˈrenəveɪt/", "pos": "v.", "meaning": "裝修, 修復", "level": "blue", "phrases": ["renovate the office", "recently renovated"], "synonyms": ["refurbish", "remodel"], "antonyms": [], "example": "The city council plans to renovate the historic library building later this year."},
        {"word": "Reparation", "phonetic": "/ˌrepəˈreɪʃn/", "pos": "n.", "meaning": "賠償, 修補", "level": "blue", "phrases": ["make reparations", "financial reparation"], "synonyms": ["compensation", "restitution"], "antonyms": [], "example": "The company agreed to pay financial reparations to the victims of the chemical spill."},
        {"word": "Repeal", "phonetic": "/rɪˈpiːl/", "pos": "v./n.", "meaning": "廢止, 撤銷", "level": "blue", "phrases": ["repeal a law", "demand a repeal"], "synonyms": ["revoke", "cancel"], "antonyms": ["enact", "establish"], "example": "The government is under pressure to repeal the controversial new tax law."},
        {"word": "Replenish", "phonetic": "/rɪˈplenɪʃ/", "pos": "v.", "meaning": "補充, 再裝滿", "level": "blue", "phrases": ["replenish stock", "replenish supplies"], "synonyms": ["refill", "restore"], "antonyms": ["deplete", "empty"], "example": "The warehouse manager needs to replenish the stock of printer ink before it runs out."},
        {"word": "Representation", "phonetic": "/ˌreprɪzenˈteɪʃn/", "pos": "n.", "meaning": "代表, 陳述", "level": "blue", "phrases": ["legal representation", "fair representation"], "synonyms": ["depiction", "agency"], "antonyms": [], "example": "The workers are demanding better representation on the company's board of directors."},
        {"word": "Reputation", "phonetic": "/ˌrepjuˈteɪʃn/", "pos": "n.", "meaning": "聲譽, 名聲", "level": "blue", "phrases": ["brand reputation", "solid reputation"], "synonyms": ["prestige", "stature"], "antonyms": ["disrepute"], "example": "The firm has built a solid reputation for providing high-quality consulting services."},
        {"word": "Requirement", "phonetic": "/rɪˈkwaɪərmənt/", "pos": "n.", "meaning": "要求, 必要條件", "level": "blue", "phrases": ["minimum requirement", "meet the requirements"], "synonyms": ["necessity", "stipulation"], "antonyms": [], "example": "A master's degree in finance is a minimum requirement for this senior analyst position."},
        {"word": "Rescind", "phonetic": "/rɪˈsɪnd/", "pos": "v.", "meaning": "撤銷, 廢除", "level": "blue", "phrases": ["rescind an offer", "rescind a contract"], "synonyms": ["revoke", "annul"], "antonyms": ["enforce", "ratify"], "example": "The company decided to rescind the job offer after discovering discrepancies in the candidate's resume."},
        {"word": "Resignation", "phonetic": "/ˌrezɪɡˈneɪʃn/", "pos": "n.", "meaning": "辭職, 辭職信", "level": "blue", "phrases": ["hand in one's resignation", "tender a resignation"], "synonyms": [], "antonyms": [], "example": "The marketing director's sudden resignation surprised everyone in the department."},
        {"word": "Resolution", "phonetic": "/ˌrezəˈluːʃn/", "pos": "n.", "meaning": "決議, 解決, 解析度", "level": "blue", "phrases": ["pass a resolution", "conflict resolution"], "synonyms": ["decision", "settlement"], "antonyms": [], "example": "The board passed a resolution to increase the annual research and development budget."},
        {"word": "Respective", "phonetic": "/rɪˈspektɪv/", "pos": "adj.", "meaning": "各自的", "level": "blue", "phrases": ["respective departments", "respective roles"], "synonyms": ["individual", "particular"], "antonyms": [], "example": "After the meeting, the managers returned to their respective departments to implement the new policy."},
        {"word": "Restructure", "phonetic": "/ˌriːˈstrʌktʃər/", "pos": "v.", "meaning": "重組, 改組", "level": "blue", "phrases": ["corporate restructuring", "restructure the debt"], "synonyms": ["reorganize"], "antonyms": [], "example": "The company needs to restructure its operations to become more agile in the digital market."},
        {"word": "Retail", "phonetic": "/ˈriːteɪl/", "pos": "n./v./adj.", "meaning": "零售", "level": "blue", "phrases": ["retail price", "retail outlet"], "synonyms": [], "antonyms": ["wholesale"], "example": "The manufacturer plans to open several new retail outlets in major cities across Asia."},
        {"word": "Retention", "phonetic": "/rɪˈtenʃn/", "pos": "n.", "meaning": "保留, 保持, 留才", "level": "blue", "phrases": ["employee retention", "customer retention"], "synonyms": ["preservation", "maintenance"], "antonyms": ["loss"], "example": "Improving employee retention is a top priority for the human resources department this year."},
        {"word": "Retract", "phonetic": "/rɪˈtrækt/", "pos": "v.", "meaning": "撤回, 縮回", "level": "blue", "phrases": ["retract a statement", "retract an offer"], "synonyms": ["withdraw", "recant"], "antonyms": [], "example": "The spokesperson was forced to retract her earlier comments regarding the company's financial health."},
        {"word": "Revenue", "phonetic": "/ˈrevənuː/", "pos": "n.", "meaning": "收入, 歲入", "level": "blue", "phrases": ["annual revenue", "generate revenue"], "synonyms": ["income", "earnings"], "antonyms": ["expenditure", "loss"], "example": "The company reported a 15% increase in annual revenue compared to the previous fiscal year."},
        {"word": "Revision", "phonetic": "/rɪˈvɪʒn/", "pos": "n.", "meaning": "修訂, 校訂", "level": "blue", "phrases": ["undergo revision", "make revisions"], "synonyms": ["amendment", "alteration"], "antonyms": [], "example": "The final draft of the proposal is currently undergoing revision based on the client's feedback."},
        {"word": "Revoke", "phonetic": "/rɪˈvoʊk/", "pos": "v.", "meaning": "撤銷, 廢除", "level": "blue", "phrases": ["revoke a license", "revoke an agreement"], "synonyms": ["cancel", "rescind"], "antonyms": ["grant", "validate"], "example": "The authorities decided to revoke the company's operating license due to repeated safety violations."},
        {"word": "Rigorous", "phonetic": "/ˈrɪɡərəs/", "pos": "adj.", "meaning": "嚴格的, 嚴密的", "level": "blue", "phrases": ["rigorous testing", "rigorous standards"], "synonyms": ["strict", "stringent"], "antonyms": ["lenient", "lax"], "example": "All new products must undergo rigorous safety testing before they are released to the public."},
        {"word": "Rival", "phonetic": "/ˈraɪvl/", "pos": "n./adj./v.", "meaning": "對手, 競爭的, 與...競爭", "level": "blue", "phrases": ["arch rival", "rival company"], "synonyms": ["competitor", "opponent"], "antonyms": ["ally", "partner"], "example": "The two rival tech giants are constantly competing for a larger share of the smartphone market."},
        {"word": "Royalty", "phonetic": "/ˈrɔɪəlti/", "pos": "n.", "meaning": "權利金, 版稅", "level": "blue", "phrases": ["pay royalties", "royalty agreement"], "synonyms": [], "antonyms": [], "example": "The author receives a 10% royalty on every copy of the book that is sold worldwide."},
        {"word": "Salvage", "phonetic": "/ˈsælvɪdʒ/", "pos": "v./n.", "meaning": "搶救, 挽救, 廢料利用", "level": "blue", "phrases": ["salvage operation", "salvage value"], "synonyms": ["rescue", "save"], "antonyms": ["abandon", "discard"], "example": "Divers are working to salvage valuable cargo from the sunken merchant ship."},
        {"word": "Sanction", "phonetic": "/ˈsæŋkʃn/", "pos": "n./v.", "meaning": "制裁, 批准, 認可", "level": "blue", "phrases": ["economic sanctions", "official sanction"], "synonyms": ["penalty", "approval"], "antonyms": ["reward", "prohibition"], "example": "The international community imposed economic sanctions on the country following the trade violation."},
        {"word": "Saturate", "phonetic": "/ˈsætʃəreɪt/", "pos": "v.", "meaning": "使飽和, 浸透", "level": "blue", "phrases": ["saturated market", "fully saturate"], "synonyms": ["soak", "drench"], "antonyms": ["dry", "dehydrate"], "example": "Many experts believe that the domestic market for smartphones is already fully saturated."},
        {"word": "Schedule", "phonetic": "/ˈskedʒuːl/", "pos": "n./v.", "meaning": "時間表, 計畫, 安排", "level": "blue", "phrases": ["behind schedule", "ahead of schedule"], "synonyms": ["timetable", "plan"], "antonyms": [], "example": "The construction project is currently two weeks behind schedule due to the heavy rain."},
        {"word": "Scrutinize", "phonetic": "/ˈskruːtənaɪz/", "pos": "v.", "meaning": "仔細檢查", "level": "blue", "phrases": ["scrutinize the records", "carefully scrutinize"], "synonyms": ["examine", "inspect"], "antonyms": ["ignore", "glance"], "example": "The auditors will scrutinize every financial transaction from the past three fiscal years."},
        {"word": "Sector", "phonetic": "/ˈsektər/", "pos": "n.", "meaning": "部門, 領域, 扇形", "level": "blue", "phrases": ["public sector", "financial sector"], "synonyms": ["segment", "area"], "antonyms": [], "example": "The technology sector has seen significant growth and innovation over the past decade."},
        {"word": "Secure", "phonetic": "/sɪˈkjʊr/", "pos": "v./adj.", "meaning": "獲得, 使安全, 安全的", "level": "blue", "phrases": ["secure a contract", "secure location"], "synonyms": ["obtain", "safe"], "antonyms": ["lose", "insecure"], "example": "The sales team worked hard to secure a multi-million dollar contract with the government."},
        {"word": "Segment", "phonetic": "/ˈseɡmənt/", "pos": "n./v.", "meaning": "部分, 切片, 分割", "level": "blue", "phrases": ["market segment", "segment the audience"], "synonyms": ["section", "portion"], "antonyms": ["whole"], "example": "The marketing team is targeting a specific segment of the population aged between 18 and 25."},
        {"word": "Shareholder", "phonetic": "/ˈʃerhoʊldər/", "pos": "n.", "meaning": "股東", "level": "blue", "phrases": ["major shareholder", "shareholders' meeting"], "synonyms": ["stockholder"], "antonyms": [], "example": "The annual shareholders' meeting will be held at the city's convention center next month."},
        {"word": "Shipment", "phonetic": "/ˈʃɪpmənt/", "pos": "n.", "meaning": "貨運, 裝運的貨物", "level": "blue", "phrases": ["bulk shipment", "track a shipment"], "synonyms": ["consignment", "delivery"], "antonyms": [], "example": "We are expecting a large shipment of raw materials to arrive at the port tomorrow morning."},
        {"word": "Shortage", "phonetic": "/ˈʃɔːrtɪdʒ/", "pos": "n.", "meaning": "短缺, 不足", "level": "blue", "phrases": ["labor shortage", "housing shortage"], "synonyms": ["deficit", "scarcity"], "antonyms": ["surplus", "abundance"], "example": "The electronics industry is currently facing a global shortage of semiconductor chips."},
        {"word": "Shrinkage", "phonetic": "/ˈʃrɪŋkɪdʒ/", "pos": "n.", "meaning": "收縮, (庫存)損耗/失竊", "level": "blue", "phrases": ["inventory shrinkage", "fabric shrinkage"], "synonyms": ["reduction", "contraction"], "antonyms": ["expansion", "growth"], "example": "The retail chain is implementing new security measures to reduce inventory shrinkage caused by shoplifting."},
        {"word": "Signature", "phonetic": "/ˈsɪɡnətʃər/", "pos": "n.", "meaning": "簽名, 特徵", "level": "blue", "phrases": ["digital signature", "authorized signature"], "synonyms": ["autograph"], "antonyms": [], "example": "Please provide your authorized signature at the bottom of the last page of the contract."},
        {"word": "Significant", "phonetic": "/sɪɡˈnɪfɪkənt/", "pos": "adj.", "meaning": "顯著的, 重要的", "level": "blue", "phrases": ["significant improvement", "statistically significant"], "synonyms": ["noteworthy", "substantial"], "antonyms": ["insignificant", "minor"], "example": "There has been a significant increase in the number of people working from home recently."},
        {"word": "Simultaneous", "phonetic": "/ˌsaɪmlˈteɪniəs/", "pos": "adj.", "meaning": "同時的", "level": "blue", "phrases": ["simultaneous translation", "simultaneous broadcast"], "synonyms": ["concurrent", "coincident"], "antonyms": ["sequential"], "example": "The event will be provided with simultaneous translation into five different languages."},
        {"word": "Skilled", "phonetic": "/skɪld/", "pos": "adj.", "meaning": "熟練的, 有技能的", "level": "blue", "phrases": ["skilled labor", "highly skilled"], "synonyms": ["proficient", "expert"], "antonyms": ["unskilled", "inexperienced"], "example": "The company is struggling to find enough skilled workers to operate the new specialized machinery."},
        {"word": "Slogan", "phonetic": "/ˈsloʊɡən/", "pos": "n.", "meaning": "口號, 標語", "level": "blue", "phrases": ["advertising slogan", "catchy slogan"], "synonyms": ["motto", "catchphrase"], "antonyms": [], "example": "The marketing team spent weeks developing a catchy slogan for the new product launch."},
        {"word": "Software", "phonetic": "/ˈsɔːftwer/", "pos": "n.", "meaning": "軟體", "level": "blue", "phrases": ["software update", "antivirus software"], "synonyms": ["program", "application"], "antonyms": ["hardware"], "example": "All company laptops must be equipped with the latest security and antivirus software."},
        {"word": "Sole", "phonetic": "/soʊl/", "pos": "adj.", "meaning": "唯一的, 單獨的", "level": "blue", "phrases": ["sole proprietor", "sole survivor"], "synonyms": ["only", "exclusive"], "antonyms": ["multiple", "shared"], "example": "The pharmaceutical company was granted the sole right to manufacture and sell the new drug."},
        {"word": "Solicit", "phonetic": "/səˈlɪsɪt/", "pos": "v.", "meaning": "徵求, 招攬", "level": "blue", "phrases": ["solicit feedback", "solicit donations"], "synonyms": ["request", "seek"], "antonyms": [], "example": "The committee is planning to solicit feedback from all employees regarding the new office layout."},
        {"word": "Solution", "phonetic": "/səˈluːʃn/", "pos": "n.", "meaning": "解決方案, 溶液", "level": "blue", "phrases": ["workable solution", "software solution"], "synonyms": ["remedy", "answer"], "antonyms": ["problem"], "example": "The IT department is working hard to find a permanent solution to the recurring server issues."},
        {"word": "Sophisticated", "phonetic": "/səˈfɪstɪkeɪtɪd/", "pos": "adj.", "meaning": "精密的, 老練的, 複雜的", "level": "blue", "phrases": ["sophisticated technology", "sophisticated investor"], "synonyms": ["advanced", "refined"], "antonyms": ["simple", "primitive"], "example": "The hackers used a highly sophisticated method to bypass the company's internal security systems."},
        {"word": "Specialize", "phonetic": "/ˈspeʃəlaɪz/", "pos": "v.", "meaning": "專攻, 專門從事", "level": "blue", "phrases": ["specialize in law", "highly specialized"], "synonyms": [], "antonyms": [], "example": "The local law firm specializes in providing legal services to small and medium-sized enterprises."},
        {"word": "Specification", "phonetic": "/ˌspesɪfɪˈkeɪʃn/", "pos": "n.", "meaning": "規格, 詳述, 說明書", "level": "blue", "phrases": ["technical specifications", "meet the specifications"], "synonyms": ["requirement", "detail"], "antonyms": [], "example": "Please review the technical specifications carefully to ensure the equipment meets our requirements."},
        {"word": "Speculate", "phonetic": "/ˈspekjuleɪt/", "pos": "v.", "meaning": "推測, 投機", "level": "blue", "phrases": ["speculate on the market", "purely speculative"], "synonyms": ["guess", "surmise", "gamble"], "antonyms": [], "example": "Economists are speculating that the central bank will raise interest rates early next month."},
        {"word": "Sponsor", "phonetic": "/ˈspɑːnsər/", "pos": "n./v.", "meaning": "贊助者, 贊助", "level": "blue", "phrases": ["corporate sponsor", "sponsor an event"], "synonyms": ["patron", "support"], "antonyms": [], "example": "Several local businesses have agreed to sponsor the charity marathon being held this weekend."},
        {"word": "Spouse", "phonetic": "/spaʊs/", "pos": "n.", "meaning": "配偶", "level": "blue", "phrases": ["surviving spouse", "spouse benefit"], "synonyms": ["partner", "husband/wife"], "antonyms": [], "example": "Employees are invited to bring their spouses to the annual company holiday party."},
        {"word": "Stability", "phonetic": "/stəˈbɪləti/", "pos": "n.", "meaning": "穩定性", "level": "blue", "phrases": ["economic stability", "political stability"], "synonyms": ["steadiness", "firmness"], "antonyms": ["instability", "volatility"], "example": "The new government is focused on restoring economic stability and attracting foreign investment."},
        {"word": "Standardize", "phonetic": "/ˈstændərdaɪz/", "pos": "v.", "meaning": "使標準化", "level": "blue", "phrases": ["standardize the process", "standardized testing"], "synonyms": ["normalize"], "antonyms": [], "example": "The organization plans to standardize its reporting procedures across all its international branches."},
        {"word": "Statement", "phonetic": "/ˈsteɪtmənt/", "pos": "n.", "meaning": "聲明, 陳述, 報表", "level": "blue", "phrases": ["bank statement", "financial statement"], "synonyms": ["declaration", "report"], "antonyms": [], "example": "Please review your monthly bank statement carefully and report any discrepancies immediately."},
        {"word": "Statistic", "phonetic": "/stəˈtɪstɪk/", "pos": "n.", "meaning": "統計數據, 統計學", "level": "blue", "phrases": ["official statistics", "vital statistics"], "synonyms": ["data", "figure"], "antonyms": [], "example": "The latest government statistics show a steady decline in the national unemployment rate."},
        {"word": "Status", "phonetic": "/ˈsteɪtəs/", "pos": "n.", "meaning": "狀態, 地位, 身分", "level": "blue", "phrases": ["current status", "social status"], "synonyms": ["condition", "standing"], "antonyms": [], "example": "You can check the current status of your online order by logging into your account."},
        {"word": "Stipulate", "phonetic": "/ˈstɪpjuleɪt/", "pos": "v.", "meaning": "規定, 約定", "level": "blue", "phrases": ["stipulate in the contract", "clearly stipulate"], "synonyms": ["specify", "prescribe"], "antonyms": [], "example": "The agreement stipulates that all disputes must be resolved through binding arbitration."},
        {"word": "Strategy", "phonetic": "/ˈstrætədʒi/", "pos": "n.", "meaning": "策略, 戰略", "level": "blue", "phrases": ["marketing strategy", "exit strategy"], "synonyms": ["plan", "tactic"], "antonyms": [], "example": "The CEO presented a new five-year strategy aimed at expanding the company's global presence."},
        {"word": "Streamline", "phonetic": "/ˈstriːmlaɪn/", "pos": "v.", "meaning": "精簡, 使有效率", "level": "blue", "phrases": ["streamline the process", "streamlined design"], "synonyms": ["simplify", "rationalize"], "antonyms": ["complicate"], "example": "The new software system will help to streamline the company's internal procurement process."},
        {"word": "Stringent", "phonetic": "/ˈstrɪndʒənt/", "pos": "adj.", "meaning": "嚴格的, 緊縮的", "level": "blue", "phrases": ["stringent regulations", "stringent requirements"], "synonyms": ["strict", "rigorous"], "antonyms": ["lenient", "relaxed"], "example": "The food industry is subject to stringent regulations regarding hygiene and quality control."},
        {"word": "Subject", "phonetic": "/ˈsʌbdʒɪkt/", "pos": "adj./v./n.", "meaning": "受制於, 使遭受, 主題", "level": "blue", "phrases": ["subject to approval", "on the subject of"], "synonyms": ["liable", "topic"], "antonyms": [], "example": "The proposed merger is still subject to approval from the national competition authority."},
        {"word": "Subsidiary", "phonetic": "/səbˈsɪdieri/", "pos": "n./adj.", "meaning": "子公司, 附屬的", "level": "blue", "phrases": ["wholly-owned subsidiary", "subsidiary company"], "synonyms": ["affiliate", "branch"], "antonyms": ["parent company"], "example": "The parent company has decided to sell its unprofitable overseas subsidiary in Europe."},
        {"word": "Subsidize", "phonetic": "/ˈsʌbsɪdaɪz/", "pos": "v.", "meaning": "補貼, 資助", "level": "blue", "phrases": ["government subsidized", "heavily subsidize"], "synonyms": ["fund", "support"], "antonyms": [], "example": "The city council plans to subsidize the development of new affordable housing projects."},
        {"word": "Substantial", "phonetic": "/səbˈstænʃl/", "pos": "adj.", "meaning": "大量的, 實質的", "level": "blue", "phrases": ["substantial increase", "substantial amount"], "synonyms": ["significant", "considerable"], "antonyms": ["insignificant", "slight"], "example": "The company has invested a substantial amount of money in its new research facility."},
        {"word": "Substitute", "phonetic": "/ˈsʌbstɪtuːt/", "pos": "n./v.", "meaning": "代替品, 代替", "level": "blue", "phrases": ["temporary substitute", "substitute for"], "synonyms": ["replacement", "alternative"], "antonyms": [], "example": "Margarine is often used as a cheaper substitute for butter in commercial baking."},
        {"word": "Succession", "phonetic": "/səkˈseʃn/", "pos": "n.", "meaning": "繼承, 連續", "level": "blue", "phrases": ["in quick succession", "succession planning"], "synonyms": ["sequence", "series"], "antonyms": [], "example": "The company is currently developing a formal succession plan for its senior management roles."},
        {"word": "Summary", "phonetic": "/ˈsʌməri/", "pos": "n./adj.", "meaning": "摘要, 總括的", "level": "blue", "phrases": ["executive summary", "brief summary"], "synonyms": ["synopsis", "outline"], "antonyms": [], "example": "Please provide a brief executive summary of the project's key findings and recommendations."},
        {"word": "Supervise", "phonetic": "/ˈsuːpərvaɪz/", "pos": "v.", "meaning": "監督, 管理", "level": "blue", "phrases": ["supervise the work", "closely supervised"], "synonyms": ["oversee", "manage"], "antonyms": [], "example": "The department head is responsible for supervising the work of ten junior designers."},
        {"word": "Supplement", "phonetic": "/ˈsʌplɪmənt/", "pos": "n./v.", "meaning": "補充, 增刊, 補貼", "level": "blue", "phrases": ["dietary supplement", "supplement one's income"], "synonyms": ["addition", "add"], "antonyms": [], "example": "He takes a second job on the weekends to supplement his regular monthly income."},
        {"word": "Surplus", "phonetic": "/ˈsɜːrpləs/", "pos": "n./adj.", "meaning": "剩餘, 盈餘, 多餘的", "level": "blue", "phrases": ["budget surplus", "surplus stock"], "synonyms": ["excess", "remainder"], "antonyms": ["deficit", "shortage"], "example": "The government reported a significant budget surplus at the end of the last fiscal year."},
        {"word": "Survey", "phonetic": "/ˈsɜːrveɪ/", "pos": "n./v.", "meaning": "調查, 測量", "level": "blue", "phrases": ["conduct a survey", "customer survey"], "synonyms": ["poll", "study"], "antonyms": [], "example": "The marketing department is conducting a customer survey to gauge interest in our new products."},
        {"word": "Suspension", "phonetic": "/səˈspenʃn/", "pos": "n.", "meaning": "暫停, 停職, 懸吊", "level": "blue", "phrases": ["temporary suspension", "suspension from work"], "synonyms": ["interruption", "delay"], "antonyms": ["continuation"], "example": "The employee was given a three-day suspension from work for violating the company's safety rules."},
        {"word": "Sustainability", "phonetic": "/səˌsteɪnəˈbɪləti/", "pos": "n.", "meaning": "永續性", "level": "blue", "phrases": ["environmental sustainability", "sustainability report"], "synonyms": [], "antonyms": [], "example": "The company is committed to improving its environmental sustainability and reducing its carbon footprint."},
        {"word": "Synergy", "phonetic": "/ˈsɪnərdʒi/", "pos": "n.", "meaning": "綜效, 協同作用", "level": "blue", "phrases": ["create synergy", "team synergy"], "synonyms": ["collaboration", "cooperation"], "antonyms": [], "example": "The merger of the two companies is expected to create significant synergies and reduce costs."},
        {"word": "Synopsis", "phonetic": "/sɪˈnɑːpsɪs/", "pos": "n.", "meaning": "大綱, 摘要", "level": "blue", "phrases": ["brief synopsis", "provide a synopsis"], "synonyms": ["summary", "outline"], "antonyms": [], "example": "The author provided a brief synopsis of the plot to the potential publishing agent."},
        {"word": "Tactful", "phonetic": "/ˈtæktfl/", "pos": "adj.", "meaning": "圓滑的, 得體的, 有分寸的", "level": "blue", "phrases": ["tactful manner", "be tactful"], "synonyms": ["diplomatic", "considerate"], "antonyms": ["tactless", "rude"], "example": "The manager used a tactful approach when providing feedback to the sensitive employee."},
        {"word": "Target", "phonetic": "/ˈtɑːrɡɪt/", "pos": "n./v.", "meaning": "目標, 瞄準", "level": "blue", "phrases": ["sales target", "target audience"], "synonyms": ["goal", "objective"], "antonyms": [], "example": "The sales team is working hard to meet their quarterly revenue target by the end of the month."},
        {"word": "Tariff", "phonetic": "/ˈtærɪf/", "pos": "n.", "meaning": "關稅, 價目表", "level": "blue", "phrases": ["import tariff", "protective tariff"], "synonyms": ["duty", "tax"], "antonyms": [], "example": "The government decided to impose higher tariffs on imported steel to protect local manufacturers."},
        {"word": "Taxation", "phonetic": "/tækˈseɪʃn/", "pos": "n.", "meaning": "課稅, 稅收", "level": "blue", "phrases": ["double taxation", "corporate taxation"], "synonyms": ["levy"], "antonyms": [], "example": "The new government plans to introduce significant reforms to the national taxation system."},
        {"word": "Technician", "phonetic": "/tekˈnɪʃn/", "pos": "n.", "meaning": "技術員, 技師", "level": "blue", "phrases": ["IT technician", "highly skilled technician"], "synonyms": [], "antonyms": [], "example": "A qualified technician was called in to repair the broken air conditioning unit in the office."},
        {"word": "Temporary", "phonetic": "/ˈtempəreri/", "pos": "adj.", "meaning": "暫時的", "level": "blue", "phrases": ["temporary job", "temporary solution"], "synonyms": ["brief", "short-term"], "antonyms": ["permanent"], "example": "The company hired ten temporary workers to help manage the increased workload during the holiday season."},
        {"word": "Tenant", "phonetic": "/ˈtenənt/", "pos": "n.", "meaning": "租戶, 房客", "level": "blue", "phrases": ["sitting tenant", "commercial tenant"], "synonyms": ["lessee", "occupant"], "antonyms": ["landlord"], "example": "The landlord is looking for a reliable new tenant for the vacant apartment on the third floor."},
        {"word": "Tender", "phonetic": "/ˈtendər/", "pos": "v./n./adj.", "meaning": "投標, 償付, 溫柔的", "level": "blue", "phrases": ["legal tender", "put out to tender"], "synonyms": ["bid", "offer"], "antonyms": [], "example": "The city council has put the new highway construction project out to public tender."},
        {"word": "Tenure", "phonetic": "/ˈtenjər/", "pos": "n.", "meaning": "任期, 終身職位", "level": "blue", "phrases": ["long tenure", "academic tenure"], "synonyms": ["term", "occupancy"], "antonyms": [], "example": "During her long tenure as CEO, the company saw significant growth and global expansion."},
        {"word": "Terminate", "phonetic": "/ˈtɜːrmɪneɪt/", "pos": "v.", "meaning": "終止, 結束", "level": "blue", "phrases": ["terminate a contract", "terminate employment"], "synonyms": ["end", "conclude"], "antonyms": ["initiate", "commence"], "example": "The company has the right to terminate the agreement if the terms are not met by the client."},
        {"word": "Testimonial", "phonetic": "/ˌtestɪˈmoʊniəl/", "pos": "n.", "meaning": "推薦信, 證言", "level": "blue", "phrases": ["customer testimonial", "written testimonial"], "synonyms": ["endorsement", "tribute"], "antonyms": [], "example": "The company's website features several positive testimonials from satisfied clients."},
        {"word": "Threshold", "phonetic": "/ˈθreʃhoʊld/", "pos": "n.", "meaning": "門檻, 開端, 臨界點", "level": "blue", "phrases": ["income threshold", "tax threshold"], "synonyms": ["boundary", "limit"], "antonyms": [], "example": "The government has raised the income threshold for the lowest tax bracket this year."},
        {"word": "Toll", "phonetic": "/toʊl/", "pos": "n./v.", "meaning": "過路費, 傷亡人數, 敲鐘", "level": "blue", "phrases": ["toll road", "toll-free number"], "synonyms": ["fee", "charge"], "antonyms": [], "example": "The new highway project will be funded by charging a toll to all passing vehicles."},
        {"word": "Transaction", "phonetic": "/trænˈzækʃn/", "pos": "n.", "meaning": "交易, 處理", "level": "blue", "phrases": ["financial transaction", "record a transaction"], "synonyms": ["deal", "business"], "antonyms": [], "example": "All online transactions are encrypted to ensure the security of our customers' personal information."},
        {"word": "Transcript", "phonetic": "/ˈtrænskrɪpt/", "pos": "n.", "meaning": "成績單, 抄本, 錄音文本", "level": "blue", "phrases": ["academic transcript", "official transcript"], "synonyms": ["record", "copy"], "antonyms": [], "example": "Applicants are required to submit an official academic transcript along with their resume."},
        {"word": "Transformation", "phonetic": "/ˌtrænsfərˈmeɪʃn/", "pos": "n.", "meaning": "轉型, 轉變", "level": "blue", "phrases": ["digital transformation", "complete transformation"], "synonyms": ["change", "alteration"], "antonyms": ["stagnation"], "example": "The company is undergoing a digital transformation to stay competitive in the evolving market."},
        {"word": "Transit", "phonetic": "/ˈtrænzɪt/", "pos": "n./v.", "meaning": "過境, 運輸, 通過", "level": "blue", "phrases": ["public transit", "in transit"], "synonyms": ["transport", "passage"], "antonyms": [], "example": "The shipment of raw materials is currently in transit and should arrive at the port by Friday."},
        {"word": "Translation", "phonetic": "/trænsˈleɪʃn/", "pos": "n.", "meaning": "翻譯", "level": "blue", "phrases": ["accurate translation", "simultaneous translation"], "synonyms": ["interpretation", "rendering"], "antonyms": [], "example": "The user manual has been provided in several different languages for our international customers."},
        {"word": "Transparency", "phonetic": "/trænsˈpærənsi/", "pos": "n.", "meaning": "透明度, 透明性", "level": "blue", "phrases": ["financial transparency", "corporate transparency"], "synonyms": ["clarity", "openness"], "antonyms": ["opacity", "secrecy"], "example": "The organization is working to improve transparency regarding its environmental impact and sustainability efforts."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
