import json
import os

def update_vocab():
    # 第十四批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Condition", "phonetic": "/kənˈdɪʃn/", "pos": "n./v.", "meaning": "條件, 狀況, 以...為條件", "level": "blue", "phrases": ["working conditions", "on condition that"], "synonyms": ["requirement", "state"], "antonyms": [], "example": "The employees are demanding better working conditions and a significant pay increase."},
        {"word": "Conditional", "phonetic": "/kənˈdɪʃənl/", "pos": "adj.", "meaning": "有條件的, 視...而定的", "level": "blue", "phrases": ["conditional offer", "conditional approval"], "synonyms": ["contingent", "dependent"], "antonyms": ["unconditional"], "example": "The company made a conditional offer to the candidate, pending a successful background check."},
        {"word": "Condolence", "phonetic": "/kənˈdoʊləns/", "pos": "n.", "meaning": "弔唁, 慰問", "level": "blue", "phrases": ["express condolences", "letter of condolence"], "synonyms": ["sympathy", "pity"], "antonyms": [], "example": "The CEO sent a formal letter of condolence to the family of the late founding member."},
        {"word": "Condone", "phonetic": "/kənˈdoʊn/", "pos": "v.", "meaning": "寬恕, 縱容", "level": "blue", "phrases": ["condone violence", "cannot condone"], "synonyms": ["excuse", "pardon"], "antonyms": ["condemn", "punish"], "example": "The organization does not condone any form of harassment or discrimination in the workplace."},
        {"word": "Conducive", "phonetic": "/kənˈduːsɪv/", "pos": "adj.", "meaning": "有助於...的, 促成的", "level": "blue", "phrases": ["conducive to", "environment conducive to learning"], "synonyms": ["helpful", "favorable"], "antonyms": ["unfavorable"], "example": "A quiet and well-lit office is more conducive to productivity and employee well-being."},
        {"word": "Conduct", "phonetic": "/kənˈdʌkt/", "pos": "v./n.", "meaning": "引導, 實施, 行為, 指導", "level": "blue", "phrases": ["conduct a survey", "code of conduct"], "synonyms": ["perform", "manage", "behavior"], "antonyms": [], "example": "The research team is planning to conduct a thorough market analysis of the renewable energy sector."},
        {"word": "Confer", "phonetic": "/kənˈfɜːr/", "pos": "v.", "meaning": "商談, 授予", "level": "blue", "phrases": ["confer with", "confer a degree"], "synonyms": ["consult", "grant"], "antonyms": [], "example": "The manager needs to confer with the legal department before making a final decision on the contract."},
        {"word": "Conference", "phonetic": "/ˈkɑːnfərəns/", "pos": "n.", "meaning": "會議, 協商會", "level": "blue", "phrases": ["press conference", "annual conference"], "synonyms": ["meeting", "convention"], "antonyms": [], "example": "Delegates from over twenty countries attended the international conference on climate change."},
        {"word": "Confidence", "phonetic": "/ˈkɑːnfɪdəns/", "pos": "n.", "meaning": "信心, 信任, 機密", "level": "blue", "phrases": ["consumer confidence", "in confidence"], "synonyms": ["trust", "certainty"], "antonyms": ["doubt", "uncertainty"], "example": "Rising consumer confidence is expected to boost retail sales during the upcoming holiday season."},
        {"word": "Configuration", "phonetic": "/kənˌfɪɡjəˈreɪʃn/", "pos": "n.", "meaning": "配置, 結構, 構造", "level": "blue", "phrases": ["system configuration", "standard configuration"], "synonyms": ["arrangement", "layout"], "antonyms": [], "example": "The technician is working to optimize the network configuration for faster data transmission speeds."},
        {"word": "Confine", "phonetic": "/kənˈfaɪn/", "pos": "v.", "meaning": "限制, 禁閉", "level": "blue", "phrases": ["confine to", "be confined to"], "synonyms": ["restrict", "limit"], "antonyms": ["release", "expand"], "example": "The discussion will be confined to the specific issues raised in the initial project proposal."},
        {"word": "Confirm", "phonetic": "/kənˈfɜːrm/", "pos": "v.", "meaning": "確認, 證實", "level": "blue", "phrases": ["confirm a booking", "fully confirm"], "synonyms": ["verify", "validate"], "antonyms": ["deny", "refute"], "example": "Please call the office to confirm your attendance at the mandatory safety training workshop."},
        {"word": "Confirmation", "phonetic": "/ˌkɑːnfərˈmeɪʃn/", "pos": "n.", "meaning": "確認, 證實, 批准", "level": "blue", "phrases": ["written confirmation", "receive confirmation"], "synonyms": ["verification", "confirmation"], "antonyms": ["cancellation"], "example": "We are still waiting for written confirmation from the client regarding the new project deadlines."},
        {"word": "Conflict", "phonetic": "/ˈkɑːnflɪkt/", "pos": "n./v.", "meaning": "衝突, 爭執, 矛盾", "level": "blue", "phrases": ["conflict of interest", "resolve a conflict"], "synonyms": ["dispute", "clash"], "antonyms": ["harmony", "agreement"], "example": "The management team is working hard to resolve the conflict between the two departments."},
        {"word": "Conform", "phonetic": "/kənˈfɔːrm/", "pos": "v.", "meaning": "遵守, 符合, 順應", "level": "blue", "phrases": ["conform to standards", "conform with"], "synonyms": ["comply", "adhere"], "antonyms": ["violate", "defy"], "example": "All products must conform to the national safety standards before they can be sold in the market."},
        {"word": "Confront", "phonetic": "/kənˈfrʌnt/", "pos": "v.", "meaning": "面臨, 對抗, 遭遇", "level": "blue", "phrases": ["confront a problem", "be confronted with"], "synonyms": ["face", "encounter"], "antonyms": ["avoid", "evade"], "example": "The industry is currently being confronted with significant challenges due to rising material costs."},
        {"word": "Confusion", "phonetic": "/kənˈfjuːʒn/", "pos": "n.", "meaning": "混亂, 困惑", "level": "blue", "phrases": ["cause confusion", "mass confusion"], "synonyms": ["disorder", "uncertainty"], "antonyms": ["clarity", "order"], "example": "The sudden change in policy caused a great deal of confusion among the regional managers."},
        {"word": "Congestion", "phonetic": "/kənˈdʒestʃən/", "pos": "n.", "meaning": "擁擠, 堵塞", "level": "blue", "phrases": ["traffic congestion", "port congestion"], "synonyms": ["crowding", "blockage"], "antonyms": [], "example": "The company is looking for alternative routes to avoid the severe traffic congestion in the city center."},
        {"word": "Congratulate", "phonetic": "/kənˈɡrætʃuleɪt/", "pos": "v.", "meaning": "祝賀, 恭喜", "level": "blue", "phrases": ["congratulate someone on", "heartily congratulate"], "synonyms": ["applaud", "praise"], "antonyms": ["criticize"], "example": "I would like to congratulate the entire development team on the successful launch of the new app."},
        {"word": "Congregate", "phonetic": "/ˈkɑːŋɡrɪɡeɪt/", "pos": "v.", "meaning": "聚集, 集合", "level": "blue", "phrases": ["congregate in the lobby", "crowds congregate"], "synonyms": ["gather", "assemble"], "antonyms": ["disperse", "scatter"], "example": "Employees were asked to congregate in the main assembly hall for an urgent company announcement."},
        {"word": "Congress", "phonetic": "/ˈkɑːŋɡrəs/", "pos": "n.", "meaning": "代表大會, 國會", "level": "blue", "phrases": ["international congress", "act of congress"], "synonyms": ["assembly", "convention"], "antonyms": [], "example": "Several senior executives from our firm will attend the international congress on digital innovation."},
        {"word": "Conjunction", "phonetic": "/kənˈdʒʌŋkʃn/", "pos": "n.", "meaning": "結合, 同時發生, 連接詞", "level": "blue", "phrases": ["in conjunction with", "unfortunate conjunction"], "synonyms": ["combination", "union"], "antonyms": ["separation"], "example": "The marketing campaign will be run in conjunction with several local community events."},
        {"word": "Connect", "phonetic": "/kəˈnekt/", "pos": "v.", "meaning": "連接, 連結, 聯絡", "level": "blue", "phrases": ["connect to the internet", "well-connected"], "synonyms": ["link", "attach", "join"], "antonyms": ["disconnect", "separate"], "example": "The new software system allows regional offices to connect directly with the central database."},
        {"word": "Connection", "phonetic": "/kəˈnekʃn/", "pos": "n.", "meaning": "連接, 關係, 接駁交通", "level": "blue", "phrases": ["business connections", "miss a connection"], "synonyms": ["link", "relationship", "tie"], "antonyms": ["separation"], "example": "Having strong business connections in the region is essential for our long-term expansion plans."},
        {"word": "Connotation", "phonetic": "/ˌkɑːnəˈteɪʃn/", "pos": "n.", "meaning": "內涵, 隱含意義", "level": "blue", "phrases": ["negative connotation", "positive connotation"], "synonyms": ["implication", "undertone"], "antonyms": ["denotation"], "example": "The term 'downsizing' often has a negative connotation for employees despite its corporate necessity."},
        {"word": "Conquer", "phonetic": "/ˈkɑːŋkər/", "pos": "v.", "meaning": "征服, 克服", "level": "blue", "phrases": ["conquer the market", "conquer fears"], "synonyms": ["overcome", "defeat"], "antonyms": ["lose", "surrender"], "example": "The tech giant is determined to conquer the emerging markets of Southeast Asia within three years."},
        {"word": "Conscience", "phonetic": "/ˈkɑːnʃəns/", "pos": "n.", "meaning": "良心, 良知", "level": "blue", "phrases": ["clear conscience", "matter of conscience"], "synonyms": ["morals", "ethics"], "antonyms": [], "example": "The company's commitment to social responsibility is driven by a strong corporate conscience."},
        {"word": "Conscious", "phonetic": "/ˈkɑːnʃəs/", "pos": "adj.", "meaning": "意識到的, 刻意的, 神志清醒的", "level": "blue", "phrases": ["cost conscious", "environmentally conscious"], "synonyms": ["aware", "deliberate"], "antonyms": ["unconscious", "unaware"], "example": "Many modern consumers are becoming more environmentally conscious and prefer sustainable products."},
        {"word": "Consecutive", "phonetic": "/kənˈsekjətɪv/", "pos": "adj.", "meaning": "連續的, 連貫的", "level": "blue", "phrases": ["consecutive days", "third consecutive year"], "synonyms": ["successive", "sequential"], "antonyms": ["discontinuous"], "example": "The firm has reported a record increase in quarterly profits for the fourth consecutive year."},
        {"word": "Consensus", "phonetic": "/kənˈsensəs/", "pos": "n.", "meaning": "共識, 一致意見", "level": "blue", "phrases": ["reach a consensus", "general consensus"], "synonyms": ["agreement", "accord"], "antonyms": ["disagreement", "dispute"], "example": "The committee finally reached a consensus on the terms of the new employee benefits policy."},
        {"word": "Consent", "phonetic": "/kənˈsent/", "pos": "n./v.", "meaning": "同意, 贊成", "level": "blue", "phrases": ["mutual consent", "written consent"], "synonyms": ["agreement", "permission"], "antonyms": ["dissent", "refusal"], "example": "Please ensure that you have obtained the client's written consent before disclosing any project details."},
        {"word": "Consequence", "phonetic": "/ˈkɑːnsəkwens/", "pos": "n.", "meaning": "後果, 重要性", "level": "blue", "phrases": ["face the consequences", "of little consequence"], "synonyms": ["result", "outcome", "importance"], "antonyms": ["cause"], "example": "Failure to comply with the new safety regulations could have serious legal consequences for the firm."},
        {"word": "Consequently", "phonetic": "/ˈkɑːnsəkwentli/", "pos": "adv.", "meaning": "因此, 所以", "level": "blue", "phrases": ["act consequently"], "synonyms": ["therefore", "accordingly"], "antonyms": [], "example": "The initial project deadlines were missed; consequently, the entire launch schedule had to be revised."},
        {"word": "Conservation", "phonetic": "/ˌkɑːnsərˈveɪʃn/", "pos": "n.", "meaning": "保護, 保存, 節約", "level": "blue", "phrases": ["energy conservation", "wildlife conservation"], "synonyms": ["preservation", "protection"], "antonyms": ["destruction", "waste"], "example": "The company is implementing several energy conservation measures to reduce its overall carbon footprint."},
        {"word": "Conservative", "phonetic": "/kənˈsɜːrvətɪv/", "pos": "adj./n.", "meaning": "保守的, 傳統的", "level": "blue", "phrases": ["conservative estimate", "conservative approach"], "synonyms": ["traditional", "cautious"], "antonyms": ["liberal", "radical"], "example": "A conservative estimate suggest that the project will take at least six months to complete."},
        {"word": "Conserve", "phonetic": "/kənˈsɜːrv/", "pos": "v.", "meaning": "保存, 節約", "level": "blue", "phrases": ["conserve energy", "conserve resources"], "synonyms": ["save", "protect"], "antonyms": ["waste", "squander"], "example": "We are looking for ways to conserve water and reduce waste in our manufacturing process."},
        {"word": "Consider", "phonetic": "/kənˈsɪdər/", "pos": "v.", "meaning": "考慮, 認為", "level": "blue", "phrases": ["consider all options", "be considered for"], "synonyms": ["think about", "contemplate"], "antonyms": ["ignore", "neglect"], "example": "The board of directors is carefully considering the potential legal ramifications of the proposed merger."},
        {"word": "Considerable", "phonetic": "/kənˈsɪdərəbl/", "pos": "adj.", "meaning": "相當大(或多)的, 值得考慮的", "level": "blue", "phrases": ["considerable amount", "considerable progress"], "synonyms": ["substantial", "significant"], "antonyms": ["insignificant", "slight"], "example": "The company has invested a considerable amount of money in its new research and development facility."},
        {"word": "Considerate", "phonetic": "/kənˈsɪdərət/", "pos": "adj.", "meaning": "體貼的, 考慮周到的", "level": "blue", "phrases": ["highly considerate", "considerate behavior"], "synonyms": ["thoughtful", "kind"], "antonyms": ["inconsiderate", "selfish"], "example": "It was very considerate of the manager to allow the team to leave early before the long weekend."},
        {"word": "Consideration", "phonetic": "/kənˌsɪdəˈreɪʃn/", "pos": "n.", "meaning": "考慮, 體貼, 報酬", "level": "blue", "phrases": ["under consideration", "take into consideration"], "synonyms": ["thought", "attention", "payment"], "antonyms": ["neglect"], "example": "Your application for the senior management position is currently under serious consideration by the committee."},
        {"word": "Consign", "phonetic": "/kənˈsaɪn/", "pos": "v.", "meaning": "交付, 委託, 運送", "level": "blue", "phrases": ["consign goods", "be consigned to"], "synonyms": ["deliver", "entrust"], "antonyms": [], "example": "The manufacturer decided to consign the goods to a specialized distribution firm in Europe."},
        {"word": "Consignment", "phonetic": "/kənˈsaɪnmənt/", "pos": "n.", "meaning": "交付, 委託, 運送的貨物", "level": "blue", "phrases": ["bulk consignment", "on consignment"], "synonyms": ["shipment", "delivery"], "antonyms": [], "example": "We are expecting a large consignment of raw materials to arrive at the port tomorrow morning."},
        {"word": "Consist", "phonetic": "/kənˈsɪst/", "pos": "v.", "meaning": "由...組成, 在於", "level": "blue", "phrases": ["consist of", "consist in"], "synonyms": ["comprise", "composed of"], "antonyms": [], "example": "The newly established committee will consist of representatives from each of the regional offices."},
        {"word": "Consistency", "phonetic": "/kənˈsɪstənsi/", "pos": "n.", "meaning": "一致性, 連貫性, 稠度", "level": "blue", "phrases": ["lack of consistency", "achieve consistency"], "synonyms": ["uniformity", "constancy"], "antonyms": ["inconsistency"], "example": "Consistency in product quality is essential for building and maintaining customer trust worldwide."},
        {"word": "Consistent", "phonetic": "/kənˈsɪstənt/", "pos": "adj.", "meaning": "一致的, 連貫的, 始終如一的", "level": "blue", "phrases": ["consistent results", "be consistent with"], "synonyms": ["uniform", "steady"], "antonyms": ["inconsistent"], "example": "The firm's latest financial statements are consistent with its previous quarterly reporting and projections."},
        {"word": "Consolation", "phonetic": "/ˌkɑːnsəˈleɪʃn/", "pos": "n.", "meaning": "慰藉, 安慰", "level": "blue", "phrases": ["offer consolation", "small consolation"], "synonyms": ["comfort", "solace"], "antonyms": [], "example": "The award served as a small consolation for the team after the cancellation of their main project."},
        {"word": "Console", "phonetic": "/kənˈsoʊl/", "pos": "v.", "meaning": "安慰, 撫慰", "level": "blue", "phrases": ["console someone", "try to console"], "synonyms": ["comfort", "soothe"], "antonyms": ["upset"], "example": "The CEO tried to console the employees who were affected by the recent corporate restructuring."},
        {"word": "Consolidate", "phonetic": "/kənˈsɑːlɪdeɪt/", "pos": "v.", "meaning": "鞏固, 合併, 強化", "level": "blue", "phrases": ["consolidate debt", "consolidate power"], "synonyms": ["unify", "merge", "strengthen"], "antonyms": ["separate", "divide"], "example": "The two competing firms decided to consolidate their operations to reduce overall annual operating costs."},
        {"word": "Consortium", "phonetic": "/kənˈsɔːrtiəm/", "pos": "n.", "meaning": "財團, 聯盟, 協會", "level": "blue", "phrases": ["international consortium", "banking consortium"], "synonyms": ["syndicate", "alliance"], "antonyms": [], "example": "A consortium of international banks provided the funding for the new infrastructure project in the region."},
        {"word": "Conspicuous", "phonetic": "/kənˈspɪkjuəs/", "pos": "adj.", "meaning": "顯眼的, 顯著的", "level": "blue", "phrases": ["conspicuous consumption", "conspicuous position"], "synonyms": ["obvious", "noticeable"], "antonyms": ["inconspicuous", "hidden"], "example": "The lack of safety equipment in the warehouse was a conspicuous violation of the new regulations."},
        {"word": "Conspiracy", "phonetic": "/kənˈspɪrəsi/", "pos": "n.", "meaning": "陰謀, 共謀", "level": "blue", "phrases": ["conspiracy theory", "criminal conspiracy"], "synonyms": ["plot", "scheme"], "antonyms": [], "example": "The authorities are investigating an alleged conspiracy to manipulate the local stock market prices."},
        {"word": "Conspire", "phonetic": "/kənˈspaɪər/", "pos": "v.", "meaning": "共謀, 密謀, 協力促成", "level": "blue", "phrases": ["conspire against", "circumstances conspire"], "synonyms": ["plot", "scheme"], "antonyms": [], "example": "Poor weather and technical issues conspired to delay the official launch of the new satellite."},
        {"word": "Constancy", "phonetic": "/ˈkɑːnstənsi/", "pos": "n.", "meaning": "堅定, 不變, 忠誠", "level": "blue", "phrases": ["constancy of purpose"], "synonyms": ["steadiness", "loyalty"], "antonyms": ["inconstancy", "change"], "example": "The constancy of the firm's growth over the last decade has attracted many long-term investors."},
        {"word": "Constant", "phonetic": "/ˈkɑːnstənt/", "pos": "adj./n.", "meaning": "持續的, 不變的, 常數", "level": "blue", "phrases": ["constant pressure", "at a constant rate"], "synonyms": ["continuous", "steady"], "antonyms": ["variable", "irregular"], "example": "The factory is under constant pressure to increase its monthly production to meet the rising demand."},
        {"word": "Constantly", "phonetic": "/ˈkɑːnstəntli/", "pos": "adv.", "meaning": "不斷地, 經常地", "level": "blue", "phrases": ["constantly evolving", "constantly improve"], "synonyms": ["always", "continually"], "antonyms": ["occasionally"], "example": "We are constantly looking for ways to improve our customer service and reduce overall client wait times."},
        {"word": "Constituent", "phonetic": "/kənˈstɪtʃuənt/", "pos": "n./adj.", "meaning": "成分, 選民, 構成的", "level": "blue", "phrases": ["constituent parts", "meet with constituents"], "synonyms": ["component", "element"], "antonyms": ["whole"], "example": "Please ensure that all the constituent parts of the equipment are accounted for before shipping."},
        {"word": "Constitute", "phonetic": "/ˈkɑːnstɪtuːt/", "pos": "v.", "meaning": "構成, 組成, 被視為", "level": "blue", "phrases": ["constitute a quorum", "be constituted"], "synonyms": ["compose", "form"], "antonyms": [], "example": "Failure to deliver the goods on time will constitute a breach of the existing service agreement."},
        {"word": "Constitution", "phonetic": "/ˌkɑːnstɪˈtuːʃn/", "pos": "n.", "meaning": "憲法, 構成, 體質", "level": "blue", "phrases": ["company constitution", "written constitution"], "synonyms": ["makeup", "structure"], "antonyms": [], "example": "The regional managers were asked to review the company's constitution following the recent merger."},
        {"word": "Constraint", "phonetic": "/kənˈstreɪnt/", "pos": "n.", "meaning": "限制, 約束, 強迫", "level": "blue", "phrases": ["budget constraints", "legal constraints"], "synonyms": ["restriction", "limitation"], "antonyms": ["freedom"], "example": "Severe budget constraints have forced the department to postpone several innovative research projects."},
        {"word": "Construct", "phonetic": "/kənˈstrʌkt/", "pos": "v./n.", "meaning": "建造, 構成, 建築物", "level": "blue", "phrases": ["construct a building", "theoretical construct"], "synonyms": ["build", "create"], "antonyms": ["demolish", "destroy"], "example": "The engineering firm has been hired to construct a new energy-efficient distribution center in the city."},
        {"word": "Construction", "phonetic": "/kənˈstrʌkʃn/", "pos": "n.", "meaning": "建造, 施工, 解釋", "level": "blue", "phrases": ["under construction", "construction site"], "synonyms": ["building", "erection"], "antonyms": ["destruction"], "example": "The new headquarters building is currently under construction and is expected to be completed late next year."},
        {"word": "Constructive", "phonetic": "/kənˈstrʌktɪv/", "pos": "adj.", "meaning": "建設性的, 積極的", "level": "blue", "phrases": ["constructive criticism", "constructive feedback"], "synonyms": ["helpful", "useful"], "antonyms": ["destructive", "negative"], "example": "The manager provided constructive feedback to the team to help them improve their overall performance."},
        {"word": "Consult", "phonetic": "/kənˈsʌlt/", "pos": "v.", "meaning": "諮詢, 請教, 商量", "level": "blue", "phrases": ["consult a specialist", "consult with"], "synonyms": ["seek advice", "confer"], "antonyms": ["ignore"], "example": "We need to consult with a financial specialist before making a final decision on the international investment."},
        {"word": "Consultant", "phonetic": "/kənˈsʌltənt/", "pos": "n.", "meaning": "顧問", "level": "blue", "phrases": ["management consultant", "external consultant"], "synonyms": ["advisor", "expert"], "antonyms": [], "example": "An external management consultant was hired to help streamline the company's internal administrative processes."},
        {"word": "Consultation", "phonetic": "/ˌkɑːnslˈteɪʃn/", "pos": "n.", "meaning": "諮詢, 商議", "level": "blue", "phrases": ["free consultation", "in consultation with"], "synonyms": ["meeting", "deliberation"], "antonyms": [], "example": "The new policy was developed in consultation with representatives from all major departments in the firm."},
        {"word": "Consume", "phonetic": "/kənˈsuːm/", "pos": "v.", "meaning": "消耗, 消費, 吃/喝", "level": "blue", "phrases": ["consume energy", "time-consuming"], "synonyms": ["use up", "utilize"], "antonyms": ["produce", "conserve"], "example": "The old manufacturing equipment consumes a significant amount of electricity compared to the newer models."},
        {"word": "Consumer", "phonetic": "/kənˈsuːmər/", "pos": "n.", "meaning": "消費者", "level": "blue", "phrases": ["consumer protection", "target consumer"], "synonyms": ["buyer", "customer"], "antonyms": ["producer", "manufacturer"], "example": "The new advertising campaign is specifically designed to appeal to the environmentally conscious consumer."},
        {"word": "Consumption", "phonetic": "/kənˈsʌmpʃn/", "pos": "n.", "meaning": "消耗, 消費量", "level": "blue", "phrases": ["energy consumption", "domestic consumption"], "synonyms": ["utilization", "usage"], "antonyms": ["production"], "example": "The company is focused on reducing its overall energy consumption and implementing more sustainable practices."},
        {"word": "Contact", "phonetic": "/ˈkɑːntækt/", "pos": "n./v.", "meaning": "聯絡, 接觸, 聯絡人", "level": "blue", "phrases": ["point of contact", "initial contact"], "synonyms": ["connection", "touch"], "antonyms": [], "example": "Please contact our customer support department if you have any questions regarding your online order."},
        {"word": "Contain", "phonetic": "/kənˈteɪn/", "pos": "v.", "meaning": "包含, 容納, 控制", "level": "blue", "phrases": ["contain a virus", "contain costs"], "synonyms": ["include", "hold", "restrain"], "antonyms": ["exclude"], "example": "The final report should contain a detailed executive summary of all major project findings and recommendations."},
        {"word": "Container", "phonetic": "/kənˈteɪnər/", "pos": "n.", "meaning": "容器, 貨櫃", "level": "blue", "phrases": ["shipping container", "reusable container"], "synonyms": ["vessel", "box"], "antonyms": [], "example": "A large shipment of goods arrived at the port this morning in ten forty-foot shipping containers."},
        {"word": "Contaminate", "phonetic": "/kənˈtæmɪneɪt/", "pos": "v.", "meaning": "污染, 弄髒", "level": "blue", "phrases": ["contaminate the water", "contaminated soil"], "synonyms": ["pollute", "taint"], "antonyms": ["purify", "clean"], "example": "The factory was closed following reports that hazardous waste had contaminated the nearby local water supply."},
        {"word": "Contamination", "phonetic": "/kənˌtæmɪˈneɪʃn/", "pos": "n.", "meaning": "污染", "level": "blue", "phrases": ["environmental contamination", "prevent contamination"], "synonyms": ["pollution", "impurity"], "antonyms": ["purification"], "example": "Rigorous safety measures are in place to prevent any contamination of the chemical manufacturing facility."},
        {"word": "Contemplate", "phonetic": "/ˈkɑːntəmpleɪt/", "pos": "v.", "meaning": "沉思, 考慮", "level": "blue", "phrases": ["contemplate a move", "contemplate change"], "synonyms": ["consider", "ponder"], "antonyms": ["ignore"], "example": "The board of directors is contemplating a major expansion into the emerging markets of Southeast Asia."},
        {"word": "Contemporary", "phonetic": "/kənˈtempəreri/", "pos": "adj./n.", "meaning": "當代的, 同時代的, 同時代的人", "level": "blue", "phrases": ["contemporary art", "contemporary style"], "synonyms": ["modern", "current"], "antonyms": ["ancient", "historical"], "example": "The new office building features a contemporary architectural style that blends well with the urban landscape."},
        {"word": "Contempt", "phonetic": "/kənˈtempt/", "pos": "n.", "meaning": "輕視, 蔑視, 藐視(法庭)", "level": "blue", "phrases": ["contempt of court", "show contempt"], "synonyms": ["disdain", "scorn"], "antonyms": ["respect", "admiration"], "example": "The firm was found in contempt of court for failing to provide the requested financial documents on time."},
        {"word": "Contend", "phonetic": "/kənˈtend/", "pos": "v.", "meaning": "競爭, 主張, 對抗", "level": "blue", "phrases": ["contend for a prize", "contend that"], "synonyms": ["compete", "argue", "assert"], "antonyms": ["agree", "surrender"], "example": "Several small firms are contending for the multi-million dollar government highway construction contract."},
        {"word": "Content", "phonetic": "/ˈkɑːntent/", "pos": "n./adj./v.", "meaning": "內容, 目錄, 滿足的, 使滿足", "level": "blue", "phrases": ["digital content", "highly content"], "synonyms": ["substance", "satisfied"], "antonyms": ["dissatisfied"], "example": "The marketing team is focusing on creating high-quality digital content to attract more potential customers."},
        {"word": "Contention", "phonetic": "/kənˈtenʃn/", "pos": "n.", "meaning": "爭論, 主張", "level": "blue", "phrases": ["point of contention", "in contention for"], "synonyms": ["dispute", "assertion"], "antonyms": ["agreement"], "example": "The proposed increase in the annual research and development budget remains a major point of contention."},
        {"word": "Contentious", "phonetic": "/kənˈtenʃəs/", "pos": "adj.", "meaning": "有爭議的, 愛爭論的", "level": "blue", "phrases": ["contentious issue", "highly contentious"], "synonyms": ["controversial", "quarrelsome"], "antonyms": ["uncontroversial"], "example": "The decision to relocate the regional distribution center has become a highly contentious issue among staff."},
        {"word": "Contest", "phonetic": "/ˈkɑːntest/", "pos": "n./v.", "meaning": "競賽, 爭論, 質疑", "level": "blue", "phrases": ["marketing contest", "contest a decision"], "synonyms": ["competition", "dispute"], "antonyms": ["agree"], "example": "The firm decided to contest the government's decision to revoke its operating license in the civil court."},
        {"word": "Context", "phonetic": "/ˈkɑːntekst/", "pos": "n.", "meaning": "語境, 背景, 上下文", "level": "blue", "phrases": ["social context", "historical context"], "synonyms": ["background", "situation"], "antonyms": [], "example": "We need to analyze the latest consumer spending habits within the context of the current economic situation."},
        {"word": "Contingency", "phonetic": "/kənˈtɪndʒənsi/", "pos": "n.", "meaning": "意外事故, 偶然性, 應急費用", "level": "blue", "phrases": ["contingency plan", "contingency fund"], "synonyms": ["possibility", "eventuality"], "antonyms": ["certainty"], "example": "We have developed a comprehensive contingency plan in case the supply chain is disrupted for any reason."},
        {"word": "Continual", "phonetic": "/kənˈtɪnjuəl/", "pos": "adj.", "meaning": "頻頻的, 連續的(中間有間歇)", "level": "blue", "phrases": ["continual improvement", "continual complaints"], "synonyms": ["recurrent", "repeated"], "antonyms": ["intermittent", "sporadic"], "example": "The firm is committed to the continual improvement of its internal quality control and safety processes."},
        {"word": "Continuation", "phonetic": "/kənˌtɪnjuˈeɪʃn/", "pos": "n.", "meaning": "繼續, 續集", "level": "blue", "phrases": ["continuation of service", "continuation of a trend"], "synonyms": ["extension", "prolongation"], "antonyms": ["cessation", "end"], "example": "We are hoping for a continuation of the steady growth in our international sales over the next fiscal year."},
        {"word": "Continue", "phonetic": "/kənˈtɪnjuː/", "pos": "v.", "meaning": "繼續, 持續", "level": "blue", "phrases": ["continue working", "continue the project"], "synonyms": ["last", "endure", "persist"], "antonyms": ["stop", "discontinue"], "example": "The company plans to continue its investment in renewable energy research and development projects."},
        {"word": "Continuity", "phonetic": "/ˌkɑːntɪˈnuːəti/", "pos": "n.", "meaning": "連續性, 連貫性", "level": "blue", "phrases": ["business continuity", "continuity plan"], "synonyms": ["connection", "consistency"], "antonyms": ["discontinuity"], "example": "A business continuity plan is essential to ensure that the firm can recover quickly following a major crisis."},
        {"word": "Continuous", "phonetic": "/kənˈtɪnjuəs/", "pos": "adj.", "meaning": "連續不斷的, 持續的(中間無間歇)", "level": "blue", "phrases": ["continuous monitoring", "continuous improvement"], "synonyms": ["uninterrupted", "constant"], "antonyms": ["intermittent", "broken"], "example": "The factory uses a continuous production process to ensure maximum efficiency and reduce overall manufacturing costs."},
        {"word": "Contour", "phonetic": "/ˈkɑːntʊr/", "pos": "n./v.", "meaning": "輪廓, 外形, 畫輪廓", "level": "blue", "phrases": ["contour line", "contour of the land"], "synonyms": ["outline", "shape"], "antonyms": [], "example": "The architect presented several drawings showing the sleek and modern contours of the new headquarters building."},
        {"word": "Contract", "phonetic": "/ˈkɑːntrækt/", "pos": "n./v.", "meaning": "合約, 契約, 訂約, 收縮", "level": "blue", "phrases": ["sign a contract", "breach of contract"], "synonyms": ["agreement", "treaty", "shrink"], "antonyms": ["expand"], "example": "Please review the final draft of the service contract carefully before providing your authorized signature."},
        {"word": "Contractor", "phonetic": "/ˈkɑːntræktər/", "pos": "n.", "meaning": "承包商, 立約者", "level": "blue", "phrases": ["general contractor", "independent contractor"], "synonyms": [], "antonyms": [], "example": "Several local contractors have submitted competitive bids for the city's new library construction project."},
        {"word": "Contradict", "phonetic": "/ˌkɑːntrəˈdɪkt/", "pos": "v.", "meaning": "反駁, 與...矛盾", "level": "blue", "phrases": ["contradict each other", "directly contradict"], "synonyms": ["refute", "clash"], "antonyms": ["agree", "confirm"], "example": "The latest market data seems to contradict the initial sales projections provided by the marketing team."},
        {"word": "Contradiction", "phonetic": "/ˌkɑːntrəˈdɪkʃn/", "pos": "n.", "meaning": "矛盾, 反駁", "level": "blue", "phrases": ["in contradiction to", "direct contradiction"], "synonyms": ["discrepancy", "clash"], "antonyms": ["agreement", "consistency"], "example": "There is a direct contradiction between the firm's stated environmental goals and its actual manufacturing practices."},
        {"word": "Contradictory", "phonetic": "/ˌkɑːntrəˈdɪktəri/", "pos": "adj.", "meaning": "矛盾的, 對立的", "level": "blue", "phrases": ["contradictory reports", "highly contradictory"], "synonyms": ["conflicting", "inconsistent"], "antonyms": ["consistent"], "example": "Management received several contradictory reports regarding the potential impact of the new trade agreement."},
        {"word": "Contrary", "phonetic": "/ˈkɑːntreri/", "pos": "adj./n.", "meaning": "相反的, 反對的, 相反事物", "level": "blue", "phrases": ["on the contrary", "contrary to expectations"], "synonyms": ["opposite", "opposing"], "antonyms": ["similar", "identical"], "example": "Contrary to expectations, the company reported a record increase in quarterly sales despite the economic downturn."},
        {"word": "Contrast", "phonetic": "/ˈkɑːntræst/", "pos": "n./v.", "meaning": "對比, 對照", "level": "blue", "phrases": ["in contrast to", "sharp contrast"], "synonyms": ["comparison", "difference"], "antonyms": ["similarity"], "example": "The CEO used several charts to highlight the sharp contrast between our current performance and that of our main rivals."},
        {"word": "Contribute", "phonetic": "/kənˈtrɪbjuːt/", "pos": "v.", "meaning": "貢獻, 捐助, 投稿", "level": "blue", "phrases": ["contribute to success", "regularly contribute"], "synonyms": ["donate", "give", "help"], "antonyms": ["take", "withdraw"], "example": "Every employee is encouraged to contribute their ideas for improving efficiency and reducing waste in the office."},
        {"word": "Contribution", "phonetic": "/ˌkɑːntrɪˈbjuːʃn/", "pos": "n.", "meaning": "貢獻, 捐款, 投稿", "level": "blue", "phrases": ["outstanding contribution", "make a contribution"], "synonyms": ["donation", "gift", "assistance"], "antonyms": [], "example": "I would like to acknowledge her outstanding contribution to the successful completion of the international project."},
        {"word": "Contributor", "phonetic": "/kənˈtrɪbjətər/", "pos": "n.", "meaning": "貢獻者, 捐助者, 投稿人", "level": "blue", "phrases": ["major contributor", "regular contributor"], "synonyms": ["donor", "patron", "writer"], "antonyms": [], "example": "The firm has been a major contributor to several local community development and education programs."},
        {"word": "Contrive", "phonetic": "/kənˈtraɪv/", "pos": "v.", "meaning": "設計, 圖謀, 設法做到", "level": "blue", "phrases": ["contrive a plan", "contrive to escape"], "synonyms": ["devise", "invent", "manage"], "antonyms": [], "example": "The engineers managed to contrive a clever solution to the recurring technical issues with the production line."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
