import json
import os

def update_vocab():
    # 第十六批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Economic", "phonetic": "/ˌiːkəˈnɑːmɪk/", "pos": "adj.", "meaning": "經濟上的, 有利可圖的", "level": "blue", "phrases": ["economic growth", "economic policy"], "synonyms": ["financial", "monetary"], "antonyms": [], "example": "The government is introducing new measures to stimulate economic growth in the region."},
        {"word": "Economical", "phonetic": "/ˌiːkəˈnɑːmɪkl/", "pos": "adj.", "meaning": "節儉的, 經濟實惠的", "level": "blue", "phrases": ["economical car", "economical use of resources"], "synonyms": ["thrifty", "frugal"], "antonyms": ["extravagant", "wasteful"], "example": "The new manufacturing process is much more economical and reduces waste by 20%."},
        {"word": "Economize", "phonetic": "/ɪˈkɑːnəmaɪz/", "pos": "v.", "meaning": "節約, 節省", "level": "blue", "phrases": ["economize on fuel", "need to economize"], "synonyms": ["save", "cut back"], "antonyms": ["squander", "waste"], "example": "Many families are trying to economize on their household spending due to the rising cost of living."},
        {"word": "Ecosystem", "phonetic": "/ˈiːkoʊsɪstəm/", "pos": "n.", "meaning": "生態系統", "level": "blue", "phrases": ["business ecosystem", "fragile ecosystem"], "synonyms": [], "antonyms": [], "example": "The company is part of a large business ecosystem that includes suppliers, partners, and customers."},
        {"word": "Edge", "phonetic": "/edʒ/", "pos": "n./v.", "meaning": "邊緣, 優勢, 緩緩移動", "level": "blue", "phrases": ["competitive edge", "on the edge"], "synonyms": ["advantage", "border"], "antonyms": [], "example": "Our focus on innovation gives us a significant competitive edge over our rivals in the industry."},
        {"word": "Edible", "phonetic": "/ˈedəbl/", "pos": "adj.", "meaning": "可食用的", "level": "blue", "phrases": ["edible flowers", "hardly edible"], "synonyms": ["eatable"], "antonyms": ["inedible"], "example": "The hotel provided a basket of edible fruits and snacks for the international conference delegates."},
        {"word": "Edition", "phonetic": "/ɪˈdɪʃn/", "pos": "n.", "meaning": "版本, 版次", "level": "blue", "phrases": ["limited edition", "revised edition"], "synonyms": ["version", "issue"], "antonyms": [], "example": "A revised edition of the employee handbook will be distributed to all staff next week."},
        {"word": "Editorial", "phonetic": "/ˌedɪˈtɔːriəl/", "pos": "n./adj.", "meaning": "社論, 編輯的", "level": "blue", "phrases": ["editorial board", "editorial policy"], "synonyms": ["opinion piece"], "antonyms": [], "example": "The newspaper's editorial criticized the government's latest changes to the national tax policy."},
        {"word": "Educated", "phonetic": "/ˈedʒukeɪtɪd/", "pos": "adj.", "meaning": "受過教育的, 有教養的", "level": "blue", "phrases": ["highly educated", "educated guess"], "synonyms": ["learned", "knowledgeable"], "antonyms": ["uneducated", "ignorant"], "example": "The firm is looking for highly educated individuals with advanced degrees in finance or engineering."},
        {"word": "Educational", "phonetic": "/ˌedʒuˈkeɪʃənl/", "pos": "adj.", "meaning": "教育的, 有教育意義的", "level": "blue", "phrases": ["educational background", "educational institution"], "synonyms": ["instructive"], "antonyms": [], "example": "Please provide details of your educational background and any professional certifications on your resume."},
        {"word": "Efface", "phonetic": "/ɪˈfeɪs/", "pos": "v.", "meaning": "擦掉, 抹去, 使不顯眼", "level": "blue", "phrases": ["efface the memory", "self-effacing"], "synonyms": ["erase", "wipe out"], "antonyms": ["highlight"], "example": "Time has failed to efface the memory of the company's most successful product launch."},
        {"word": "Effect", "phonetic": "/ɪˈfekt/", "pos": "n./v.", "meaning": "結果, 影響, 產生(效果)", "level": "blue", "phrases": ["cause and effect", "take effect"], "synonyms": ["result", "impact", "influence"], "antonyms": [], "example": "The new regulations will take effect starting from the first of next month across all industries."},
        {"word": "Effective", "phonetic": "/ɪˈfektɪv/", "pos": "adj.", "meaning": "有效的, 起作用的, 給人深刻印象的", "level": "blue", "phrases": ["effective management", "highly effective"], "synonyms": ["efficient", "successful"], "antonyms": ["ineffective", "useless"], "example": "An effective management style is essential for building a productive and motivated workforce."},
        {"word": "Efficacy", "phonetic": "/ˈefɪkəsi/", "pos": "n.", "meaning": "功效, 效能", "level": "blue", "phrases": ["test the efficacy", "proven efficacy"], "synonyms": ["effectiveness"], "antonyms": ["inefficacy"], "example": "Clinical trials are currently being conducted to test the efficacy of the new pharmaceutical drug."},
        {"word": "Efficiency", "phonetic": "/ɪˈfɪʃnsi/", "pos": "n.", "meaning": "效率, 效能", "level": "blue", "phrases": ["operational efficiency", "fuel efficiency"], "synonyms": ["effectiveness", "productivity"], "antonyms": ["inefficiency"], "example": "The new software is designed to improve operational efficiency and reduce overall administrative costs."},
        {"word": "Efficient", "phonetic": "/ɪˈfɪʃnt/", "pos": "adj.", "meaning": "效率高的, 能幹的", "level": "blue", "phrases": ["efficient process", "energy efficient"], "synonyms": ["effective", "productive"], "antonyms": ["inefficient", "wasteful"], "example": "The factory plans to replace its old machinery with newer and more energy-efficient models next year."},
        {"word": "Effort", "phonetic": "/ˈefərt/", "pos": "n.", "meaning": "努力, 成就", "level": "blue", "phrases": ["joint effort", "make an effort"], "synonyms": ["attempt", "endeavor"], "antonyms": [], "example": "The successful completion of the project was the result of a joint effort from all departments."},
        {"word": "Eject", "phonetic": "/ɪˈdʒekt/", "pos": "v.", "meaning": "驅逐, 噴出, 彈出", "level": "blue", "phrases": ["eject a disc", "be ejected from"], "synonyms": ["expel", "remove"], "antonyms": [], "example": "The individual was forcibly ejected from the premises after attempting to enter without authorization."},
        {"word": "Elaborate", "phonetic": "/ɪˈlæbərət/", "pos": "adj./v.", "meaning": "精心製作的, 詳盡的, 詳盡闡述", "level": "blue", "phrases": ["elaborate plan", "elaborate on a point"], "synonyms": ["detailed", "intricate", "expand"], "antonyms": ["simple", "plain"], "example": "Could you please elaborate on your earlier comments regarding the potential risks of the investment?"},
        {"word": "Elasticity", "phonetic": "/ˌiːlæˈstɪsəti/", "pos": "n.", "meaning": "彈性, 靈活性", "level": "blue", "phrases": ["price elasticity", "income elasticity"], "synonyms": ["flexibility"], "antonyms": ["rigidity"], "example": "The price elasticity of demand for our products is quite high, meaning customers are sensitive to changes."},
        {"word": "Elect", "phonetic": "/ɪˈlekt/", "pos": "v./adj.", "meaning": "選舉, 選擇, 選定的", "level": "blue", "phrases": ["be elected to", "president elect"], "synonyms": ["choose", "vote"], "antonyms": [], "example": "The shareholders will meet next month to elect a new member to the company's board of directors."},
        {"word": "Election", "phonetic": "/ɪˈlekʃn/", "pos": "n.", "meaning": "選舉", "level": "blue", "phrases": ["general election", "hold an election"], "synonyms": ["vote", "poll"], "antonyms": [], "example": "The outcome of the upcoming national election is expected to have a significant impact on trade policy."},
        {"word": "Elective", "phonetic": "/ɪˈlektɪv/", "pos": "adj./n.", "meaning": "選舉的, 選修的, 選修課程", "level": "blue", "phrases": ["elective office", "elective course"], "synonyms": ["optional"], "antonyms": ["compulsory", "mandatory"], "example": "The training program includes several elective modules that staff can choose based on their career goals."},
        {"word": "Electoral", "phonetic": "/ɪˈlektərəl/", "pos": "adj.", "meaning": "選舉的", "level": "blue", "phrases": ["electoral system", "electoral process"], "synonyms": [], "antonyms": [], "example": "Changes to the national electoral process are currently being debated by the government committee."},
        {"word": "Electric", "phonetic": "/ɪˈlektrɪk/", "pos": "adj.", "meaning": "電的, 令人興奮的", "level": "blue", "phrases": ["electric vehicle", "electric guitar"], "synonyms": ["electrical"], "antonyms": [], "example": "The company is investing heavily in the development of new electric vehicle charging infrastructure."},
        {"word": "Electrician", "phonetic": "/ɪˌlekˈtrɪʃn/", "pos": "n.", "meaning": "電工, 電氣技師", "level": "blue", "phrases": ["certified electrician", "call an electrician"], "synonyms": [], "antonyms": [], "example": "A certified electrician was called in to inspect the faulty wiring in the company's main server room."},
        {"word": "Electricity", "phonetic": "/ɪˌlekˈtrɪsəti/", "pos": "n.", "meaning": "電", "level": "blue", "phrases": ["generate electricity", "electricity bill"], "synonyms": ["power"], "antonyms": [], "example": "Significant investment is needed to modernize the national grid and ensure a stable supply of electricity."},
        {"word": "Electronic", "phonetic": "/ɪˌlekˈtrɑːnɪk/", "pos": "adj.", "meaning": "電子位的", "level": "blue", "phrases": ["electronic mail", "electronic signature"], "synonyms": ["digital"], "antonyms": ["analog"], "example": "Please provide your authorized electronic signature at the bottom of the last page of the service contract."},
        {"word": "Electronics", "phonetic": "/ɪˌlekˈtrɑːnɪks/", "pos": "n.", "meaning": "電子學, 電子設備", "level": "blue", "phrases": ["consumer electronics", "consumer electronics show"], "synonyms": [], "antonyms": [], "example": "The consumer electronics industry is characterized by rapid innovation and fierce international competition."},
        {"word": "Elegant", "phonetic": "/ˈelɪɡənt/", "pos": "adj.", "meaning": "優雅的, 高雅的, 簡潔的", "level": "blue", "phrases": ["elegant solution", "elegant design"], "synonyms": ["graceful", "stylish", "simple"], "antonyms": ["clumsy", "awkward"], "example": "The engineer presented an elegant solution to the complex technical issues we were facing with the design."},
        {"word": "Element", "phonetic": "/ˈelɪmənt/", "pos": "n.", "meaning": "要素, 元素, 基礎", "level": "blue", "phrases": ["key element", "essential element"], "synonyms": ["component", "factor"], "antonyms": ["whole"], "example": "Customer satisfaction is a key element of our corporate strategy and is never compromised for any reason."},
        {"word": "Elementary", "phonetic": "/ˌelɪˈmentri/", "pos": "adj.", "meaning": "基本的, 初級的", "level": "blue", "phrases": ["elementary education", "elementary level"], "synonyms": ["basic", "fundamental"], "antonyms": ["advanced", "complex"], "example": "New employees are required to complete an elementary training module on company safety and security."},
        {"word": "Elevate", "phonetic": "/ˈelɪveɪt/", "pos": "v.", "meaning": "舉起, 提升, 提高", "level": "blue", "phrases": ["elevate to a position", "elevate the status"], "synonyms": ["lift", "raise", "promote"], "antonyms": ["lower", "demote"], "example": "The CEO's goal is to elevate the firm's status to that of a global leader in sustainable manufacturing."},
        {"word": "Elevation", "phonetic": "/ˌelɪˈveɪʃn/", "pos": "n.", "meaning": "高度, 提升, 正視圖", "level": "blue", "phrases": ["high elevation", "elevation of status"], "synonyms": ["altitude", "promotion"], "antonyms": ["depression", "demotion"], "example": "The architect provided several drawings showing the front and side elevations of the new office building."},
        {"word": "Eligible", "phonetic": "/ˈelɪdʒəbl/", "pos": "adj.", "meaning": "有資格的, 合適的", "level": "blue", "phrases": ["eligible for a bonus", "eligible candidate"], "synonyms": ["qualified", "suitable"], "antonyms": ["ineligible", "unqualified"], "example": "Full-time staff members are eligible for the company's comprehensive health insurance and pension plans."},
        {"word": "Eliminate", "phonetic": "/ɪˈlɪmɪneɪt/", "pos": "v.", "meaning": "消除, 排除", "level": "blue", "phrases": ["eliminate waste", "eliminate competition"], "synonyms": ["remove", "erase"], "antonyms": ["add", "create"], "example": "The organization is implementing new software to help eliminate redundant administrative tasks and reduce costs."},
        {"word": "Elimination", "phonetic": "/ɪˌlɪmɪˈneɪʃn/", "pos": "n.", "meaning": "消除, 排除, 淘汰", "level": "blue", "phrases": ["elimination of debt", "process of elimination"], "synonyms": ["removal"], "antonyms": ["addition"], "example": "The eventual elimination of international trade tariffs will lead to lower prices for consumers worldwide."},
        {"word": "Elite", "phonetic": "/eɪˈliːt/", "pos": "n./adj.", "meaning": "精英, 精銳的", "level": "blue", "phrases": ["elite group", "elite team"], "synonyms": ["pick", "best"], "antonyms": ["ordinary", "common"], "example": "The firm hired an elite team of management consultants to oversee its complex digital transformation process."},
        {"word": "Elongate", "phonetic": "/ɪˈlɔːŋɡeɪt/", "pos": "v.", "meaning": "拉長, 延長", "level": "blue", "phrases": ["elongated shape", "elongate the process"], "synonyms": ["lengthen", "stretch"], "antonyms": ["shorten", "contract"], "example": "Technical issues during the construction phase have served to elongate the project's overall completion timeline."},
        {"word": "Eloquence", "phonetic": "/ˈeləkwəns/", "pos": "n.", "meaning": "雄辯, 口才", "level": "blue", "phrases": ["natural eloquence", "great eloquence"], "synonyms": ["fluency", "oratory"], "antonyms": [], "example": "The candidate's eloquence and clear vision for the department made a very positive impression on the board."},
        {"word": "Eloquent", "phonetic": "/ˈeləkwənt/", "pos": "adj.", "meaning": "雄辯的, 有說服力的", "level": "blue", "phrases": ["eloquent speaker", "eloquent defense"], "synonyms": ["articulate", "persuasive"], "antonyms": ["inarticulate"], "example": "The CEO gave an eloquent speech at the gala dinner, thanking all employees for their dedication and hard work."},
        {"word": "Elucidate", "phonetic": "/iˈluːsɪdeɪt/", "pos": "v.", "meaning": "闡明, 說明", "level": "blue", "phrases": ["elucidate a point", "clearly elucidate"], "synonyms": ["explain", "clarify"], "antonyms": ["confuse", "obscure"], "example": "Could you please elucidate your earlier statement regarding the proposed budget for next year's marketing campaign?"},
        {"word": "Elude", "phonetic": "/iˈluːd/", "pos": "v.", "meaning": "逃避, 避開, 使困惑", "level": "blue", "phrases": ["elude capture", "elude understanding"], "synonyms": ["escape", "evade"], "antonyms": [], "example": "A permanent solution to the recurring technical issues has so far managed to elude our engineering team."},
        {"word": "Elusive", "phonetic": "/iˈluːsɪv/", "pos": "adj.", "meaning": "難找的, 難以實現的, 難懂的", "level": "blue", "phrases": ["elusive target", "remain elusive"], "synonyms": ["evasive", "slippery"], "antonyms": [], "example": "Consistent profitability in the volatile emerging markets has proven to be elusive for many international firms."},
        {"word": "Embargo", "phonetic": "/ɪmˈbɑːrɡoʊ/", "pos": "n./v.", "meaning": "禁運, 禁止, 封港", "level": "blue", "phrases": ["trade embargo", "lift an embargo"], "synonyms": ["ban", "prohibition"], "antonyms": [], "example": "The international community decided to lift the trade embargo following the signing of the peace treaty."},
        {"word": "Embark", "phonetic": "/ɪmˈbɑːrk/", "pos": "v.", "meaning": "著手, 開始, 上船/飛機", "level": "blue", "phrases": ["embark on a project", "embark on a journey"], "synonyms": ["commence", "undertake"], "antonyms": ["conclude", "finish"], "example": "The organization is about to embark on a major fundraising campaign to support local education programs."},
        {"word": "Embarrass", "phonetic": "/ɪmˈbærəs/", "pos": "v.", "meaning": "使尷尬, 使困窘", "level": "blue", "phrases": ["embarrass someone", "deeply embarrassed"], "synonyms": ["humiliate", "shame"], "antonyms": [], "example": "The spokesperson was deeply embarrassed when she was unable to answer basic questions about the firm's finances."},
        {"word": "Embassy", "phonetic": "/ˈembəsi/", "pos": "n.", "meaning": "大使館, 大使館全體人員", "level": "blue", "phrases": ["foreign embassy", "visit the embassy"], "synonyms": [], "antonyms": [], "example": "The trade delegation visited the national embassy to discuss potential investment opportunities in the region."},
        {"word": "Embed", "phonetic": "/ɪmˈbed/", "pos": "v.", "meaning": "嵌入, 埋置, 派遣(記者)", "level": "blue", "phrases": ["embedded system", "embed a video"], "synonyms": ["insert", "fix"], "antonyms": [], "example": "The new security feature is embedded directly into the smartphone's hardware for maximum protection."},
        {"word": "Embody", "phonetic": "/ɪmˈbɑːdi/", "pos": "v.", "meaning": "體現, 使具體化, 包含", "level": "blue", "phrases": ["embody the values", "embody in a plan"], "synonyms": ["personify", "represent"], "antonyms": [], "example": "The new office building was designed to embody the company's commitment to innovation and sustainability."},
        {"word": "Embrace", "phonetic": "/ɪmˈbreɪs/", "pos": "v.", "meaning": "擁抱, 欣然接受, 包含", "level": "blue", "phrases": ["embrace change", "eagerly embrace"], "synonyms": ["accept", "adopt", "include"], "antonyms": ["reject", "refuse"], "example": "Successful businesses are those that are willing to embrace new technologies and adapt to changing market trends."},
        {"word": "Emerge", "phonetic": "/iˈmɜːrdʒ/", "pos": "v.", "meaning": "浮現, 出現, 暴露", "level": "blue", "phrases": ["emerge from a crisis", "new trends emerge"], "synonyms": ["appear", "arise"], "antonyms": ["disappear", "vanish"], "example": "Several promising new startups have emerged in the local technology sector over the past few years."},
        {"word": "Emergence", "phonetic": "/iˈmɜːrdʒəns/", "pos": "n.", "meaning": "出現, 興起", "level": "blue", "phrases": ["emergence of technology", "rapid emergence"], "synonyms": ["arrival", "advent"], "antonyms": ["disappearance"], "example": "The rapid emergence of artificial intelligence is transforming the way many businesses operate worldwide."},
        {"word": "Emergency", "phonetic": "/iˈmɜːrdʒənsi/", "pos": "n./adj.", "meaning": "緊急情況, 緊急的", "level": "blue", "phrases": ["emergency exit", "in case of emergency"], "synonyms": ["crisis", "exigency"], "antonyms": [], "example": "All employees are required to participate in a mandatory safety drill to prepare for any workplace emergency."},
        {"word": "Eminent", "phonetic": "/ˈemɪnənt/", "pos": "adj.", "meaning": "著名的, 卓越的", "level": "blue", "phrases": ["eminent scientist", "eminent business leader"], "synonyms": ["distinguished", "prominent"], "antonyms": ["obscure", "unknown"], "example": "An eminent professor from the university was invited to give a keynote speech at the international conference."},
        {"word": "Emission", "phonetic": "/iˈmɪʃn/", "pos": "n.", "meaning": "排放, 排放物", "level": "blue", "phrases": ["carbon emissions", "emission standards"], "synonyms": ["discharge", "release"], "antonyms": [], "example": "The firm is investing in new technology to reduce its annual carbon emissions and environmental impact."},
        {"word": "Emit", "phonetic": "/iˈmɪt/", "pos": "v.", "meaning": "排放, 散發", "level": "blue", "phrases": ["emit light", "emit gases"], "synonyms": ["release", "discharge"], "antonyms": ["absorb"], "example": "The new manufacturing plant is designed to emit zero hazardous waste into the local environment."},
        {"word": "Emotion", "phonetic": "/ɪˈmoʊʃn/", "pos": "n.", "meaning": "情感, 情緒", "level": "blue", "phrases": ["show emotion", "mixed emotions"], "synonyms": ["feeling", "sentiment"], "antonyms": [], "example": "The outgoing CEO spoke with visible emotion during his final address to the company's employees."},
        {"word": "Emotional", "phonetic": "/ɪˈmoʊʃənl/", "pos": "adj.", "meaning": "情感的, 情緒化的", "level": "blue", "phrases": ["emotional intelligence", "become emotional"], "synonyms": ["sentimental", "passionate"], "antonyms": ["unemotional", "cold"], "example": "Emotional intelligence is increasingly being recognized as an essential skill for effective leadership in the workplace."},
        {"word": "Emphasize", "phonetic": "/ˈemfəsaɪz/", "pos": "v.", "meaning": "強調, 重視", "level": "blue", "phrases": ["heavily emphasize", "emphasize the point"], "synonyms": ["stress", "highlight"], "antonyms": ["ignore", "neglect"], "example": "Management continues to emphasize the importance of workplace safety and adherence to all protocols."},
        {"word": "Emphatic", "phonetic": "/ɪmˈfætɪk/", "pos": "adj.", "meaning": "強調的, 堅決的", "level": "blue", "phrases": ["emphatic denial", "be emphatic"], "synonyms": ["forceful", "firm"], "antonyms": ["hesitant", "weak"], "example": "The company issued an emphatic denial of the rumors regarding a potential takeover by its main competitor."},
        {"word": "Empire", "phonetic": "/ˈempaɪər/", "pos": "n.", "meaning": "帝國, 大企業", "level": "blue", "phrases": ["business empire", "build an empire"], "synonyms": ["domain", "kingdom"], "antonyms": [], "example": "Over the past three decades, the founder has built a massive business empire spanning several industries."},
        {"word": "Empirical", "phonetic": "/ɪmˈpɪrɪkl/", "pos": "adj.", "meaning": "憑經驗的, 實證的", "level": "blue", "phrases": ["empirical evidence", "empirical study"], "synonyms": ["experimental", "factual"], "antonyms": ["theoretical"], "example": "The committee is looking for more empirical evidence of market demand before approving the expansion plan."},
        {"word": "Employ", "phonetic": "/ɪmˈplɔɪ/", "pos": "v.", "meaning": "雇用, 運用", "level": "blue", "phrases": ["employ staff", "employ a strategy"], "synonyms": ["hire", "utilize"], "antonyms": ["dismiss", "fire"], "example": "The firm plans to employ twenty new software developers to help manage the increased workload next year."},
        {"word": "Employee", "phonetic": "/ɪmˈplɔɪiː/", "pos": "n.", "meaning": "雇員, 員工", "level": "blue", "phrases": ["valued employee", "full-time employee"], "synonyms": ["worker", "staff"], "antonyms": ["employer"], "example": "Improving employee morale and retention is a top priority for the human resources department this year."},
        {"word": "Employer", "phonetic": "/ɪmˈplɔɪər/", "pos": "n.", "meaning": "雇主, 老闆", "level": "blue", "phrases": ["major employer", "prospective employer"], "synonyms": ["boss", "owner"], "antonyms": ["employee"], "example": "The company is one of the largest employers in the region, providing jobs for over five thousand people."},
        {"word": "Employment", "phonetic": "/ɪmˈplɔɪmənt/", "pos": "n.", "meaning": "雇用, 工作", "level": "blue", "phrases": ["full-time employment", "employment contract"], "synonyms": ["work", "job"], "antonyms": ["unemployment"], "example": "Please review the terms of your employment contract carefully before providing your authorized signature."},
        {"word": "Empower", "phonetic": "/ɪmˈpaʊər/", "pos": "v.", "meaning": "授權, 使能夠", "level": "blue", "phrases": ["empower employees", "be empowered to"], "synonyms": ["authorize", "enable"], "antonyms": ["hinder"], "example": "The new management style is designed to empower employees to make decisions and take ownership of their work."},
        {"word": "Empowerment", "phonetic": "/ɪmˈpaʊərmənt/", "pos": "n.", "meaning": "授權, 自主權", "level": "blue", "phrases": ["employee empowerment", "show empowerment"], "synonyms": ["authorization"], "antonyms": [], "example": "Employee empowerment is a key component of our corporate culture and contributes to overall productivity."},
        {"word": "Emulate", "phonetic": "/ˈemjuleɪt/", "pos": "v.", "meaning": "模仿, 效法, 仿真", "level": "blue", "phrases": ["emulate success", "try to emulate"], "synonyms": ["imitate", "copy"], "antonyms": [], "example": "Many young entrepreneurs try to emulate the success of the tech giant's founder and CEO."},
        {"word": "Enable", "phonetic": "/ɪˈneɪbl/", "pos": "v.", "meaning": "使能夠, 使可行", "level": "blue", "phrases": ["enable a feature", "enable someone to"], "synonyms": ["allow", "facilitate"], "antonyms": ["disable", "prevent"], "example": "The new software update will enable regional offices to access the central database directly and securely."},
        {"word": "Enact", "phonetic": "/ɪˈnækt/", "pos": "v.", "meaning": "制定(法律), 通過, 扮演", "level": "blue", "phrases": ["enact a law", "enact a policy"], "synonyms": ["pass", "establish"], "antonyms": ["repeal", "revoke"], "example": "The government is planning to enact several new laws to protect consumer rights in the digital market."},
        {"word": "Enactment", "phonetic": "/ɪˈnæktmənt/", "pos": "n.", "meaning": "制定, 通過, 法律", "level": "blue", "phrases": ["enactment of a law", "legislative enactment"], "synonyms": ["establishment"], "antonyms": ["repeal"], "example": "The enactment of the new trade agreement is expected to lead to a significant increase in international sales."},
        {"word": "Encapsulate", "phonetic": "/ɪnˈkæpsjuleɪt/", "pos": "v.", "meaning": "封裝, 概括", "level": "blue", "phrases": ["encapsulate the vision", "fully encapsulate"], "synonyms": ["summarize", "outline"], "antonyms": [], "example": "The executive summary should encapsulate all the key findings and recommendations from the final report."},
        {"word": "Encase", "phonetic": "/ɪnˈkeɪs/", "pos": "v.", "meaning": "包圍, 把...裝入箱內", "level": "blue", "phrases": ["encased in plastic", "fully encase"], "synonyms": ["enclose", "surround"], "antonyms": [], "example": "The delicate laboratory equipment was encased in high-quality protective foam for international shipping."},
        {"word": "Enchant", "phonetic": "/ɪnˈtʃænt/", "pos": "v.", "meaning": "使著迷, 吸引", "level": "blue", "phrases": ["be enchanted by"], "synonyms": ["captivate", "attract"], "antonyms": ["repel"], "example": "The international dignitaries were enchanted by the high-quality hospitality provided during the gala dinner."},
        {"word": "Enclose", "phonetic": "/ɪnˈkloʊz/", "pos": "v.", "meaning": "隨函附上, 圍住", "level": "blue", "phrases": ["please find enclosed", "enclose a check"], "synonyms": ["attach", "insert"], "antonyms": [], "example": "I enclose a copy of the signed service agreement for your personal and professional records."},
        {"word": "Enclosure", "phonetic": "/ɪnˈkloʊʒər/", "pos": "n.", "meaning": "附件, 圍住, 圍欄", "level": "blue", "phrases": ["list of enclosures", "secure enclosure"], "synonyms": ["attachment"], "antonyms": [], "example": "Please ensure that all items listed in the enclosure section of the letter are present before shipping."},
        {"word": "Encode", "phonetic": "/ɪnˈkoʊd/", "pos": "v.", "meaning": "編碼, 把...譯成密碼", "level": "blue", "phrases": ["encode information", "digitally encode"], "synonyms": ["encrypt"], "antonyms": ["decode"], "example": "All customer data is digitally encoded to ensure the security and privacy of our online users."},
        {"word": "Encompass", "phonetic": "/ɪnˈkʌmpəs/", "pos": "v.", "meaning": "包含, 圍繞", "level": "blue", "phrases": ["encompass a range of", "broadly encompass"], "synonyms": ["include", "contain", "comprise"], "antonyms": ["exclude"], "example": "The new training program is designed to encompass all aspects of modern marketing and distribution."},
        {"word": "Encounter", "phonetic": "/ɪnˈkaʊntər/", "pos": "v./n.", "meaning": "遭遇, 遇到, 偶然相遇", "level": "blue", "phrases": ["encounter difficulties", "chance encounter"], "synonyms": ["face", "meet"], "antonyms": ["avoid"], "example": "We encountered several unforeseen technical issues during the implementation of the new software system."},
        {"word": "Encourage", "phonetic": "/ɪnˈkɜːrdʒ/", "pos": "v.", "meaning": "鼓勵, 促進", "level": "blue", "phrases": ["encourage innovation", "strongly encourage"], "synonyms": ["support", "promote"], "antonyms": ["discourage", "hinder"], "example": "Management plans to introduce new incentives to encourage staff to contribute their innovative ideas."},
        {"word": "Encouragement", "phonetic": "/ɪnˈkɜːrdʒmənt/", "pos": "n.", "meaning": "鼓勵", "level": "blue", "phrases": ["give encouragement", "word of encouragement"], "synonyms": ["support"], "antonyms": ["discouragement"], "example": "The supervisor provided words of encouragement to the team during the difficult phase of the project."},
        {"word": "Encroach", "phonetic": "/ɪnˈkroʊtʃ/", "pos": "v.", "meaning": "侵入, 侵佔, 蠶食", "level": "blue", "phrases": ["encroach on rights", "encroach upon"], "synonyms": ["infringe", "intrude"], "antonyms": [], "example": "The firm was accused of attempting to encroach on its competitor's territory by using aggressive marketing tactics."},
        {"word": "Encrypt", "phonetic": "/ɪnˈkrɪpt/", "pos": "v.", "meaning": "加密", "level": "blue", "phrases": ["encrypt a file", "heavily encrypt"], "synonyms": ["encode"], "antonyms": ["decrypt"], "example": "Please ensure that you encrypt all confidential documents before sending them via external email servers."},
        {"word": "Encryption", "phonetic": "/ɪnˈkrɪpʃn/", "pos": "n.", "meaning": "加密", "level": "blue", "phrases": ["data encryption", "encryption software"], "synonyms": ["encoding"], "antonyms": ["decryption"], "example": "Advanced data encryption techniques are used to protect our customers' personal and financial information."},
        {"word": "Encumber", "phonetic": "/ɪnˈkʌmbər/", "pos": "v.", "meaning": "妨礙, 拖累, 負擔", "level": "blue", "phrases": ["be encumbered with debt", "unencumbered property"], "synonyms": ["hinder", "burden"], "antonyms": ["aid", "assist"], "example": "The firm is heavily encumbered with debt, making it difficult to secure funding for new research projects."},
        {"word": "Endanger", "phonetic": "/ɪnˈdeɪndʒər/", "pos": "v.", "meaning": "危及, 使遭受危險", "level": "blue", "phrases": ["endanger lives", "seriously endanger"], "synonyms": ["jeopardize", "threaten"], "antonyms": ["protect", "safeguard"], "example": "Failure to follow the mandatory safety protocols could seriously endanger the health of all warehouse staff."},
        {"word": "Endeavor", "phonetic": "/ɪnˈdevər/", "pos": "v./n.", "meaning": "努力, 盡力", "level": "blue", "phrases": ["scientific endeavor", "make every endeavor"], "synonyms": ["strive", "attempt"], "antonyms": [], "example": "We will endeavor to resolve the outstanding technical issues as quickly and efficiently as possible."},
        {"word": "Endorse", "phonetic": "/ɪnˈdɔːrs/", "pos": "v.", "meaning": "背書, 贊同, 代言", "level": "blue", "phrases": ["endorse a check", "celebrity endorsement"], "synonyms": ["approve", "sanction", "support"], "antonyms": ["oppose", "criticize"], "example": "The famous athlete was hired to endorse the company's new line of professional sportswear."},
        {"word": "Endorsement", "phonetic": "/ɪnˈdɔːrsmənt/", "pos": "n.", "meaning": "贊同, 認可, 背書, 代言", "level": "blue", "phrases": ["official endorsement", "product endorsement"], "synonyms": ["approval", "support"], "antonyms": ["disapproval"], "example": "The new fitness app received an official endorsement from several prominent health and wellness organizations."},
        {"word": "Endow", "phonetic": "/ɪnˈdaʊ/", "pos": "v.", "meaning": "捐贈, 資助, 賦予", "level": "blue", "phrases": ["endow a chair", "endowed with"], "synonyms": ["fund", "finance"], "antonyms": [], "example": "The wealthy benefactor decided to endow a new research chair at the university's school of finance."},
        {"word": "Endowment", "phonetic": "/ɪnˈdaʊmənt/", "pos": "n.", "meaning": "捐贈, 基金, 天賦", "level": "blue", "phrases": ["university endowment", "endowment insurance"], "synonyms": ["grant", "gift"], "antonyms": [], "example": "The university's endowment has grown significantly over the past decade thanks to several large private donations."},
        {"word": "Endurable", "phonetic": "/ɪnˈdʊrəbl/", "pos": "adj.", "meaning": "可忍受的, 耐用的", "level": "blue", "phrases": ["endurable pain", "highly endurable"], "synonyms": ["bearable", "durable"], "antonyms": ["unbearable"], "example": "The new outdoor furniture is made from highly endurable materials that can resist extreme weather conditions."},
        {"word": "Endurance", "phonetic": "/ɪnˈdʊrəns/", "pos": "n.", "meaning": "耐力, 持久", "level": "blue", "phrases": ["test of endurance", "powers of endurance"], "synonyms": ["stamina", "persistence"], "antonyms": ["weakness"], "example": "The long-distance marathon is a true test of physical and mental endurance for all participating athletes."},
        {"word": "Endure", "phonetic": "/ɪnˈdʊr/", "pos": "v.", "meaning": "忍受, 持久", "level": "blue", "phrases": ["endure a crisis", "endure for years"], "synonyms": ["bear", "last", "persist"], "antonyms": ["fade", "vanish"], "example": "The company has managed to endure several economic downturns over its long fifty-year history."},
        {"word": "Energetic", "phonetic": "/ˌenərˈdʒetɪk/", "pos": "adj.", "meaning": "精力充沛的, 積極的", "level": "blue", "phrases": ["energetic leader", "highly energetic"], "synonyms": ["active", "dynamic"], "antonyms": ["lazy", "lethargic"], "example": "We are looking for an energetic and motivated individual to manage our local customer support team."},
        {"word": "Energy", "phonetic": "/ˈenərdʒi/", "pos": "n.", "meaning": "能量, 精力, 能源", "level": "blue", "phrases": ["renewable energy", "save energy"], "synonyms": ["power", "vigor"], "antonyms": ["lethargy"], "example": "The firm is committed to switching all its manufacturing operations to renewable energy sources by 2030."},
        {"word": "Enforce", "phonetic": "/ɪnˈfɔːrs/", "pos": "v.", "meaning": "執行, 強制, 實施", "level": "blue", "phrases": ["enforce regulations", "strictly enforced"], "synonyms": ["implement", "administer"], "antonyms": ["disregard", "ignore"], "example": "Security guards are responsible for enforcing the building's access and safety rules at all times."},
        {"word": "Enforcement", "phonetic": "/ɪnˈfɔːrsmənt/", "pos": "n.", "meaning": "執行, 強制實施", "level": "blue", "phrases": ["law enforcement", "strict enforcement"], "synonyms": ["implementation"], "antonyms": ["negligence"], "example": "The strict enforcement of environmental regulations has led to a significant decrease in local water pollution."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
