import json

# 第 751-800 個高品質單字對應表 (金色等級)
enriched_data_gold_16 = {
    "even though": {"phonetic": "/ˈiːvn ðoʊ/", "pos": "conj.", "meaning": "雖然；儘管", "phrases": [], "synonyms": ["although", "despite the fact that"], "antonyms": [], "example": "Even though the weather was bad, the outdoor concert was a great success."},
    "conductor": {"phonetic": "/kənˈdʌktər/", "pos": "n.", "meaning": "指揮家；導體；列車長", "phrases": ["orchestra conductor"], "synonyms": ["leader", "director"], "antonyms": [], "example": "The world-famous conductor will lead the symphony orchestra tomorrow night."},
    "whereas": {"phonetic": "/ˌwerˈæz/", "pos": "conj.", "meaning": "然而；反之", "phrases": [], "synonyms": ["while", "on the other hand"], "antonyms": [], "example": "Some people prefer to work in the office, whereas others find it easier to work from home."},
    "stop by": {"phonetic": "/stɑːp baɪ/", "pos": "v. phr.", "meaning": "順道拜訪", "phrases": [], "synonyms": ["drop by", "visit"], "antonyms": [], "example": "Please stop by my office this afternoon if you have a moment to discuss the project."},
    "aroma": {"phonetic": "/əˈroʊmə/", "pos": "n.", "meaning": "香氣；芬芳", "phrases": ["pleasant aroma"], "synonyms": ["scent", "fragrance"], "antonyms": ["stench", "odor"], "example": "The delicious aroma of freshly brewed coffee filled the entire office building."},
    "ruins": {"phonetic": "/ˈruːɪnz/", "pos": "n.", "meaning": "廢墟；遺跡(複數)", "phrases": ["ancient ruins"], "synonyms": ["remains", "wreckage"], "antonyms": [], "example": "Many tourists visit the island to see the ancient ruins of the roman temples."},
    "trail": {"phonetic": "/treɪl/", "pos": "n./v.", "meaning": "小徑；蹤跡；追蹤", "phrases": ["hiking trail", "audit trail"], "synonyms": ["path", "track"], "antonyms": [], "example": "The hiking trail leads through the forest and offers some spectacular views of the valley."},
    "preservative": {"phonetic": "/prɪˈzɜːrvətɪv/", "pos": "n./adj.", "meaning": "防腐劑；保存的", "phrases": ["no artificial preservatives"], "synonyms": [], "antonyms": [], "example": "These snacks contain no artificial preservatives and are made from all-natural ingredients."},
    "ground floor": {"phonetic": "/ɡraʊnd flɔːr/", "pos": "n. phr.", "meaning": "一樓；地面層", "phrases": ["located on the ground floor"], "synonyms": ["first floor"], "antonyms": [], "example": "The reception desk is located on the ground floor, right next to the main entrance."},
    "portrait": {"phonetic": "/ˈpɔːrtrət/", "pos": "n.", "meaning": "肖像；畫像；描繪", "phrases": ["family portrait", "portrait mode"], "synonyms": ["picture", "image"], "antonyms": ["landscape"], "example": "A large portrait of the company's founder hangs in the main conference room."},
    "refreshment": {"phonetic": "/rɪˈfreʃmənt/", "pos": "n.", "meaning": "茶點；點心；恢復活力", "phrases": ["light refreshments"], "synonyms": ["snacks", "drinks"], "antonyms": [], "example": "Light refreshments will be served during the break in the afternoon session."},
    "a preview": {"phonetic": "/ə ˈpriːvjuː/", "pos": "n. phr.", "meaning": "預覽；預演", "phrases": ["sneak preview"], "synonyms": ["advance showing"], "antonyms": [], "example": "The company gave us a special preview of its new product line before the official launch."},
    "hike": {"phonetic": "/haɪk/", "pos": "n./v.", "meaning": "遠足；大幅增加(價格/利率)", "phrases": ["price hike", "interest rate hike"], "synonyms": ["walk", "increase", "rise"], "antonyms": ["decrease", "cut"], "example": "The central bank decided to hike interest rates to combat rising inflation in the country."},
    "warranty": {"phonetic": "/ˈwɔːrənti/", "pos": "n.", "meaning": "保固；保證", "phrases": ["under warranty", "extended warranty"], "synonyms": ["guarantee"], "antonyms": [], "example": "The laptop is still under warranty, so the repair should be free of charge."},
    "declination": {"phonetic": "/ˌdeklɪˈneɪʃn/", "pos": "n.", "meaning": "傾斜；衰微；拒絕", "phrases": [], "synonyms": ["decline", "refusal"], "antonyms": ["acceptance"], "example": "We received his declination of the job offer due to personal reasons."},
    "class action": {"phonetic": "/klæs ˈækʃn/", "pos": "n. phr.", "meaning": "集體訴訟", "phrases": ["class action lawsuit"], "synonyms": [], "antonyms": [], "example": "Several former employees have filed a class action lawsuit against the company for unpaid overtime."},
    "lobby": {"phonetic": "/ˈlɑːbi/", "pos": "n./v.", "meaning": "大廳；遊說", "phrases": ["hotel lobby", "lobby group"], "synonyms": ["foyer", "influence"], "antonyms": [], "example": "Please meet me in the hotel lobby at 8 AM so we can go to the conference together."},
    "agency": {"phonetic": "/ˈeɪdʒənsi/", "pos": "n.", "meaning": "代理機構；行政機構", "phrases": ["advertising agency", "travel agency"], "synonyms": ["firm", "organization"], "antonyms": [], "example": "The company hired a marketing agency to help launch its new product in Asia."},
    "agent": {"phonetic": "/ˈeɪdʒənt/", "pos": "n.", "meaning": "代理人；經紀人", "phrases": ["real estate agent", "secret agent"], "synonyms": ["representative", "broker"], "antonyms": [], "example": "You should contact your insurance agent if you have any questions about your coverage."},
    "remittance": {"phonetic": "/rɪˈmɪtns/", "pos": "n.", "meaning": "匯款", "phrases": ["electronic remittance"], "synonyms": ["payment", "transfer"], "antonyms": [], "example": "The company requires a copy of the bank remittance before it can dispatch the order."},
    "streamline": {"phonetic": "/ˈstriːmlaɪn/", "pos": "v.", "meaning": "簡化；效率化；使流線型", "phrases": ["streamline operations"], "synonyms": ["simplify", "optimize"], "antonyms": ["complicate"], "example": "The new manager is planning to streamline the production process to reduce waste and save time."},
    "clue to": {"phonetic": "/kluː tuː/", "pos": "n. phr.", "meaning": "點出...的線索；...的提示", "phrases": [], "synonyms": ["hint", "indication"], "antonyms": [], "example": "The researchers hope the new data will provide a clue to the cause of the disease."},
    "take into account": {"phonetic": "/teɪk ˈɪntuː əˈkaʊnt/", "pos": "v. phr.", "meaning": "考量；考慮到", "phrases": [], "synonyms": ["consider", "bear in mind"], "antonyms": ["ignore", "overlook"], "example": "The board will take into account all relevant factors before making a final decision."},
    "be in the way": {"phonetic": "/bi ɪn ðə weɪ/", "pos": "phr.", "meaning": "擋路；礙事", "phrases": [], "synonyms": ["obstruct"], "antonyms": [], "example": "Could you please move those boxes? They are in the way of the exit."},
    "as a whole": {"phonetic": "/æz ə hoʊl/", "pos": "phr.", "meaning": "整體而言", "phrases": [], "synonyms": ["entirely", "altogether"], "antonyms": ["partially"], "example": "The proposal was supported by the department as a whole, despite some minor concerns."},
    "in an attempt to V": {"phonetic": "/ɪn ən əˈtempt tuː/", "pos": "phr.", "meaning": "試圖做某事", "phrases": [], "synonyms": ["trying to"], "antonyms": [], "example": "The company lowered its prices in an attempt to attract more customers during the sale."},
    "alert": {"phonetic": "/əˈlɜːrt/", "pos": "n./v./adj.", "meaning": "警報；警示；警覺的", "phrases": ["security alert", "stay alert"], "synonyms": ["warning", "vigilant"], "antonyms": ["inattentive"], "example": "Employees should be alert to any suspicious activity in the office building."},
    "throughout": {"phonetic": "/θruːˈaʊt/", "pos": "prep./adv.", "meaning": "貫穿；遍及；自始至終", "phrases": ["throughout the year", "throughout the building"], "synonyms": ["during", "everywhere in"], "antonyms": [], "example": "The company has maintained a high level of quality throughout its thirty-year history."},
    "sentimental": {"phonetic": "/ˌsentɪˈmentl/", "pos": "adj.", "meaning": "多愁善感的；感傷的；有紀念意義的", "phrases": ["sentimental value"], "synonyms": ["emotional"], "antonyms": ["pragmatic"], "example": "The old watch has no financial worth, but it has great sentimental value to him."},
    "complementary": {"phonetic": "/ˌkɑːmplɪˈmentəri/", "pos": "adj.", "meaning": "互補的", "phrases": ["complementary colors"], "synonyms": ["matching"], "antonyms": [], "example": "The two managers have complementary skills, which makes them a very effective team."},
    "supplementary": {"phonetic": "/ˌsʌplɪˈmentəri/", "pos": "adj.", "meaning": "補充的；追加的", "phrases": ["supplementary information"], "synonyms": ["additional", "extra"], "antonyms": [], "example": "You can find supplementary materials for the course on the university's website."},
    "state-of-the-art": {"phonetic": "/steɪt əv ðə ɑːrt/", "pos": "adj.", "meaning": "最先進的", "phrases": ["state-of-the-art facility"], "synonyms": ["cutting-edge", "modern"], "antonyms": ["obsolete", "outdated"], "example": "The new research center is equipped with state-of-the-art technology and instruments."},
    "amicably": {"phonetic": "/ˈæmɪkəbli/", "pos": "adv.", "meaning": "友好地；和睦地", "phrases": ["settle amicably"], "synonyms": ["harmoniously"], "antonyms": ["hostilely"], "example": "The two companies decided to settle their dispute amicably without going to court."},
    "handsomely": {"phonetic": "/ˈhænsəmli/", "pos": "adv.", "meaning": "大方地；慷慨地；漂亮地", "phrases": ["pay handsomely"], "synonyms": ["generously", "liberally"], "antonyms": [], "example": "The successful project manager was handsomely rewarded with a large bonus at the end of the year."},
    "pick up": {"phonetic": "/pɪk ʌp/", "pos": "v. phr.", "meaning": "撿起；接送；獲得；改善", "phrases": ["pick up the phone", "pick up passengers"], "synonyms": ["collect", "improve"], "antonyms": ["drop off"], "example": "The economy is starting to pick up after several months of slow growth."},
    "challenging": {"phonetic": "/ˈtʃælɪndʒɪŋ/", "pos": "adj.", "meaning": "具挑戰性的", "phrases": ["challenging task"], "synonyms": ["demanding", "difficult"], "antonyms": ["easy", "simple"], "example": "The new project is very challenging, but it provides a great opportunity for learning."},
    "challenged": {"phonetic": "/ˈtʃælɪndʒd/", "pos": "adj./v. (past)", "meaning": "受到挑戰的；殘障的", "phrases": ["physically challenged"], "synonyms": [], "antonyms": [], "example": "The manager's decision was challenged by several members of the board during the meeting."},
    "smooth": {"phonetic": "/smuːð/", "pos": "adj./v.", "meaning": "平滑的；順利的；使平滑", "phrases": ["smooth transition"], "synonyms": ["level", "easy", "polished"], "antonyms": ["rough", "bumpy"], "example": "We are working hard to ensure a smooth transition to the new computer system."},
    "smoothed": {"phonetic": "/smuːðd/", "pos": "v. (past)", "meaning": "弄平；使順利", "phrases": ["smoothed over"], "synonyms": [], "antonyms": [], "example": "He managed to smooth over the disagreement between the two colleagues."},
    "outlook": {"phonetic": "/ˈaʊtlʊk/", "pos": "n.", "meaning": "展望；觀點", "phrases": ["economic outlook", "positive outlook"], "synonyms": ["prospect", "viewpoint"], "antonyms": [], "example": "The economic outlook for the next year remains positive despite current challenges."},
    "ubiquitious": {"word": "ubiquitous", "phonetic": "/juːˈbɪkwɪtəs/", "pos": "adj.", "meaning": "無所不在的；普遍的", "phrases": [], "synonyms": ["omnipresent", "pervasive"], "antonyms": ["rare", "scarce"], "example": "Smartphone technology has become ubiquitous in almost all parts of the world today."},
    "leading": {"phonetic": "/ˈliːdɪŋ/", "pos": "adj.", "meaning": "領先的；首要的", "phrases": ["leading manufacturer", "leading role"], "synonyms": ["foremost", "primary", "top"], "antonyms": ["following"], "example": "The company is a leading manufacturer of high-quality medical equipment."},
    "troublesome": {"phonetic": "/ˈtrʌblsəm/", "pos": "adj.", "meaning": "麻煩的；令人苦惱的", "phrases": ["troublesome issue"], "synonyms": ["bothersome", "annoying"], "antonyms": ["convenient", "easy"], "example": "The technical problem with the server proved to be quite troublesome for the IT team."},
    "malicious": {"phonetic": "/məˈlɪʃəs/", "pos": "adj.", "meaning": "惡意的", "phrases": ["malicious software", "malicious intent"], "synonyms": ["spiteful", "malevolent"], "antonyms": ["benevolent", "kind"], "example": "The security system is designed to detect and block any malicious attacks on the network."},
    "emerging market": {"phonetic": "/iˈmɜːrdʒɪŋ ˈmɑːrkɪt/", "pos": "n. phr.", "meaning": "新興市場", "phrases": ["invest in emerging markets"], "synonyms": [], "antonyms": ["developed market"], "example": "The company is planning to expand its operations into emerging markets in Southeast Asia."},
    "poised": {"phonetic": "/pɔɪzd/", "pos": "adj.", "meaning": "準備就緒的；沉著的", "phrases": ["poised to do something"], "synonyms": ["ready", "prepared"], "antonyms": [], "example": "The company is poised to become the market leader in renewable energy technology."},
    "thorough": {"phonetic": "/ˈθɜːroʊ/", "pos": "adj.", "meaning": "徹底的；周密的", "phrases": ["thorough investigation"], "synonyms": ["complete", "comprehensive"], "antonyms": ["superficial", "incomplete"], "example": "The auditors conducted a thorough review of all the company's financial records."},
    "mild": {"phonetic": "/maɪld/", "pos": "adj.", "meaning": "溫和的；輕微的", "phrases": ["mild weather", "mild symptoms"], "synonyms": ["gentle", "slight"], "antonyms": ["severe", "harsh", "intense"], "example": "The city enjoys a mild climate during the winter months, with very little snow."},
    "blockbuster": {"phonetic": "/ˈblɑːkbʌstər/", "pos": "n.", "meaning": "大片；暢銷作品", "phrases": ["blockbuster movie"], "synonyms": ["hit", "success"], "antonyms": ["flop"], "example": "The new action movie is expected to be a global blockbuster this summer."},
    "panel": {"phonetic": "/ˈpænl/", "pos": "n.", "meaning": "面板；專題討論小組", "phrases": ["control panel", "panel of experts", "solar panel"], "synonyms": ["board", "group"], "antonyms": [], "example": "A panel of experts was invited to discuss the future of digital technology at the conference."}
}

with open('data_gold.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_gold_16:
        update_info = enriched_data_gold_16[word].copy()
        if 'word' in update_info:
            item['word'] = update_info.pop('word')
        item.update(update_info)

with open('data_gold.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修金色等級第 751-800 個單字。")
