import json
import os

def update_vocab():
    # 第十二批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Abundant", "phonetic": "/əˈbʌndənt/", "pos": "adj.", "meaning": "豐富的, 充裕的", "level": "blue", "phrases": ["abundant resources", "abundant evidence"], "synonyms": ["plentiful", "ample"], "antonyms": ["scarce", "sparse"], "example": "The region is known for its abundant natural resources, making it a prime location for manufacturing."},
        {"word": "Accelerate", "phonetic": "/əkˈseləreɪt/", "pos": "v.", "meaning": "加速, 促進", "level": "blue", "phrases": ["accelerate growth", "accelerate the process"], "synonyms": ["hasten", "expedite"], "antonyms": ["decelerate", "slow down"], "example": "The company plans to accelerate its digital transformation to keep up with the evolving market trends."},
        {"word": "Accommodating", "phonetic": "/əˈkɑːmədeɪtɪŋ/", "pos": "adj.", "meaning": "樂於助人的, 親切的, 肯通融的", "level": "blue", "phrases": ["accommodating staff", "highly accommodating"], "synonyms": ["helpful", "obliging"], "antonyms": ["uncooperative"], "example": "The hotel staff were extremely accommodating, fulfilling all our requests during the international conference."},
        {"word": "Accomplishment", "phonetic": "/əˈkʌmplɪʃmənt/", "pos": "n.", "meaning": "成就, 完成", "level": "blue", "phrases": ["great accomplishment", "sense of accomplishment"], "synonyms": ["achievement", "attainment"], "antonyms": ["failure"], "example": "Winning the 'Exporter of the Year' award was a significant accomplishment for our small marketing firm."},
        {"word": "Accordance", "phonetic": "/əˈkɔːrdns/", "pos": "n.", "meaning": "一致, 符合", "level": "blue", "phrases": ["in accordance with", "strict accordance"], "synonyms": ["agreement", "conformity"], "antonyms": ["disagreement"], "example": "All financial statements must be prepared in strict accordance with the national accounting standards."},
        {"word": "Accordingly", "phonetic": "/əˈkɔːrdɪŋli/", "pos": "adv.", "meaning": "相應地, 因此", "level": "blue", "phrases": ["act accordingly", "adjust accordingly"], "synonyms": ["consequently", "therefore"], "antonyms": [], "example": "The market conditions have changed, and we must adjust our investment strategy accordingly."},
        {"word": "Accountability", "phonetic": "/əˌkaʊntəˈbɪləti/", "pos": "n.", "meaning": "問責性, 責任", "level": "blue", "phrases": ["public accountability", "hold someone accountable"], "synonyms": ["responsibility", "liability"], "antonyms": [], "example": "Greater transparency and accountability are needed to restore public trust in the financial sector."},
        {"word": "Accumulation", "phonetic": "/əˌkjuːmjəˈleɪʃn/", "pos": "n.", "meaning": "累積, 堆積物", "level": "blue", "phrases": ["capital accumulation", "accumulation of wealth"], "synonyms": ["collection", "buildup"], "antonyms": ["dissemination"], "example": "The slow accumulation of debt over several years has left the company in a difficult financial position."},
        {"word": "Accurate", "phonetic": "/ˈækjərət/", "pos": "adj.", "meaning": "準確的, 精確的", "level": "blue", "phrases": ["accurate data", "highly accurate"], "synonyms": ["precise", "correct"], "antonyms": ["inaccurate", "wrong"], "example": "It is essential to provide accurate financial data to the board of directors for the annual review."},
        {"word": "Accustomed", "phonetic": "/əˈkʌstəmd/", "pos": "adj.", "meaning": "習慣的, 通常的", "level": "blue", "phrases": ["accustomed to", "become accustomed"], "synonyms": ["used", "familiar"], "antonyms": ["unaccustomed"], "example": "New employees often take a few weeks to become accustomed to the company's internal software systems."},
        {"word": "Achievement", "phonetic": "/əˈtʃiːvmənt/", "pos": "n.", "meaning": "成就, 達成", "level": "blue", "phrases": ["outstanding achievement", "academic achievement"], "synonyms": ["accomplishment", "success"], "antonyms": ["failure"], "example": "The successful launch of the new product line is a major achievement for the entire development team."},
        {"word": "Acknowledgement", "phonetic": "/əkˈnɑːlɪdʒmənt/", "pos": "n.", "meaning": "確認, 承認, 感謝", "level": "blue", "phrases": ["written acknowledgement", "formal acknowledgement"], "synonyms": ["recognition", "confirmation"], "antonyms": ["denial"], "example": "We have sent an acknowledgement of your application and will contact you regarding an interview shortly."},
        {"word": "Acquire", "phonetic": "/əˈkwaɪər/", "pos": "v.", "meaning": "獲得, 學到, 收購", "level": "blue", "phrases": ["acquire a company", "acquire skills"], "synonyms": ["obtain", "gain", "purchase"], "antonyms": ["lose", "forfeit"], "example": "The firm is looking to acquire several smaller competitors to expand its presence in the domestic market."},
        {"word": "Actionable", "phonetic": "/ˈækʃənəbl/", "pos": "adj.", "meaning": "可執行的, 可控告的", "level": "blue", "phrases": ["actionable advice", "actionable insights"], "synonyms": ["practical", "usable"], "antonyms": ["theoretical"], "example": "The consultant provided us with several actionable insights that we can implement immediately to improve efficiency."},
        {"word": "Adaptability", "phonetic": "/əˌdæptəˈbɪləti/", "pos": "n.", "meaning": "適應性, 順應性", "level": "blue", "phrases": ["great adaptability", "show adaptability"], "synonyms": ["flexibility", "versatility"], "antonyms": ["rigidity"], "example": "Adaptability is a key trait that we look for when hiring managers for our international branches."},
        {"word": "Adjacent", "phonetic": "/əˈdʒeɪsnt/", "pos": "adj.", "meaning": "鄰近的, 毗連的", "level": "blue", "phrases": ["adjacent building", "adjacent to"], "synonyms": ["neighboring", "adjoining"], "antonyms": ["distant", "remote"], "example": "The new distribution center is located in the building adjacent to our main manufacturing facility."},
        {"word": "Adjustment", "phonetic": "/əˈdʒʌstmənt/", "pos": "n.", "meaning": "調整, 調節", "level": "blue", "phrases": ["make adjustments", "price adjustment"], "synonyms": ["alteration", "modification"], "antonyms": [], "example": "We may need to make several adjustments to the budget based on the latest quarterly sales figures."},
        {"word": "Administrative", "phonetic": "/ədˈmɪnɪstreɪtɪv/", "pos": "adj.", "meaning": "行政的, 管理的", "level": "blue", "phrases": ["administrative assistant", "administrative costs"], "synonyms": ["executive", "managerial"], "antonyms": [], "example": "The new software is designed to streamline various administrative tasks and reduce the workload for office staff."},
        {"word": "Admiration", "phonetic": "/ˌædməˈreɪʃn/", "pos": "n.", "meaning": "欽佩, 讚賞", "level": "blue", "phrases": ["express admiration", "mutual admiration"], "synonyms": ["respect", "esteem"], "antonyms": ["contempt", "disdain"], "example": "The CEO expressed his deep admiration for the team's hard work during the successful merger process."},
        {"word": "Adoption", "phonetic": "/əˈdɑːpʃn/", "pos": "n.", "meaning": "採用, 收養", "level": "blue", "phrases": ["adoption of technology", "early adoption"], "synonyms": ["acceptance", "implementation"], "antonyms": ["rejection"], "example": "The widespread adoption of cloud computing has revolutionized the way many businesses store and manage their data."},
        {"word": "Advancement", "phonetic": "/ədˈvænsmənt/", "pos": "n.", "meaning": "進步, 晉升, 發展", "level": "blue", "phrases": ["career advancement", "technological advancement"], "synonyms": ["progress", "promotion"], "antonyms": ["regression", "decline"], "example": "The company offers numerous opportunities for career advancement to its most dedicated and high-performing employees."},
        {"word": "Advantageous", "phonetic": "/ˌædvənˈteɪdʒəs/", "pos": "adj.", "meaning": "有利的, 有益的", "level": "blue", "phrases": ["advantageous position", "mutually advantageous"], "synonyms": ["beneficial", "favorable"], "antonyms": ["disadvantageous", "harmful"], "example": "The new trade agreement provides several advantageous terms for local manufacturers looking to export their goods."},
        {"word": "Advertiser", "phonetic": "/ˈædvərtaɪzər/", "pos": "n.", "meaning": "廣告商, 刊登廣告者", "level": "blue", "phrases": ["major advertiser", "online advertiser"], "synonyms": [], "antonyms": [], "example": "The magazine attracts many high-end advertisers from the luxury goods and fashion industries."},
        {"word": "Advisable", "phonetic": "/ədˈvaɪzəbl/", "pos": "adj.", "meaning": "明智的, 可取的", "level": "blue", "phrases": ["highly advisable", "it is advisable to"], "synonyms": ["prudent", "sensible"], "antonyms": ["inadvisable", "unwise"], "example": "It is advisable to consult with a legal expert before signing any long-term service agreements."},
        {"word": "Advocacy", "phonetic": "/ˈædvəkəsi/", "pos": "n.", "meaning": "擁護, 提倡, 辯護", "level": "blue", "phrases": ["consumer advocacy", "public advocacy"], "synonyms": ["support", "promotion"], "antonyms": ["opposition"], "example": "The organization's advocacy for stronger environmental regulations has gained significant public support recently."},
        {"word": "Affordable", "phonetic": "/əˈfɔːrdəbl/", "pos": "adj.", "meaning": "負擔得起的, 便宜的", "level": "blue", "phrases": ["affordable housing", "affordable prices"], "synonyms": ["inexpensive", "reasonable"], "antonyms": ["expensive", "unaffordable"], "example": "Our goal is to provide high-quality and affordable solar energy solutions for residential customers."},
        {"word": "Agenda", "phonetic": "/əˈdʒendə/", "pos": "n.", "meaning": "議程, 待辦事項", "level": "blue", "phrases": ["hidden agenda", "top of the agenda"], "synonyms": ["schedule", "timetable"], "antonyms": [], "example": "The main item on today's agenda is the discussion of the proposed budget for the upcoming fiscal year."},
        {"word": "Aggregate", "phonetic": "/ˈæɡrɪɡət/", "pos": "adj./n./v.", "meaning": "總計的, 集合體, 合計", "level": "blue", "phrases": ["aggregate demand", "in the aggregate"], "synonyms": ["total", "cumulative"], "antonyms": ["individual", "separate"], "example": "The aggregate value of all projects completed this year has exceeded our initial annual targets."},
        {"word": "Agreement", "phonetic": "/əˈɡriːmənt/", "pos": "n.", "meaning": "協定, 同意, 合約", "level": "blue", "phrases": ["reach an agreement", "sign an agreement"], "synonyms": ["contract", "accord", "treaty"], "antonyms": ["disagreement", "dispute"], "example": "The two companies have finally reached a formal agreement on the terms of the strategic partnership."},
        {"word": "Agriculture", "phonetic": "/ˈæɡrɪkʌltʃər/", "pos": "n.", "meaning": "農業", "level": "blue", "phrases": ["sustainable agriculture", "modern agriculture"], "synonyms": ["farming"], "antonyms": [], "example": "Technological advancements in agriculture have led to a significant increase in crop yields worldwide."},
        {"word": "Alignment", "phonetic": "/əˈlaɪnmənt/", "pos": "n.", "meaning": "結盟, 對準, 協調", "level": "blue", "phrases": ["strategic alignment", "in alignment with"], "synonyms": ["arrangement", "alliance"], "antonyms": ["misalignment"], "example": "We need to ensure that our marketing strategy is in full alignment with the company's overall business goals."},
        {"word": "Allocation", "phonetic": "/ˌæləˈkeɪʃn/", "pos": "n.", "meaning": "分配, 撥款", "level": "blue", "phrases": ["resource allocation", "budget allocation"], "synonyms": ["distribution", "assignment"], "antonyms": [], "example": "The efficient allocation of resources is essential for the successful completion of the infrastructure project."},
        {"word": "Allowance", "phonetic": "/əˈlaʊəns/", "pos": "n.", "meaning": "津貼, 限額, 容忍", "level": "blue", "phrases": ["baggage allowance", "travel allowance"], "synonyms": ["grant", "stipend"], "antonyms": [], "example": "The company provides a monthly travel allowance to employees who have to commute from outside the city."},
        {"word": "Ambassador", "phonetic": "/æmˈbæsədər/", "pos": "n.", "meaning": "大使, 使者", "level": "blue", "phrases": ["brand ambassador", "goodwill ambassador"], "synonyms": ["representative", "envoy"], "antonyms": [], "example": "The famous athlete was appointed as a brand ambassador for the new line of sportswear."},
        {"word": "Ambiguity", "phonetic": "/ˌæmbɪˈɡjuːəti/", "pos": "n.", "meaning": "含糊, 歧義", "level": "blue", "phrases": ["avoid ambiguity", "legal ambiguity"], "synonyms": ["vagueness", "uncertainty"], "antonyms": ["clarity", "precision"], "example": "The contract was redrafted to remove any potential ambiguity regarding the termination clauses."},
        {"word": "Ambitious", "phonetic": "/æmˈbɪʃəs/", "pos": "adj.", "meaning": "有野心的, 抱負不凡的", "level": "blue", "phrases": ["ambitious plan", "ambitious person"], "synonyms": ["aspiring", "determined"], "antonyms": ["unambitious", "lazy"], "example": "The CEO presented an ambitious plan to double the company's annual revenue within the next five years."},
        {"word": "Amendment", "phonetic": "/əˈmendmənt/", "pos": "n.", "meaning": "修正, 修正案", "level": "blue", "phrases": ["constitutional amendment", "propose an amendment"], "synonyms": ["revision", "alteration"], "antonyms": [], "example": "Several amendments were made to the initial proposal to address the concerns raised by the shareholders."},
        {"word": "Amicable", "phonetic": "/ˈæmɪkəbl/", "pos": "adj.", "meaning": "友好的, 和睦的", "level": "blue", "phrases": ["amicable settlement", "amicable relationship"], "synonyms": ["friendly", "harmonious"], "antonyms": ["hostile", "antagonistic"], "example": "The two competing firms managed to reach an amicable settlement after months of legal disputes."},
        {"word": "Analysis", "phonetic": "/əˈnæləsɪs/", "pos": "n.", "meaning": "分析", "level": "blue", "phrases": ["data analysis", "market analysis"], "synonyms": ["examination", "investigation"], "antonyms": [], "example": "A thorough analysis of the latest consumer spending habits is included in the quarterly marketing report."},
        {"word": "Analytic", "phonetic": "/ˌænəˈlɪtɪk/", "pos": "adj.", "meaning": "分析的, 解析的", "level": "blue", "phrases": ["analytic skills", "analytic approach"], "synonyms": ["logical", "systematic"], "antonyms": [], "example": "Strong analytic skills are essential for candidates applying for the senior financial analyst position."},
        {"word": "Anchor", "phonetic": "/ˈæŋkər/", "pos": "n./v.", "meaning": "錨, 核心, 固定, 擔任主持人", "level": "blue", "phrases": ["anchor store", "anchor the program"], "synonyms": ["support", "fix"], "antonyms": [], "example": "The large department store serves as the anchor for the entire shopping mall, attracting thousands of visitors."},
        {"word": "Annex", "phonetic": "/ˈæneks/", "pos": "n./v.", "meaning": "附件, 增建部分, 併吞", "level": "blue", "phrases": ["office annex", "annex a document"], "synonyms": ["attachment", "addition"], "antonyms": [], "example": "The marketing team has moved their operations to the new office annex across the street."},
        {"word": "Announcement", "phonetic": "/əˈnaʊnsmənt/", "pos": "n.", "meaning": "公告, 宣布", "level": "blue", "phrases": ["official announcement", "make an announcement"], "synonyms": ["notification", "declaration"], "antonyms": [], "example": "The company is expected to make an official announcement regarding the merger early tomorrow morning."},
        {"word": "Anonymous", "phonetic": "/əˈnɑːnɪməs/", "pos": "adj.", "meaning": "匿名的", "level": "blue", "phrases": ["anonymous donor", "remain anonymous"], "synonyms": ["unnamed", "unidentified"], "antonyms": ["named", "known"], "example": "An anonymous donor provided a multi-million dollar grant to support the university's research facility."},
        {"word": "Anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "pos": "v.", "meaning": "預期, 預料, 提前行動", "level": "blue", "phrases": ["anticipate problems", "eagerly anticipate"], "synonyms": ["expect", "foresee"], "antonyms": [], "example": "We anticipate a significant increase in demand for our services during the upcoming holiday season."},
        {"word": "Apparent", "phonetic": "/əˈpærənt/", "pos": "adj.", "meaning": "明顯的, 表面上的", "level": "blue", "phrases": ["become apparent", "for no apparent reason"], "synonyms": ["obvious", "evident"], "antonyms": ["hidden", "obscure"], "example": "It soon became apparent that the initial sales projections were far too optimistic for the current market."},
        {"word": "Appeal", "phonetic": "/əˈpiːl/", "pos": "n./v.", "meaning": "吸引力, 呼籲, 上訴", "level": "blue", "phrases": ["broad appeal", "file an appeal"], "synonyms": ["attraction", "request"], "antonyms": ["repulsion"], "example": "The new marketing campaign is designed to appeal to a younger and more tech-savvy demographic."},
        {"word": "Applicant", "phonetic": "/ˈæplɪkənt/", "pos": "n.", "meaning": "申請人, 應徵者", "level": "blue", "phrases": ["job applicant", "successful applicant"], "synonyms": ["candidate", "bidder"], "antonyms": [], "example": "All qualified applicants will be contacted for an initial phone interview within the next two weeks."},
        {"word": "Application", "phonetic": "/ˌæplɪˈkeɪʃn/", "pos": "n.", "meaning": "申請, 應用, 應用程式", "level": "blue", "phrases": ["job application", "software application"], "synonyms": ["request", "utilization"], "antonyms": [], "example": "Please submit your completed application form along with a copy of your resume by the end of the month."},
        {"word": "Appointment", "phonetic": "/əˈpɔɪntmənt/", "pos": "n.", "meaning": "預約, 任命, 職位", "level": "blue", "phrases": ["make an appointment", "official appointment"], "synonyms": ["meeting", "nomination"], "antonyms": [], "example": "I would like to make an appointment to discuss the latest project proposal with the department head."},
        {"word": "Appraisal", "phonetic": "/əˈpreɪzl/", "pos": "n.", "meaning": "評價, 考核, 估價", "level": "blue", "phrases": ["performance appraisal", "property appraisal"], "synonyms": ["assessment", "evaluation"], "antonyms": [], "example": "The annual performance appraisal is a key component of our professional development program for all staff."},
        {"word": "Appreciative", "phonetic": "/əˈpriːʃieɪtɪv/", "pos": "adj.", "meaning": "感激的, 有欣賞力的", "level": "blue", "phrases": ["highly appreciative", "appreciative audience"], "synonyms": ["grateful", "thankful"], "antonyms": ["ungrateful"], "example": "The company is highly appreciative of your years of dedicated service and hard work."},
        {"word": "Apprentice", "phonetic": "/əˈprentɪs/", "pos": "n./v.", "meaning": "學徒, 實習生, 當學徒", "level": "blue", "phrases": ["unskilled apprentice", "apprentice program"], "synonyms": ["trainee", "learner"], "antonyms": ["expert", "master"], "example": "The vocational school offers an apprentice program that combines classroom learning with on-the-job training."},
        {"word": "Approach", "phonetic": "/əˈproʊtʃ/", "pos": "v./n.", "meaning": "接近, 方法, 著手處理", "level": "blue", "phrases": ["innovative approach", "cautious approach"], "synonyms": ["method", "strategy", "access"], "antonyms": ["avoidance"], "example": "We need to adopt a more proactive approach to customer service to improve overall client satisfaction."},
        {"word": "Appropriate", "phonetic": "/əˈproʊpriət/", "pos": "adj./v.", "meaning": "適當的, 撥款, 盜用", "level": "blue", "phrases": ["appropriate action", "appropriate funds"], "synonyms": ["suitable", "proper"], "antonyms": ["inappropriate", "unsuitable"], "example": "The board will take appropriate action once the full internal investigation has been completed."},
        {"word": "Approval", "phonetic": "/əˈpruːvl/", "pos": "n.", "meaning": "批准, 同意", "level": "blue", "phrases": ["official approval", "give approval"], "synonyms": ["authorization", "sanction"], "antonyms": ["disapproval", "rejection"], "example": "The proposed project is still subject to official approval from the regional planning committee."},
        {"word": "Approximate", "phonetic": "/əˈprɑːksɪmət/", "pos": "adj./v.", "meaning": "大約的, 接近", "level": "blue", "phrases": ["approximate cost", "approximate time"], "synonyms": ["rough", "estimated"], "antonyms": ["exact", "precise"], "example": "The approximate cost of the new manufacturing facility is estimated to be around ten million dollars."},
        {"word": "Arbitrate", "phonetic": "/ˈɑːrbɪtreɪt/", "pos": "v.", "meaning": "仲裁, 調停", "level": "blue", "phrases": ["arbitrate a dispute", "arbitrate between"], "synonyms": ["mediate", "settle"], "antonyms": [], "example": "An independent legal expert was hired to arbitrate the contract dispute between the two companies."},
        {"word": "Architecture", "phonetic": "/ˈɑːrkɪtektʃər/", "pos": "n.", "meaning": "建築學, 結構", "level": "blue", "phrases": ["modern architecture", "system architecture"], "synonyms": ["design", "structure"], "antonyms": [], "example": "The new headquarters building is considered a masterpiece of modern sustainable architecture."},
        {"word": "Arouse", "phonetic": "/əˈraʊz/", "pos": "v.", "meaning": "喚起, 激起", "level": "blue", "phrases": ["arouse interest", "arouse suspicion"], "synonyms": ["stimulate", "provoke"], "antonyms": ["calm", "soothe"], "example": "The innovative features of the new smartphone have aroused significant interest among tech enthusiasts."},
        {"word": "Arrangement", "phonetic": "/əˈreɪndʒmənt/", "pos": "n.", "meaning": "安排, 整理, 協議", "level": "blue", "phrases": ["travel arrangements", "make arrangements"], "synonyms": ["organization", "agreement"], "antonyms": ["disarray"], "example": "The conference organizers are making travel and accommodation arrangements for all the keynote speakers."},
        {"word": "Arrival", "phonetic": "/əˈraɪvl/", "pos": "n.", "meaning": "到達, 到達者, 到貨", "level": "blue", "phrases": ["late arrival", "arrival time"], "synonyms": ["advent", "entry"], "antonyms": ["departure"], "example": "We are expecting the arrival of a large shipment of raw materials from our overseas supplier tomorrow."},
        {"word": "Arrogant", "phonetic": "/ˈærəɡənt/", "pos": "adj.", "meaning": "傲慢的, 自大的", "level": "blue", "phrases": ["arrogant behavior", "overly arrogant"], "synonyms": ["conceited", "haughty"], "antonyms": ["humble", "modest"], "example": "His arrogant attitude towards junior staff members led to several complaints to the HR department."},
        {"word": "Articulate", "phonetic": "/ɑːrˈtɪkjuleɪt/", "pos": "adj./v.", "meaning": "口齒伶俐的, 清晰表達", "level": "blue", "phrases": ["articulate speaker", "articulate the vision"], "synonyms": ["eloquent", "clear"], "antonyms": ["inarticulate", "vague"], "example": "The candidate was very articulate during the interview, clearly expressing her vision for the department's growth."},
        {"word": "Artificial", "phonetic": "/ˌɑːrtɪˈfɪʃl/", "pos": "adj.", "meaning": "人造的, 虛假的", "level": "blue", "phrases": ["artificial intelligence", "artificial flavoring"], "synonyms": ["synthetic", "man-made"], "antonyms": ["natural", "genuine"], "example": "The company is investing heavily in the development of artificial intelligence for customer service automation."},
        {"word": "Aspect", "phonetic": "/ˈæspekt/", "pos": "n.", "meaning": "方面, 面貌, 朝向", "level": "blue", "phrases": ["key aspect", "every aspect of"], "synonyms": ["facet", "feature"], "antonyms": [], "example": "Every aspect of the project was carefully scrutinized by the internal quality control team."},
        {"word": "Aspiration", "phonetic": "/ˌæspəˈreɪʃn/", "pos": "n.", "meaning": "抱負, 渴望", "level": "blue", "phrases": ["career aspirations", "high aspirations"], "synonyms": ["ambition", "goal"], "antonyms": [], "example": "The company's mentorship program is designed to help young professionals achieve their long-term career aspirations."},
        {"word": "Assemble", "phonetic": "/əˈsembl/", "pos": "v.", "meaning": "組裝, 集合, 聚集", "level": "blue", "phrases": ["assemble a team", "easily assembled"], "synonyms": ["gather", "collect", "build"], "antonyms": ["disassemble", "scatter"], "example": "The marketing manager is trying to assemble a team of experts for the upcoming international campaign."},
        {"word": "Assembly", "phonetic": "/əˈsembli/", "pos": "n.", "meaning": "集會, 組裝, 立法機構", "level": "blue", "phrases": ["assembly line", "general assembly"], "synonyms": ["gathering", "construction"], "antonyms": [], "example": "The new manufacturing plant features a fully automated assembly line for increased production efficiency."},
        {"word": "Assertive", "phonetic": "/əˈsɜːrtɪv/", "pos": "adj.", "meaning": "果斷的, 自信的, 斷斷的", "level": "blue", "phrases": ["assertive behavior", "be assertive"], "synonyms": ["confident", "decisive"], "antonyms": ["passive", "timid"], "example": "An assertive management style is often needed to resolve conflicts effectively within a large team."},
        {"word": "Assessment", "phonetic": "/əˈsesmənt/", "pos": "n.", "meaning": "評估, 評價, 估價", "level": "blue", "phrases": ["risk assessment", "needs assessment"], "synonyms": ["evaluation", "appraisal"], "antonyms": [], "example": "The consultant provided a detailed assessment of the company's current digital marketing capabilities."},
        {"word": "Asset", "phonetic": "/ˈæset/", "pos": "n.", "meaning": "資產, 優點", "level": "blue", "phrases": ["valuable asset", "fixed assets"], "synonyms": ["property", "resource"], "antonyms": ["liability"], "example": "The new marketing director has proven to be a valuable asset to the company's expansion efforts."},
        {"word": "Assignment", "phonetic": "/əˈsaɪnmənt/", "pos": "n.", "meaning": "任務, 指派, 分配", "level": "blue", "phrases": ["overseas assignment", "special assignment"], "synonyms": ["task", "duty"], "antonyms": [], "example": "He was given a special overseas assignment to oversee the establishment of our new branch in London."},
        {"word": "Assistance", "phonetic": "/əˈsɪstəns/", "pos": "n.", "meaning": "協助, 幫助", "level": "blue", "phrases": ["financial assistance", "technical assistance"], "synonyms": ["help", "support"], "antonyms": ["hinderance", "obstruction"], "example": "The government is providing financial assistance to small businesses affected by the recent economic downturn."},
        {"word": "Assistant", "phonetic": "/əˈsɪstənt/", "pos": "n./adj.", "meaning": "助手, 助理", "level": "blue", "phrases": ["administrative assistant", "research assistant"], "synonyms": ["helper", "aide"], "antonyms": [], "example": "The department head is looking for a new administrative assistant to manage her busy schedule."},
        {"word": "Associate", "phonetic": "/əˈsoʊʃieɪt/", "pos": "v./n./adj.", "meaning": "聯想, 結合, 夥伴, 副的", "level": "blue", "phrases": ["business associate", "associate director"], "synonyms": ["partner", "colleague", "connect"], "antonyms": ["separate"], "example": "He invited several business associates to a private dinner to discuss the terms of the new joint venture."},
        {"word": "Association", "phonetic": "/əˌsoʊʃiˈeɪʃn/", "pos": "n.", "meaning": "協會, 關聯", "level": "blue", "phrases": ["professional association", "trade association"], "synonyms": ["organization", "connection"], "antonyms": [], "example": "Membership in the national trade association provides several benefits, including access to exclusive market research."},
        {"word": "Assume", "phonetic": "/əˈsuːm/", "pos": "v.", "meaning": "假設, 承擔(責任), 呈現(特徵)", "level": "blue", "phrases": ["assume responsibility", "assume the role"], "synonyms": ["presume", "undertake"], "antonyms": [], "example": "The new manager will assume responsibility for the entire department starting next Monday."},
        {"word": "Assumption", "phonetic": "/əˈsʌmpʃn/", "pos": "n.", "meaning": "假設, 承擔, 奪取", "level": "blue", "phrases": ["basic assumption", "on the assumption that"], "synonyms": ["premise", "presupposition"], "antonyms": [], "example": "The initial budget was based on the assumption that market conditions would remain stable throughout the year."},
        {"word": "Assurance", "phonetic": "/əˈʃʊrəns/", "pos": "n.", "meaning": "保證, 信心, 保險", "level": "blue", "phrases": ["quality assurance", "give assurance"], "synonyms": ["guarantee", "confidence"], "antonyms": ["uncertainty"], "example": "The CEO gave his personal assurance that the company would resolve the technical issues by the end of the day."},
        {"word": "Astonishing", "phonetic": "/əˈstɑːnɪʃɪŋ/", "pos": "adj.", "meaning": "令人驚訝的, 驚人的", "level": "blue", "phrases": ["astonishing growth", "astonishing results"], "synonyms": ["amazing", "surprising"], "antonyms": ["ordinary", "predictable"], "example": "The company has seen astonishing growth in its overseas sales over the past three fiscal years."},
        {"word": "Attachment", "phonetic": "/əˈtætʃmənt/", "pos": "n.", "meaning": "附件, 連結, 依戀", "level": "blue", "phrases": ["email attachment", "file attachment"], "synonyms": ["appendix", "connection"], "antonyms": ["detachment"], "example": "Please find the requested financial reports in the email attachment sent earlier this morning."},
        {"word": "Attainment", "phonetic": "/əˈteɪnmənt/", "pos": "n.", "meaning": "達成, 獲得, 造詣", "level": "blue", "phrases": ["educational attainment", "goal attainment"], "synonyms": ["achievement", "accomplishment"], "antonyms": ["failure"], "example": "The attainment of our quarterly sales targets is essential for the company's overall financial health."},
        {"word": "Attendance", "phonetic": "/əˈtendəns/", "pos": "n.", "meaning": "出席, 出席人數", "level": "blue", "phrases": ["record attendance", "attendance record"], "synonyms": ["presence"], "antonyms": ["absence"], "example": "Attendance at the annual safety training workshop is mandatory for all warehouse and factory staff."},
        {"word": "Attention", "phonetic": "/əˈtenʃn/", "pos": "n.", "meaning": "注意力, 關注, 照料", "level": "blue", "phrases": ["pay attention", "draw attention to"], "synonyms": ["concentration", "notice"], "antonyms": ["inattention", "neglect"], "example": "Management is paying close attention to the latest market developments following the trade policy changes."},
        {"word": "Attire", "phonetic": "/əˈtaɪər/", "pos": "n.", "meaning": "服裝, 衣著", "level": "blue", "phrases": ["formal attire", "business attire"], "synonyms": ["clothing", "garments"], "antonyms": [], "example": "All employees are expected to wear professional business attire when meeting with clients at the headquarters."},
        {"word": "Attribute", "phonetic": "/əˈtrɪbjuːt/", "pos": "v./n.", "meaning": "歸因於, 把...歸功於, 特質", "level": "blue", "phrases": ["attribute to", "key attribute"], "synonyms": ["ascribe", "feature", "quality"], "antonyms": [], "example": "The marketing team attributes the campaign's success to their innovative use of social media platforms."},
        {"word": "Auction", "phonetic": "/ˈɔːkʃn/", "pos": "n./v.", "meaning": "拍賣", "level": "blue", "phrases": ["public auction", "online auction"], "synonyms": [], "antonyms": [], "example": "The seized assets of the bankrupt company will be sold at a public auction later this month."},
        {"word": "Audience", "phonetic": "/ˈɔːdiəns/", "pos": "n.", "meaning": "聽眾, 觀眾, 特定族群", "level": "blue", "phrases": ["target audience", "wide audience"], "synonyms": ["spectators", "listeners"], "antonyms": [], "example": "Our new advertising campaign is specifically designed to reach a younger and more diverse audience."},
        {"word": "Audit", "phonetic": "/ˈɔːdɪt/", "pos": "n./v.", "meaning": "審計, 查帳", "level": "blue", "phrases": ["internal audit", "financial audit"], "synonyms": ["inspection", "scrutiny"], "antonyms": [], "example": "The company undergoes an independent financial audit every year to ensure transparency and compliance."},
        {"word": "Authentic", "phonetic": "/ɔːˈθentɪk/", "pos": "adj.", "meaning": "真實的, 正宗的, 可信的", "level": "blue", "phrases": ["authentic product", "authentic experience"], "synonyms": ["genuine", "real"], "antonyms": ["fake", "counterfeit"], "example": "Customers are willing to pay a premium for authentic hand-crafted goods made from sustainable materials."},
        {"word": "Authority", "phonetic": "/əˈθɔːrəti/", "pos": "n.", "meaning": "權威, 當局, 授權", "level": "blue", "phrases": ["local authority", "position of authority"], "synonyms": ["power", "jurisdiction"], "antonyms": [], "example": "The regional planning authority has approved our proposal for the construction of the new distribution center."},
        {"word": "Authorization", "phonetic": "/ˌɔːθərəˈzeɪʃn/", "pos": "n.", "meaning": "授權, 批准, 許可證", "level": "blue", "phrases": ["official authorization", "require authorization"], "synonyms": ["approval", "permission"], "antonyms": ["prohibition"], "example": "Please ensure that you have obtained official authorization before making any large equipment purchases."},
        {"word": "Automate", "phonetic": "/ˈɔːtəmeɪt/", "pos": "v.", "meaning": "使自動化", "level": "blue", "phrases": ["fully automate", "automate the process"], "synonyms": [], "antonyms": ["manual"], "example": "The organization plans to automate several manual processes to increase operational efficiency and reduce costs."},
        {"word": "Auxiliary", "phonetic": "/ɔːɡˈzɪliəri/", "pos": "adj./n.", "meaning": "輔助的, 備用的", "level": "blue", "phrases": ["auxiliary power", "auxiliary staff"], "synonyms": ["supplementary", "additional"], "antonyms": ["primary", "main"], "example": "The facility is equipped with an auxiliary generator to ensure continued operations during power outages."},
        {"word": "Availability", "phonetic": "/əˌveɪləˈbɪləti/", "pos": "n.", "meaning": "可獲得性, 可利用性, 有空與否", "level": "blue", "phrases": ["check availability", "limited availability"], "synonyms": ["accessibility"], "antonyms": ["unavailability"], "example": "Please check the availability of the conference room before scheduling the team meeting."},
        {"word": "Avenue", "phonetic": "/ˈævənjuː/", "pos": "n.", "meaning": "大道, 途徑, 手段", "level": "blue", "phrases": ["explore all avenues", "main avenue"], "synonyms": ["path", "way"], "antonyms": [], "example": "The board is exploring all possible avenues for expansion into the emerging markets of Southeast Asia."},
        {"word": "Avert", "phonetic": "/əˈvɜːrt/", "pos": "v.", "meaning": "防止, 避免, 轉向", "level": "blue", "phrases": ["avert a crisis", "avert one's eyes"], "synonyms": ["prevent", "avoid"], "antonyms": [], "example": "The timely intervention of the central bank helped to avert a major financial crisis in the region."},
        {"word": "Awkward", "phonetic": "/ˈɔːkwərd/", "pos": "adj.", "meaning": "尷尬的, 笨拙的, 棘手的", "level": "blue", "phrases": ["awkward silence", "awkward situation"], "synonyms": ["clumsy", "difficult"], "antonyms": ["graceful", "easy"], "example": "The sudden cancellation of the joint venture led to several awkward meetings with our international partners."},
        {"word": "Backdrop", "phonetic": "/ˈbækdrɑːp/", "pos": "n.", "meaning": "背景, 背景幕", "level": "blue", "phrases": ["against the backdrop of", "scenic backdrop"], "synonyms": ["background", "setting"], "antonyms": [], "example": "The new marketing campaign was launched against the backdrop of an improving global economic situation."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
