import json

# 第 101-150 個高品質單字對應表 (綠色等級)
enriched_data_3 = {
    "owe": {"phonetic": "/oʊ/", "pos": "v.", "meaning": "欠債；歸功於", "phrases": ["owe money", "owe success to"], "synonyms": ["be in debt"], "antonyms": [], "example": "The company still owes a significant amount of money to its suppliers."},
    "perceive": {"phonetic": "/pərˈsiːv/", "pos": "v.", "meaning": "察覺；理解", "phrases": ["perceive a change", "perceived value"], "synonyms": ["notice", "detect"], "antonyms": ["ignore"], "example": "The customers perceive the new product as being of higher quality."},
    "permeate": {"phonetic": "/ˈpɜːrmieɪt/", "pos": "v.", "meaning": "滲透；充滿", "phrases": ["permeate the market", "permeate throughout"], "synonyms": ["penetrate", "spread"], "antonyms": [], "example": "The new corporate culture has begun to permeate all levels of the organization."},
    "perpetuate": {"phonetic": "/pərˈpetʃueɪt/", "pos": "v.", "meaning": "使永恆；使持續", "phrases": ["perpetuate a myth", "perpetuate inequality"], "synonyms": ["continue", "preserve"], "antonyms": ["halt", "stop"], "example": "The current policies only serve to perpetuate the existing problems."},
    "place": {"phonetic": "/pleɪs/", "pos": "v./n.", "meaning": "放置；地點；下訂單", "phrases": ["place an order", "take place"], "synonyms": ["put", "location"], "antonyms": [], "example": "You can place an order for the new office furniture through our website."},
    "pleasure": {"phonetic": "/ˈpleʒər/", "pos": "n.", "meaning": "愉快；榮幸", "phrases": ["with pleasure", "take pleasure in"], "synonyms": ["delight", "satisfaction"], "antonyms": ["displeasure", "pain"], "example": "It is a great pleasure to welcome our guest speaker to the conference today."},
    "poll": {"phonetic": "/poʊl/", "pos": "n./v.", "meaning": "民意調查；投票", "phrases": ["opinion poll", "poll the public"], "synonyms": ["survey", "vote"], "antonyms": [], "example": "According to a recent opinion poll, most employees are happy with the new working hours."},
    "precede": {"phonetic": "/prɪˈsiːd/", "pos": "v.", "meaning": "在...之前", "phrases": ["precede the meeting", "preceding chapter"], "synonyms": ["come before", "lead"], "antonyms": ["follow", "succeed"], "example": "A brief introduction will precede the main presentation."},
    "preface": {"phonetic": "/ˈprefəs/", "pos": "n./v.", "meaning": "前言；序言", "phrases": ["author's preface", "preface with"], "synonyms": ["introduction", "prologue"], "antonyms": ["epilogue", "conclusion"], "example": "In the preface of the report, the author explains the purpose of the research."},
    "prefer": {"phonetic": "/prɪˈfɜːr/", "pos": "v.", "meaning": "更喜歡；偏好", "phrases": ["prefer A to B", "strongly prefer"], "synonyms": ["favor", "like better"], "antonyms": [], "example": "Many employees prefer to work from home at least two days a week."},
    "prejudice": {"phonetic": "/ˈpredʒədɪs/", "pos": "n./v.", "meaning": "偏見；成見", "phrases": ["without prejudice", "racial prejudice"], "synonyms": ["bias", "partiality"], "antonyms": ["fairness", "tolerance"], "example": "The company is committed to eliminating all forms of prejudice in the workplace."},
    "present": {"phonetic": "/ˈpreznt/", "pos": "v./adj./n.", "meaning": "呈現；禮物；出席的", "phrases": ["present a report", "at present"], "synonyms": ["show", "gift"], "antonyms": ["absent"], "example": "The marketing manager will present the annual sales report at the meeting."},
    "preserve": {"phonetic": "/prɪˈzɜːrv/", "pos": "v.", "meaning": "保存；維護", "phrases": ["preserve nature", "well-preserved"], "synonyms": ["maintain", "protect"], "antonyms": ["destroy", "damage"], "example": "We must take steps to preserve the historical integrity of the building."},
    "presume": {"phonetic": "/prɪˈzuːm/", "pos": "v.", "meaning": "假定；推定", "phrases": ["presume innocence", "presumably"], "synonyms": ["assume", "suppose"], "antonyms": [], "example": "I presume that the meeting will be held in the main conference room as usual."},
    "pretend": {"phonetic": "/prɪˈtend/", "pos": "v.", "meaning": "假裝", "phrases": ["pretend to be", "make believe"], "synonyms": ["feign", "fake"], "antonyms": [], "example": "He tried to pretend that he was not surprised by the sudden news."},
    "prevail": {"phonetic": "/prɪˈveɪl/", "pos": "v.", "meaning": "流行；佔優勢", "phrases": ["prevail over", "prevailing wind"], "synonyms": ["triumph", "predominate"], "antonyms": ["lose", "fail"], "example": "We hope that common sense will prevail and a strike will be avoided."},
    "privilege": {"phonetic": "/ˈprɪvəlɪdʒ/", "pos": "n.", "meaning": "特權；榮幸", "phrases": ["exclusive privilege", "have the privilege"], "synonyms": ["right", "advantage"], "antonyms": [], "example": "It is a privilege to work with such a talented team of professionals."},
    "proceed": {"phonetic": "/proʊˈsiːd/", "pos": "v.", "meaning": "繼續進行；著手", "phrases": ["proceed with", "proceed to the gate"], "synonyms": ["continue", "advance"], "antonyms": ["stop", "halt"], "example": "The board decided to proceed with the merger despite some initial concerns."},
    "process": {"phonetic": "/ˈprɑːses/", "pos": "n./v.", "meaning": "過程；處理", "phrases": ["application process", "process data"], "synonyms": ["procedure", "handle"], "antonyms": [], "example": "The recruitment process usually takes about four to six weeks to complete."},
    "procure": {"phonetic": "/prəˈkjʊr/", "pos": "v.", "meaning": "採購；獲得", "phrases": ["procure supplies", "procurement department"], "synonyms": ["acquire", "obtain"], "antonyms": [], "example": "The company needs to procure new raw materials for the production line."},
    "profuse": {"phonetic": "/prəˈfjuːs/", "pos": "adj.", "meaning": "大量的；豐富的", "phrases": ["profuse sweating", "profuse apologies"], "synonyms": ["abundant", "copious"], "antonyms": ["scarce", "limited"], "example": "The manager offered profuse apologies for the delay in processing the order."},
    "progress": {"phonetic": "/ˈprɑːɡres/", "pos": "n./v.", "meaning": "進展；進步", "phrases": ["make progress", "in progress"], "synonyms": ["advancement", "growth"], "antonyms": ["regression", "decline"], "example": "The project is making good progress and should be finished on schedule."},
    "prohibit": {"phonetic": "/proʊˈhɪbɪt/", "pos": "v.", "meaning": "禁止", "phrases": ["prohibit smoking", "strictly prohibited"], "synonyms": ["forbid", "ban"], "antonyms": ["allow", "permit"], "example": "The company's policy strictly prohibits the use of mobile phones in the factory area."},
    "purpose": {"phonetic": "/ˈpɜːrpəs/", "pos": "n.", "meaning": "目的；意圖", "phrases": ["on purpose", "for the purpose of"], "synonyms": ["goal", "aim"], "antonyms": [], "example": "The main purpose of the meeting is to discuss the budget for next year."},
    "pursue": {"phonetic": "/pərˈsuː/", "pos": "v.", "meaning": "追求；從事", "phrases": ["pursue a career", "pursue a goal"], "synonyms": ["follow", "seek"], "antonyms": ["abandon", "give up"], "example": "She decided to leave the company to pursue a career in international law."},
    "puzzle": {"phonetic": "/ˈpʌzl/", "pos": "n./v.", "meaning": "難題；使困惑", "phrases": ["solve a puzzle", "puzzling situation"], "synonyms": ["mystery", "confuse"], "antonyms": ["clarify", "explain"], "example": "The sudden drop in sales is a puzzle that the marketing team is trying to solve."},
    "quote": {"phonetic": "/kwoʊt/", "pos": "v./n.", "meaning": "報價；引用", "phrases": ["get a quote", "price quote"], "synonyms": ["estimate", "cite"], "antonyms": [], "example": "Could you please give me a quote for the cost of repairing the machine?"},
    "qualify": {"phonetic": "/ˈkwɑːlɪfaɪ/", "pos": "v.", "meaning": "取得資格；使合格", "phrases": ["qualify for", "highly qualified"], "synonyms": ["fit", "suit"], "antonyms": ["disqualify"], "example": "You need to have at least five years of experience to qualify for this position."},
    "realize": {"phonetic": "/ˈriːəlaɪz/", "pos": "v.", "meaning": "意識到；實現", "phrases": ["realize a dream", "fully realize"], "synonyms": ["understand", "achieve"], "antonyms": [], "example": "It took me a long time to realize how important this project really was."},
    "recognize": {"phonetic": "/ˈrekəɡnaɪz/", "pos": "v.", "meaning": "認出；承認", "phrases": ["recognize achievement", "easily recognizable"], "synonyms": ["identify", "acknowledge"], "antonyms": ["ignore"], "example": "The company presented him with an award to recognize his 20 years of service."},
    "recommend": {"phonetic": "/ˌrekəˈmend/", "pos": "v.", "meaning": "推薦；建議", "phrases": ["highly recommend", "recommendation letter"], "synonyms": ["suggest", "advise"], "antonyms": ["dissuade"], "example": "I would highly recommend this hotel to anyone visiting the city for business."},
    "rectify": {"phonetic": "/ˈrektɪfaɪ/", "pos": "v.", "meaning": "糾正；改正", "phrases": ["rectify a mistake", "rectify the situation"], "synonyms": ["correct", "remedy"], "antonyms": ["damage", "worsen"], "example": "We will take immediate action to rectify the error in your billing statement."},
    "regard": {"phonetic": "/rɪˈɡɑːrd/", "pos": "n./v.", "meaning": "看待；尊重", "phrases": ["with regard to", "high regard"], "synonyms": ["consideration", "respect"], "antonyms": ["contempt"], "example": "He is held in high regard by all his colleagues for his hard work and dedication."},
    "regard as": {"phonetic": "/rɪˈɡɑːrd æz/", "pos": "v.", "meaning": "視為...", "phrases": [], "synonyms": ["consider", "view as"], "antonyms": [], "example": "The new CEO is regarded as one of the most innovative leaders in the industry."},
    "in regard to": {"phonetic": "/ɪn rɪˈɡɑːrd tuː/", "pos": "prep.", "meaning": "關於...", "phrases": [], "synonyms": ["concerning", "about"], "antonyms": [], "example": "I am writing to you in regard to your recent inquiry about our new products."},
    "regress": {"phonetic": "/rɪˈɡres/", "pos": "v.", "meaning": "退步；倒退", "phrases": ["regress to", "economic regression"], "synonyms": ["backslide", "decline"], "antonyms": ["progress", "advance"], "example": "The company's performance began to regress after the departure of the manager."},
    "reinforce": {"phonetic": "/ˌriːɪnˈfɔːrs/", "pos": "v.", "meaning": "強化；加固", "phrases": ["reinforce the message", "reinforce a structure"], "synonyms": ["strengthen", "bolster"], "antonyms": ["weaken", "undermine"], "example": "The training session was designed to reinforce the importance of workplace safety."},
    "relate": {"phonetic": "/rɪˈleɪt/", "pos": "v.", "meaning": "有關聯；敘述", "phrases": ["relate to", "closely related"], "synonyms": ["connect", "link"], "antonyms": ["disconnect"], "example": "The new regulations relate to the disposal of hazardous industrial waste."},
    "relate with": {"phonetic": "/rɪˈleɪt wɪð/", "pos": "v.", "meaning": "與...相處/聯繫", "phrases": [], "synonyms": ["associate with"], "antonyms": [], "example": "It is important for managers to relate well with their team members."},
    "relocate": {"phonetic": "/ˌriːˈloʊkeɪt/", "pos": "v.", "meaning": "搬遷；遷移", "phrases": ["relocate an office", "relocation package"], "synonyms": ["move", "transfer"], "antonyms": ["stay"], "example": "The company decided to relocate its headquarters to a more central location."},
    "remain": {"phonetic": "/rɪˈmeɪn/", "pos": "v.", "meaning": "保持；遺留", "phrases": ["remain silent", "it remains to be seen"], "synonyms": ["stay", "continue"], "antonyms": ["leave", "change"], "example": "The price of the product will remain the same for the rest of the year."},
    "remark": {"phonetic": "/rɪˈmɑːrk/", "pos": "n./v.", "meaning": "評論；話語", "phrases": ["make a remark", "remarkable"], "synonyms": ["comment", "observation"], "antonyms": [], "example": "The manager made several interesting remarks about the new project during the meeting."},
    "render": {"phonetic": "/ˈrendər/", "pos": "v.", "meaning": "致使；提供(服務)", "phrases": ["render a service", "render assistance"], "synonyms": ["make", "provide"], "antonyms": [], "example": "The sudden power failure rendered all the office computers useless."},
    "render thanks": {"phonetic": "/ˈrendər θæŋks/", "pos": "v.", "meaning": "表示感謝", "phrases": [], "synonyms": ["express gratitude"], "antonyms": [], "example": "I would like to render my sincere thanks to everyone who helped with the project."},
    "represent": {"phonetic": "/ˌreprɪˈzent/", "pos": "v.", "meaning": "代表；表現", "phrases": ["represent a client", "sales representative"], "synonyms": ["stand for", "symbolize"], "antonyms": [], "example": "Our local sales representative will visit your office next week to discuss the contract."},
    "rescue": {"phonetic": "/ˈreskjuː/", "pos": "v./n.", "meaning": "營救；救援", "phrases": ["rescue mission", "come to the rescue"], "synonyms": ["save", "deliver"], "antonyms": ["abandon"], "example": "The government launched a plan to rescue the failing national airline from bankruptcy."},
    "resemble": {"phonetic": "/rɪˈzembl/", "pos": "v.", "meaning": "像；與...相似", "phrases": ["closely resemble", "bear a resemblance"], "synonyms": ["look like", "be similar to"], "antonyms": ["differ from"], "example": "The new office building will resemble the modern design of our headquarters in London."},
    "resolve": {"phonetic": "/rɪˈzɑːlv/", "pos": "v.", "meaning": "解決；決定", "phrases": ["resolve a conflict", "firmly resolved"], "synonyms": ["settle", "solve"], "antonyms": [], "example": "We are working hard to resolve the technical issues as quickly as possible."},
    "retrieve": {"phonetic": "/rɪˈtriːv/", "pos": "v.", "meaning": "取回；檢索(數據)", "phrases": ["retrieve data", "retrieve a file"], "synonyms": ["recover", "get back"], "antonyms": ["lose"], "example": "It took several hours to retrieve the lost data from the computer system."},
    "reveal": {"phonetic": "/rɪˈviːl/", "pos": "v.", "meaning": "揭露；顯示", "phrases": ["reveal a secret", "revealing results"], "synonyms": ["disclose", "show"], "antonyms": ["hide", "conceal"], "example": "The latest market research revealed a growing demand for eco-friendly products."}
}

with open('data_green.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_3:
        item.update(enriched_data_3[word])

with open('data_green.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修第 101-150 個高品質單字。")
