import json
import os

def update_vocab():
    # 第十五批 100 個商務進階單字 (藍色等級)
    new_data = [
        {"word": "Deceptive", "phonetic": "/dɪˈseptɪv/", "pos": "adj.", "meaning": "欺騙性的, 誤導的", "level": "blue", "phrases": ["deceptive advertising", "highly deceptive"], "synonyms": ["misleading", "dishonest"], "antonyms": ["honest", "truthful"], "example": "The company was fined for its deceptive advertising regarding the health benefits of its products."},
        {"word": "Decisive", "phonetic": "/dɪˈsaɪsɪv/", "pos": "adj.", "meaning": "決定性的, 果斷的", "level": "blue", "phrases": ["decisive action", "play a decisive role"], "synonyms": ["conclusive", "resolute"], "antonyms": ["indecisive", "hesitant"], "example": "The CEO took decisive action to stabilize the company's financial position during the crisis."},
        {"word": "Declaration", "phonetic": "/ˌdekləˈreɪʃn/", "pos": "n.", "meaning": "宣布, 申報, 聲明", "level": "blue", "phrases": ["customs declaration", "official declaration"], "synonyms": ["announcement", "statement"], "antonyms": [], "example": "Please ensure that you fill out the customs declaration form accurately before entering the country."},
        {"word": "Decline", "phonetic": "/dɪˈklaɪn/", "pos": "v./n.", "meaning": "下降, 衰退, 拒絕", "level": "blue", "phrases": ["sharp decline", "decline an invitation"], "synonyms": ["decrease", "reject"], "antonyms": ["increase", "accept"], "example": "The company reported a sharp decline in profits due to increased competition in the market."},
        {"word": "Dedicate", "phonetic": "/ˈdedɪkeɪt/", "pos": "v.", "meaning": "奉獻, 致力於", "level": "blue", "phrases": ["dedicate oneself to", "dedicated server"], "synonyms": ["devote", "commit"], "antonyms": [], "example": "The team is dedicated to providing high-quality customer service to all our international clients."},
        {"word": "Deduct", "phonetic": "/dɪˈdʌkt/", "pos": "v.", "meaning": "扣除, 減去", "level": "blue", "phrases": ["deduct from salary", "automatically deducted"], "synonyms": ["subtract", "remove"], "antonyms": ["add"], "example": "The membership fee will be automatically deducted from your account every month."},
        {"word": "Deduction", "phonetic": "/dɪˈdʌkʃn/", "pos": "n.", "meaning": "扣除額, 推論", "level": "blue", "phrases": ["tax deduction", "logical deduction"], "synonyms": ["discount", "inference"], "antonyms": ["addition"], "example": "Businesses can claim various tax deductions for expenses related to research and development."},
        {"word": "Deface", "phonetic": "/dɪˈfeɪs/", "pos": "v.", "meaning": "毀容, 塗汙, 損壞外觀", "level": "blue", "phrases": ["deface property", "willfully deface"], "synonyms": ["damage", "mar"], "antonyms": ["repair", "beautify"], "example": "Anyone caught trying to deface company property will face severe disciplinary action."},
        {"word": "Defame", "phonetic": "/dɪˈfeɪm/", "pos": "v.", "meaning": "誹謗, 中傷", "level": "blue", "phrases": ["defame someone's character"], "synonyms": ["slander", "libel"], "antonyms": ["praise", "honor"], "example": "The newspaper was sued for attempting to defame the reputation of the prominent business leader."},
        {"word": "Defective", "phonetic": "/dɪˈfektɪv/", "pos": "adj.", "meaning": "有缺陷的, 有瑕疵的", "level": "blue", "phrases": ["defective product", "return defective goods"], "synonyms": ["faulty", "flawed"], "antonyms": ["perfect", "flawless"], "example": "Customers are entitled to a full refund if they receive a defective product from our store."},
        {"word": "Defence", "phonetic": "/dɪˈfens/", "pos": "n.", "meaning": "防禦, 辯護", "level": "blue", "phrases": ["legal defence", "in defence of"], "synonyms": ["protection", "shield"], "antonyms": ["offence", "attack"], "example": "The firm hired a top-tier legal team to prepare its defence against the patent infringement claim."},
        {"word": "Defensive", "phonetic": "/dɪˈfensɪv/", "pos": "adj.", "meaning": "防禦性的, 自衛的", "level": "blue", "phrases": ["defensive strategy", "become defensive"], "synonyms": ["protective"], "antonyms": ["aggressive"], "example": "The company adopted a defensive strategy to protect its market share from aggressive new competitors."},
        {"word": "Deference", "phonetic": "/ˈdefərəns/", "pos": "n.", "meaning": "尊重, 順從", "level": "blue", "phrases": ["out of deference to", "show deference"], "synonyms": ["respect", "regard"], "antonyms": ["disrespect"], "example": "Out of deference to the visiting dignitaries, the meeting schedule was adjusted at the last minute."},
        {"word": "Deficiency", "phonetic": "/dɪˈfɪʃnsi/", "pos": "n.", "meaning": "缺乏, 不足, 缺陷", "level": "blue", "phrases": ["vitamin deficiency", "budgetary deficiency"], "synonyms": ["shortage", "scarcity"], "antonyms": ["surplus", "abundance"], "example": "The audit revealed a significant deficiency in the company's internal financial control systems."},
        {"word": "Deficient", "phonetic": "/dɪˈfɪʃnt/", "pos": "adj.", "meaning": "缺乏的, 不足的, 有缺陷的", "level": "blue", "phrases": ["deficient in", "mentally deficient"], "synonyms": ["lacking", "inadequate"], "antonyms": ["sufficient", "adequate"], "example": "The original project proposal was considered deficient in detail and was returned for revision."},
        {"word": "Define", "phonetic": "/dɪˈfaɪn/", "pos": "v.", "meaning": "定義, 規定, 限定", "level": "blue", "phrases": ["clearly define", "define the scope"], "synonyms": ["explain", "specify"], "antonyms": ["confuse"], "example": "It is essential to clearly define the roles and responsibilities of each team member at the start of the project."},
        {"word": "Definite", "phonetic": "/ˈdefɪnət/", "pos": "adj.", "meaning": "明確的, 肯定的", "level": "blue", "phrases": ["definite plan", "give a definite answer"], "synonyms": ["clear", "certain"], "antonyms": ["indefinite", "vague"], "example": "We need a definite commitment from our partners before we proceed with the next phase of the project."},
        {"word": "Definition", "phonetic": "/ˌdefɪˈnɪʃn/", "pos": "n.", "meaning": "定義, 清晰度", "level": "blue", "phrases": ["by definition", "high definition"], "synonyms": ["meaning", "explanation"], "antonyms": [], "example": "The standard legal definition of a 'small business' varies from one country to another."},
        {"word": "Deflate", "phonetic": "/dɪˈfleɪt/", "pos": "v.", "meaning": "使縮小, 通貨緊縮, 洩氣", "level": "blue", "phrases": ["deflate the tires", "deflate the ego"], "synonyms": ["shrink", "contract"], "antonyms": ["inflate"], "example": "The central bank's policy is aimed at trying to deflate the growing bubble in the local real estate market."},
        {"word": "Deflation", "phonetic": "/dɪˈfleɪʃn/", "pos": "n.", "meaning": "通貨緊縮", "level": "blue", "phrases": ["economic deflation", "risk of deflation"], "synonyms": [], "antonyms": ["inflation"], "example": "Economists are worried that prolonged deflation could lead to a significant slowdown in economic growth."},
        {"word": "Deflect", "phonetic": "/dɪˈflekt/", "pos": "v.", "meaning": "偏斜, 轉移(注意力/批評)", "level": "blue", "phrases": ["deflect criticism", "deflect attention"], "synonyms": ["divert", "distract"], "antonyms": [], "example": "The spokesperson tried to deflect the journalist's questions regarding the company's financial losses."},
        {"word": "Defraud", "phonetic": "/dɪˈfrɔːd/", "pos": "v.", "meaning": "詐騙, 欺詐", "level": "blue", "phrases": ["defraud the government", "conspiracy to defraud"], "synonyms": ["cheat", "swindle"], "antonyms": [], "example": "The individual was arrested for attempting to defraud investors out of millions of dollars."},
        {"word": "Defray", "phonetic": "/dɪˈfreɪ/", "pos": "v.", "meaning": "支付, 負擔(費用)", "level": "blue", "phrases": ["defray the costs", "defray expenses"], "synonyms": ["pay", "cover"], "antonyms": [], "example": "The grant is intended to help defray the costs of attending the international research conference."},
        {"word": "Degrade", "phonetic": "/dɪˈɡreɪd/", "pos": "v.", "meaning": "降級, 退化, 侮辱", "level": "blue", "phrases": ["degrade the environment", "highly degrading"], "synonyms": ["deteriorate", "humiliate"], "antonyms": ["improve", "upgrade"], "example": "The use of low-quality materials will seriously degrade the overall performance and lifespan of the product."},
        {"word": "Degree", "phonetic": "/dɪˈɡriː/", "pos": "n.", "meaning": "程度, 等級, 學位", "level": "blue", "phrases": ["to a certain degree", "university degree"], "synonyms": ["extent", "level"], "antonyms": [], "example": "Candidates for the position are required to have a university degree in finance or a related field."},
        {"word": "Delegation", "phonetic": "/ˌdelɪˈɡeɪʃn/", "pos": "n.", "meaning": "代表團, 授權, 委派", "level": "blue", "phrases": ["trade delegation", "effective delegation"], "synonyms": ["deputation", "commission"], "antonyms": [], "example": "The effective delegation of tasks is an essential skill for any successful manager in a large organization."},
        {"word": "Delete", "phonetic": "/dɪˈliːt/", "pos": "v.", "meaning": "刪除", "level": "blue", "phrases": ["delete a file", "permanently delete"], "synonyms": ["remove", "erase"], "antonyms": ["add", "insert"], "example": "Please remember to delete any confidential files from your computer before you leave the company."},
        {"word": "Deleterious", "phonetic": "/ˌdelɪˈtɪriəs/", "pos": "adj.", "meaning": "有害的, 有毒的", "level": "blue", "phrases": ["deleterious effects", "deleterious impact"], "synonyms": ["harmful", "detrimental"], "antonyms": ["beneficial", "helpful"], "example": "The sudden increase in interest rates could have a deleterious effect on the country's economic recovery."},
        {"word": "Deliberate", "phonetic": "/dɪˈlɪbərət/", "pos": "adj./v.", "meaning": "故意的, 慎重的, 仔細考慮", "level": "blue", "phrases": ["deliberate attempt", "deliberate on a decision"], "synonyms": ["intentional", "planned"], "antonyms": ["accidental", "hasty"], "example": "The jury took several days to deliberate on the complex evidence before reaching a final verdict."},
        {"word": "Deliberately", "phonetic": "/dɪˈlɪbərətli/", "pos": "adv.", "meaning": "故意地, 慎重地", "level": "blue", "phrases": ["deliberately mislead"], "synonyms": ["intentionally", "purposely"], "antonyms": ["accidentally"], "example": "The manager deliberately kept the information confidential until the official announcement was made."},
        {"word": "Deliberation", "phonetic": "/dɪˌlɪbəˈreɪʃn/", "pos": "n.", "meaning": "審議, 深思熟慮", "level": "blue", "phrases": ["after careful deliberation", "period of deliberation"], "synonyms": ["contemplation", "discussion"], "antonyms": [], "example": "After careful deliberation, the board of directors decided to approve the proposed international expansion."},
        {"word": "Delicate", "phonetic": "/ˈdelɪkət/", "pos": "adj.", "meaning": "精緻的, 脆弱的, 微妙的", "level": "blue", "phrases": ["delicate balance", "delicate situation"], "synonyms": ["fragile", "subtle"], "antonyms": ["sturdy", "robust"], "example": "The situation requires a delicate touch to ensure that the ongoing negotiations are not jeopardized."},
        {"word": "Delighted", "phonetic": "/dɪˈlaɪtɪd/", "pos": "adj.", "meaning": "高興的, 欣喜的", "level": "blue", "phrases": ["delighted to meet you", "absolutely delighted"], "synonyms": ["happy", "pleased"], "antonyms": ["miserable", "unhappy"], "example": "We are delighted to announce that our company has been awarded the government contract for the new project."},
        {"word": "Delineate", "phonetic": "/dɪˈlɪnieɪt/", "pos": "v.", "meaning": "描繪, 敘述, 劃定(界線)", "level": "blue", "phrases": ["clearly delineate", "delineate the boundaries"], "synonyms": ["describe", "define"], "antonyms": [], "example": "The report fails to clearly delineate the potential risks associated with the new investment strategy."},
        {"word": "Delinquency", "phonetic": "/dɪˈlɪŋkwənsi/", "pos": "n.", "meaning": "拖欠, 違法行為", "level": "blue", "phrases": ["loan delinquency", "juvenile delinquency"], "synonyms": ["default", "fault"], "antonyms": [], "example": "The bank is taking steps to reduce the rising rate of delinquency among its credit card customers."},
        {"word": "Delinquent", "phonetic": "/dɪˈlɪŋkwənt/", "pos": "adj./n.", "meaning": "拖欠的, 違法的, 違法者", "level": "blue", "phrases": ["delinquent account", "delinquent taxes"], "synonyms": ["overdue", "unpaid"], "antonyms": ["paid"], "example": "The company sent a formal notice to all customers with delinquent accounts requesting immediate payment."},
        {"word": "Deliverable", "phonetic": "/dɪˈlɪvərəbl/", "pos": "n.", "meaning": "可交付成果, 產品", "level": "blue", "phrases": ["project deliverables", "key deliverables"], "synonyms": ["output", "product"], "antonyms": [], "example": "The management team is reviewing the key deliverables for each phase of the new development project."},
        {"word": "Delivery", "phonetic": "/dɪˈlɪvəri/", "pos": "n.", "meaning": "遞送, 交付, 演講風格", "level": "blue", "phrases": ["express delivery", "home delivery"], "synonyms": ["consignment", "shipment"], "antonyms": [], "example": "We offer free delivery on all online orders over fifty dollars within the continental United States."},
        {"word": "Deluge", "phonetic": "/ˈdeljuːdʒ/", "pos": "n./v.", "meaning": "大洪水, 湧現, 使氾濫", "level": "blue", "phrases": ["deluge of complaints", "deluge of orders"], "synonyms": ["flood", "inundation"], "antonyms": [], "example": "The customer support department was hit by a deluge of complaints following the latest software update."},
        {"word": "Deluxe", "phonetic": "/dəˈlʌks/", "pos": "adj.", "meaning": "豪華的, 高級的", "level": "blue", "phrases": ["deluxe hotel", "deluxe edition"], "synonyms": ["luxurious", "sumptuous"], "antonyms": ["basic", "standard"], "example": "The company booked several deluxe suites for the international dignitaries attending the gala dinner."},
        {"word": "Demand", "phonetic": "/dɪˈmænd/", "pos": "n./v.", "meaning": "需求, 要求", "level": "blue", "phrases": ["high demand", "on demand"], "synonyms": ["request", "requirement"], "antonyms": ["supply"], "example": "There is a growing demand for high-quality and affordable solar energy solutions for residential homes."},
        {"word": "Demarcation", "phonetic": "/ˌdiːmɑːrˈkeɪʃn/", "pos": "n.", "meaning": "劃界, 區別", "level": "blue", "phrases": ["line of demarcation", "clear demarcation"], "synonyms": ["boundary", "separation"], "antonyms": [], "example": "There needs to be a clear demarcation of responsibilities between the marketing and sales departments."},
        {"word": "Demeanor", "phonetic": "/dɪˈmiːnər/", "pos": "n.", "meaning": "舉止, 行為, 風度", "level": "blue", "phrases": ["professional demeanor", "calm demeanor"], "synonyms": ["behavior", "manner"], "antonyms": [], "example": "The candidate's professional demeanor and clear communication skills made a very positive impression on the committee."},
        {"word": "Demise", "phonetic": "/dɪˈmaɪz/", "pos": "n.", "meaning": "倒閉, 死亡, 轉讓", "level": "blue", "phrases": ["the demise of a company", "sudden demise"], "synonyms": ["failure", "collapse"], "antonyms": ["birth", "rise"], "example": "The rapid advancement of digital technology led to the eventual demise of many traditional film-based firms."},
        {"word": "Democracy", "phonetic": "/dɪˈmɑːkrəsi/", "pos": "n.", "meaning": "民主, 民主政體", "level": "blue", "phrases": ["corporate democracy", "liberal democracy"], "synonyms": [], "antonyms": ["dictatorship"], "example": "The company's new policy is aimed at promoting more corporate democracy and transparency in decision-making."},
        {"word": "Demolish", "phonetic": "/dɪˈmɑːlɪʃ/", "pos": "v.", "meaning": "拆除, 破壞", "level": "blue", "phrases": ["demolish a building", "completely demolish"], "synonyms": ["destroy", "raze"], "antonyms": ["build", "construct"], "example": "The city council plans to demolish the old warehouse to make room for a new public park and community center."},
        {"word": "Demolition", "phonetic": "/ˌdeməˈlɪʃn/", "pos": "n.", "meaning": "拆除, 破壞", "level": "blue", "phrases": ["demolition site", "demolition work"], "synonyms": ["destruction"], "antonyms": ["construction"], "example": "Demolition work on the old factory building is expected to begin early next month and take six weeks."},
        {"word": "Demonstrate", "phonetic": "/ˈdemənstreɪt/", "pos": "v.", "meaning": "證明, 演示, 示範", "level": "blue", "phrases": ["demonstrate a product", "clearly demonstrate"], "synonyms": ["show", "illustrate"], "antonyms": [], "example": "The technician will demonstrate how to use the new software system during the training session tomorrow."},
        {"word": "Demonstration", "phonetic": "/ˌdemənˈstreɪʃn/", "pos": "n.", "meaning": "演示, 示範, 示威", "level": "blue", "phrases": ["product demonstration", "peaceful demonstration"], "synonyms": ["exhibition", "display"], "antonyms": [], "example": "The sales team provided a live demonstration of the new features of the smartphone to the potential client."},
        {"word": "Demote", "phonetic": "/ˌdiːˈmoʊt/", "pos": "v.", "meaning": "降職, 降級", "level": "blue", "phrases": ["be demoted to", "demote an employee"], "synonyms": ["downgrade"], "antonyms": ["promote"], "example": "The manager was demoted following reports of gross negligence and failure to follow company safety rules."},
        {"word": "Demotion", "phonetic": "/ˌdiːˈmoʊʃn/", "pos": "n.", "meaning": "降職, 降級", "level": "blue", "phrases": ["face demotion", "unfair demotion"], "synonyms": ["downgrade"], "antonyms": ["promotion"], "example": "The employee is considering legal action against the firm, claiming that his demotion was unfair and discriminatory."},
        {"word": "Denial", "phonetic": "/dɪˈnaɪəl/", "pos": "n.", "meaning": "否認, 拒絕", "level": "blue", "phrases": ["official denial", "denial of service"], "synonyms": ["refusal", "rejection"], "antonyms": ["acceptance", "admission"], "example": "The company issued an official denial of the rumors regarding a potential merger with its arch rival."},
        {"word": "Denounce", "phonetic": "/dɪˈnaʊns/", "pos": "v.", "meaning": "譴責, 告發", "level": "blue", "phrases": ["denounce violence", "publicly denounce"], "synonyms": ["condemn", "criticize"], "antonyms": ["praise", "applaud"], "example": "Several international organizations have denounced the government's new trade policy as unfair and protectionist."},
        {"word": "Dense", "phonetic": "/dens/", "pos": "adj.", "meaning": "稠密的, 密集的", "level": "blue", "phrases": ["dense forest", "dense population"], "synonyms": ["thick", "compact"], "antonyms": ["sparse", "thin"], "example": "The city has one of the most dense populations in the world, leading to high real estate prices."},
        {"word": "Density", "phonetic": "/ˈdensəti/", "pos": "n.", "meaning": "密度, 稠密", "level": "blue", "phrases": ["population density", "high density"], "synonyms": ["thickness", "concentration"], "antonyms": [], "example": "The high population density in the downtown area makes it an ideal location for our new retail outlet."},
        {"word": "Depart", "phonetic": "/dɪˈpɑːrt/", "pos": "v.", "meaning": "離開, 出發, 離職", "level": "blue", "phrases": ["depart from", "depart on time"], "synonyms": ["leave", "quit"], "antonyms": ["arrive"], "example": "The flight is scheduled to depart from Tokyo at 10:00 AM and arrive in New York the same day."},
        {"word": "Department", "phonetic": "/dɪˈpɑːrtmənt/", "pos": "n.", "meaning": "部門, 系", "level": "blue", "phrases": ["marketing department", "fire department"], "synonyms": ["division", "section"], "antonyms": [], "example": "Each department is responsible for managing its own annual budget and professional development programs."},
        {"word": "Departure", "phonetic": "/dɪˈpɑːrtʃər/", "pos": "n.", "meaning": "離開, 出發, 離職, 違背", "level": "blue", "phrases": ["scheduled departure", "departure lounge"], "synonyms": ["exit", "withdrawal"], "antonyms": ["arrival"], "example": "The sudden departure of the marketing director has left the department in a state of confusion."},
        {"word": "Dependability", "phonetic": "/dɪˌpendəˈbɪləti/", "pos": "n.", "meaning": "可靠性, 可信任度", "level": "blue", "phrases": ["product dependability", "high dependability"], "synonyms": ["reliability", "trustworthiness"], "antonyms": ["unreliability"], "example": "Our brand has built a reputation for product dependability and high-quality customer support worldwide."},
        {"word": "Dependable", "phonetic": "/dɪˈpendəbl/", "pos": "adj.", "meaning": "可靠的, 可信任的", "level": "blue", "phrases": ["dependable service", "highly dependable"], "synonyms": ["reliable", "trustworthy"], "antonyms": ["unreliable"], "example": "We are looking for a dependable individual to manage our newly established distribution center in Asia."},
        {"word": "Dependence", "phonetic": "/dɪˈpendəns/", "pos": "n.", "meaning": "依賴, 信任", "level": "blue", "phrases": ["heavy dependence on", "mutual dependence"], "synonyms": ["reliance"], "antonyms": ["independence"], "example": "Our heavy dependence on a single supplier for raw materials is a significant risk to our operations."},
        {"word": "Dependency", "phonetic": "/dɪˈpendənsi/", "pos": "n.", "meaning": "依賴, 屬地", "level": "blue", "phrases": ["drug dependency", "economic dependency"], "synonyms": ["reliance"], "antonyms": ["independence"], "example": "The country is trying to reduce its economic dependency on oil exports by developing its technology sector."},
        {"word": "Dependent", "phonetic": "/dɪˈpendənt/", "pos": "adj./n.", "meaning": "依賴的, 受...影響的, 受扶養者", "level": "blue", "phrases": ["heavily dependent on", "claim a dependent"], "synonyms": ["contingent", "conditional"], "antonyms": ["independent"], "example": "The success of the project is dependent on our ability to secure adequate funding from international investors."},
        {"word": "Depict", "phonetic": "/dɪˈpɪkt/", "pos": "v.", "meaning": "描繪, 描述", "level": "blue", "phrases": ["graphically depict", "depict a scene"], "synonyms": ["describe", "portray"], "antonyms": [], "example": "The presentation included several charts that graphically depict the steady growth in our international sales."},
        {"word": "Depiction", "phonetic": "/dɪˈpɪkʃn/", "pos": "n.", "meaning": "描繪, 描述", "level": "blue", "phrases": ["accurate depiction", "fair depiction"], "synonyms": ["description", "portrayal"], "antonyms": [], "example": "The newsletter provides an accurate depiction of the challenges facing small businesses in the current market."},
        {"word": "Deplete", "phonetic": "/dɪˈpliːt/", "pos": "v.", "meaning": "耗盡, 枯竭", "level": "blue", "phrases": ["deplete resources", "deplete the ozone layer"], "synonyms": ["exhaust", "use up"], "antonyms": ["replenish", "restore"], "example": "The long period of low sales has seriously depleted the company's annual marketing and research budget."},
        {"word": "Depletion", "phonetic": "/dɪˈpliːʃn/", "pos": "n.", "meaning": "耗盡, 枯竭", "level": "blue", "phrases": ["ozone depletion", "resource depletion"], "synonyms": ["exhaustion"], "antonyms": ["replenishment"], "example": "The rapid depletion of natural resources is a major global concern that requires immediate international action."},
        {"word": "Deplorable", "phonetic": "/dɪˈplɔːrəbl/", "pos": "adj.", "meaning": "糟透的, 應受譴責的", "level": "blue", "phrases": ["deplorable conditions", "absolutely deplorable"], "synonyms": ["wretched", "disgraceful"], "antonyms": ["admirable", "excellent"], "example": "The investigation revealed the deplorable working conditions in many of the small manufacturing plants in the region."},
        {"word": "Deplore", "phonetic": "/dɪˈplɔːr/", "pos": "v.", "meaning": "哀嘆, 譴責", "level": "blue", "phrases": ["deeply deplore"], "synonyms": ["condemn", "lament"], "antonyms": ["praise", "applaud"], "example": "The international community continues to deplore the use of child labor in the global textile industry."},
        {"word": "Deploy", "phonetic": "/dɪˈplɔɪ/", "pos": "v.", "meaning": "部署, 運用", "level": "blue", "phrases": ["deploy resources", "deploy technology"], "synonyms": ["utilize", "station"], "antonyms": [], "example": "The firm plans to deploy its latest security software across all its regional offices by the end of the year."},
        {"word": "Deployment", "phonetic": "/dɪˈplɔɪmənt/", "pos": "n.", "meaning": "部署, 運用", "level": "blue", "phrases": ["software deployment", "rapid deployment"], "synonyms": ["utilization", "stationing"], "antonyms": [], "example": "The rapid deployment of renewable energy technology is essential for meeting international carbon reduction targets."},
        {"word": "Deposit", "phonetic": "/dɪˈpɑːzɪt/", "pos": "n./v.", "meaning": "存款, 押金, 存放", "level": "blue", "phrases": ["security deposit", "direct deposit"], "synonyms": ["payment", "store"], "antonyms": ["withdrawal"], "example": "Most landlords require a security deposit equivalent to one month's rent before tenants move in."},
        {"word": "Deposition", "phonetic": "/ˌdepəˈzɪʃn/", "pos": "n.", "meaning": "宣誓證言, 罷免, 沉澱", "level": "blue", "phrases": ["give a deposition", "written deposition"], "synonyms": ["testimony", "statement"], "antonyms": [], "example": "The witness provided a detailed deposition to the legal team regarding the alleged contract dispute."},
        {"word": "Depository", "phonetic": "/dɪˈpɑːzətɔːri/", "pos": "n.", "meaning": "儲藏所, 存放處, 受託者", "level": "blue", "phrases": ["official depository", "safe depository"], "synonyms": ["warehouse", "storehouse"], "antonyms": [], "example": "The bank serves as an official depository for government funds and various high-value financial assets."},
        {"word": "Depot", "phonetic": "/ˈdiːpoʊ/", "pos": "n.", "meaning": "倉庫, 站", "level": "blue", "phrases": ["bus depot", "supply depot"], "synonyms": ["warehouse", "terminal"], "antonyms": [], "example": "A large shipment of raw materials is currently being stored at the main supply depot near the port."},
        {"word": "Depreciate", "phonetic": "/dɪˈpriːʃieɪt/", "pos": "v.", "meaning": "貶值, 折舊, 輕視", "level": "blue", "phrases": ["currency depreciates", "depreciate assets"], "synonyms": ["devalue"], "antonyms": ["appreciate"], "example": "Many electronic products depreciate rapidly in value as newer and more advanced models are released."},
        {"word": "Depreciation", "phonetic": "/dɪˌpriːʃiˈeɪʃn/", "pos": "n.", "meaning": "貶值, 折舊", "level": "blue", "phrases": ["annual depreciation", "currency depreciation"], "synonyms": ["devaluation"], "antonyms": ["appreciation"], "example": "The accountant spent the afternoon calculating the annual depreciation of the company's office equipment."},
        {"word": "Depress", "phonetic": "/dɪˈpres/", "pos": "v.", "meaning": "使沮喪, 使蕭條, 按下", "level": "blue", "phrases": ["depress the market", "depress a key"], "synonyms": ["sadden", "weaken"], "antonyms": ["uplift", "boost"], "example": "The sudden increase in import tariffs is expected to seriously depress the domestic steel market prices."},
        {"word": "Depressed", "phonetic": "/dɪˈprest/", "pos": "adj.", "meaning": "沮喪的, 蕭條的", "level": "blue", "phrases": ["economically depressed", "feel depressed"], "synonyms": ["sad", "weak"], "antonyms": ["prosperous", "happy"], "example": "The local government is providing grants to encourage new businesses to open in economically depressed areas."},
        {"word": "Depression", "phonetic": "/dɪˈpreʃn/", "pos": "n.", "meaning": "憂鬱, 蕭條, 窪地", "level": "blue", "phrases": ["economic depression", "deep depression"], "synonyms": ["slump", "downturn"], "antonyms": ["boom", "prosperity"], "example": "Many families struggled to survive during the Great Depression, which began in the late 1920s."},
        {"word": "Deprive", "phonetic": "/dɪˈpraɪv/", "pos": "v.", "meaning": "剝奪, 使喪失", "level": "blue", "phrases": ["deprive of rights", "be deprived of"], "synonyms": ["strip", "rob"], "antonyms": ["provide", "bestow"], "example": "The new regulations could deprive many small businesses of their primary sources of international revenue."},
        {"word": "Depth", "phonetic": "/depθ/", "pos": "n.", "meaning": "深度, 深度(程度)", "level": "blue", "phrases": ["in depth", "out of one's depth"], "synonyms": ["intensity", "extent"], "antonyms": ["shallowness"], "example": "The marketing report provides an in-depth analysis of the current consumer spending habits in Asia."},
        {"word": "Deputy", "phonetic": "/ˈdepjuti/", "pos": "n./adj.", "meaning": "副手, 代理人, 副的", "level": "blue", "phrases": ["deputy manager", "deputy director"], "synonyms": ["assistant", "proxy"], "antonyms": [], "example": "The deputy manager will be in charge of the department while her supervisor is on maternity leave."},
        {"word": "Derelict", "phonetic": "/ˈderəlɪkt/", "pos": "adj./n.", "meaning": "被拋棄的, 玩忽職守的, 遺棄物", "level": "blue", "phrases": ["derelict building", "derelict in duty"], "synonyms": ["abandoned", "negligent"], "antonyms": [], "example": "The city council is planning to renovate several derelict buildings in the old industrial district."},
        {"word": "Dereliction", "phonetic": "/ˌderəˈlɪkʃn/", "pos": "n.", "meaning": "玩忽職守, 遺棄", "level": "blue", "phrases": ["dereliction of duty"], "synonyms": ["negligence", "neglect"], "antonyms": [], "example": "The security guard was dismissed for gross dereliction of duty following the unauthorized break-in."},
        {"word": "Deride", "phonetic": "/dɪˈraɪd/", "pos": "v.", "meaning": "嘲笑, 嘲弄", "level": "blue", "phrases": ["be derided by critics"], "synonyms": ["mock", "ridicule"], "antonyms": ["praise", "respect"], "example": "The initial project proposal was derided by some board members as being too ambitious and unrealistic."},
        {"word": "Derisive", "phonetic": "/dɪˈraɪsɪv/", "pos": "adj.", "meaning": "嘲笑的, 嘲弄的", "level": "blue", "phrases": ["derisive laughter", "derisive comment"], "synonyms": ["mocking", "scornful"], "antonyms": ["respectful"], "example": "His derisive comments regarding his colleagues' hard work led to a formal warning from the manager."},
        {"word": "Derivation", "phonetic": "/ˌderɪˈveɪʃn/", "pos": "n.", "meaning": "起源, 派生", "level": "blue", "phrases": ["word derivation", "derivation of a formula"], "synonyms": ["origin", "source"], "antonyms": [], "example": "The derivation of many modern business terms can be traced back to military and legal terminology."},
        {"word": "Derivative", "phonetic": "/dɪˈrɪvətɪv/", "pos": "adj./n.", "meaning": "衍生的, 衍生產品", "level": "blue", "phrases": ["financial derivatives", "highly derivative"], "synonyms": ["unoriginal", "secondary"], "antonyms": ["original"], "example": "Investors are cautioned about the high risks associated with trading complex financial derivatives in the market."},
        {"word": "Derive", "phonetic": "/dɪˈraɪv/", "pos": "v.", "meaning": "獲得, 源於, 推論出", "level": "blue", "phrases": ["derive from", "derive benefit from"], "synonyms": ["obtain", "originate"], "antonyms": [], "example": "The company derives a significant portion of its annual revenue from its international operations in Europe."},
        {"word": "Descend", "phonetic": "/dɪˈsend/", "pos": "v.", "meaning": "下降, 傳下, 突然到訪", "level": "blue", "phrases": ["descend the stairs", "descend into chaos"], "synonyms": ["drop", "fall"], "antonyms": ["ascend", "rise"], "example": "The elevator will descend to the basement level where the secure storage facility is located."},
        {"word": "Descendant", "phonetic": "/dɪˈsendənt/", "pos": "n.", "meaning": "後裔, 子孫", "level": "blue", "phrases": ["direct descendant"], "synonyms": ["heir", "offspring"], "antonyms": ["ancestor"], "example": "The founder's direct descendants still own a majority share in the private family-owned corporation."},
        {"word": "Descent", "phonetic": "/dɪˈsent/", "pos": "n.", "meaning": "下降, 出身, 斜坡", "level": "blue", "phrases": ["steep descent", "of Asian descent"], "synonyms": ["drop", "ancestry"], "antonyms": ["ascent"], "example": "The pilot announced the start of the final descent into Tokyo Narita International Airport."},
        {"word": "Describe", "phonetic": "/dɪˈskraɪb/", "pos": "v.", "meaning": "描述, 形容", "level": "blue", "phrases": ["vividly describe", "describe the process"], "synonyms": ["portray", "delineate"], "antonyms": [], "example": "Could you please describe the specific issues you encountered while using the new software system?"},
        {"word": "Description", "phonetic": "/dɪˈskrɪpʃn/", "pos": "n.", "meaning": "描述, 職業, 種類", "level": "blue", "phrases": ["job description", "beyond description"], "synonyms": ["depiction", "portrayal"], "antonyms": [], "example": "Please provide a detailed job description along with the vacancy announcement for the senior accountant role."},
        {"word": "Deserve", "phonetic": "/dɪˈzɜːrv/", "pos": "v.", "meaning": "應受, 值得", "level": "blue", "phrases": ["well-deserved", "deserve a promotion"], "synonyms": ["merit", "earn"], "antonyms": [], "example": "The entire team deserves recognition for their hard work during the successful audit process last week."},
        {"word": "Design", "phonetic": "/dɪˈzaɪn/", "pos": "n./v.", "meaning": "設計, 圖案, 策劃", "level": "blue", "phrases": ["graphic design", "by design"], "synonyms": ["plan", "draft"], "antonyms": [], "example": "The marketing department is working on a new design for our corporate newsletter and website."},
        {"word": "Designate", "phonetic": "/ˈdezɪɡneɪt/", "pos": "v./adj.", "meaning": "指定, 任命, 指定的", "level": "blue", "phrases": ["designated smoking area", "designate a representative"], "synonyms": ["appoint", "specify"], "antonyms": [], "example": "The CEO plans to designate her successor before she retires at the end of the fiscal year."},
        {"word": "Designation", "phonetic": "/ˌdezɪɡˈneɪʃn/", "pos": "n.", "meaning": "指定, 名稱, 職位", "level": "blue", "phrases": ["official designation", "receive a designation"], "synonyms": ["name", "title"], "antonyms": [], "example": "The 'Eco-Friendly' designation is only awarded to firms that meet strict environmental and sustainability criteria."}
    ]
    
    file_path = "data_blue.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                current_data = json.load(f)
            except:
                current_data = []
    else:
        current_data = []

    # 避免重複 (根據 word)
    existing_words = {item['word'].lower() for item in current_data}
    added_count = 0
    for item in new_data:
        if item['word'].lower() not in existing_words:
            current_data.append(item)
            added_count += 1
            
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(current_data, f, ensure_ascii=False, indent=2)
        
    print(f"成功合併！新增了 {added_count} 個單字到 {file_path}，目前總計 {len(current_data)} 個單字。")

if __name__ == "__main__":
    update_vocab()
