import json

# 第 51-100 個高品質單字對應表 (綠色等級)
enriched_data_2 = {
    "encroach": {"phonetic": "/ɪnˈkroʊtʃ/", "pos": "v.", "meaning": "侵占；侵入", "phrases": ["encroach on", "encroach upon"], "synonyms": ["intrude", "trespass"], "antonyms": [], "example": "The new building project must not encroach on the neighboring park."},
    "entrance": {"phonetic": "/ˈentrəns/", "pos": "n.", "meaning": "入口；進入權", "phrases": ["main entrance", "entrance fee"], "synonyms": ["entry", "access"], "antonyms": ["exit"], "example": "Please use the main entrance when you arrive at the office building."},
    "enlighten": {"phonetic": "/ɪnˈlaɪtn/", "pos": "v.", "meaning": "啟發；教導", "phrases": ["enlighten someone on", "highly enlightening"], "synonyms": ["inform", "educate"], "antonyms": ["confuse"], "example": "The seminar was designed to enlighten employees on the new safety regulations."},
    "enlist": {"phonetic": "/ɪnˈlɪst/", "pos": "v.", "meaning": "徵募；獲得支持", "phrases": ["enlist help", "enlist support"], "synonyms": ["recruit", "engage"], "antonyms": [], "example": "We need to enlist the support of the local community for our new project."},
    "esteem": {"phonetic": "/ɪˈstiːm/", "pos": "n./v.", "meaning": "尊敬；尊重", "phrases": ["high esteem", "self-esteem"], "synonyms": ["respect", "admiration"], "antonyms": ["contempt", "disdain"], "example": "The CEO is held in high esteem by all the employees in the company."},
    "evade": {"phonetic": "/ɪˈveɪd/", "pos": "v.", "meaning": "逃避；規避", "phrases": ["evade taxes", "evade responsibility"], "synonyms": ["avoid", "dodge"], "antonyms": ["confront", "face"], "example": "The company was accused of trying to evade its environmental responsibilities."},
    "excel": {"phonetic": "/ɪkˈsel/", "pos": "v.", "meaning": "擅長；勝過他人", "phrases": ["excel in", "excel at"], "synonyms": ["surpass", "outdo"], "antonyms": ["fail"], "example": "Our marketing team excels at creating innovative advertising campaigns."},
    "exaggerate": {"phonetic": "/ɪɡˈzædʒəreɪt/", "pos": "v.", "meaning": "誇張；誇大", "phrases": ["highly exaggerated", "exaggerate the facts"], "synonyms": ["overstate", "magnify"], "antonyms": ["understate", "play down"], "example": "The salesperson tended to exaggerate the benefits of the new product."},
    "evoke": {"phonetic": "/ɪˈvoʊk/", "pos": "v.", "meaning": "引起；喚起", "phrases": ["evoke memories", "evoke a response"], "synonyms": ["elicit", "arouse"], "antonyms": [], "example": "The new advertisement was designed to evoke a strong emotional response."},
    "exhibit": {"phonetic": "/ɪɡˈzɪbɪt/", "pos": "v./n.", "meaning": "展示；陳列品", "phrases": ["exhibit products", "trade exhibit"], "synonyms": ["display", "showcase"], "antonyms": ["hide", "conceal"], "example": "We will exhibit our latest products at the international trade fair next month."},
    "falter": {"phonetic": "/ˈfɔːltər/", "pos": "v.", "meaning": "動搖；衰退", "phrases": ["falter in", "without faltering"], "synonyms": ["hesitate", "waver"], "antonyms": ["persist", "continue"], "example": "The company's sales began to falter due to the increased competition."},
    "familiarize": {"phonetic": "/fəˈmɪliəraɪz/", "pos": "v.", "meaning": "使熟悉", "phrases": ["familiarize oneself with", "familiarization tour"], "synonyms": ["acquaint", "accustom"], "antonyms": [], "example": "New employees need to familiarize themselves with the company's software."},
    "figure": {"phonetic": "/ˈfɪɡjər/", "pos": "n./v.", "meaning": "數字；人物；計算", "phrases": ["sales figures", "key figure"], "synonyms": ["number", "amount"], "antonyms": [], "example": "According to the latest sales figures, our market share is increasing."},
    "fluctuate": {"phonetic": "/ˈflʌktʃueɪt/", "pos": "v.", "meaning": "波動；起伏", "phrases": ["fluctuate wildly", "price fluctuation"], "synonyms": ["vary", "oscillate"], "antonyms": ["stabilize"], "example": "The price of gold tends to fluctuate depending on the global economy."},
    "formulate": {"phonetic": "/ˈfɔːrmjuleɪt/", "pos": "v.", "meaning": "制定；規劃", "phrases": ["formulate a plan", "formulate a strategy"], "synonyms": ["develop", "create"], "antonyms": [], "example": "The committee is working hard to formulate a new marketing strategy."},
    "founder": {"phonetic": "/ˈfaʊndər/", "pos": "n.", "meaning": "創辦人", "phrases": ["co-founder", "founding father"], "synonyms": ["creator", "originator"], "antonyms": [], "example": "The founder of the company is still actively involved in its daily operations."},
    "franchise": {"phonetic": "/ˈfræntʃaɪz/", "pos": "n.", "meaning": "加盟權；特許經營", "phrases": ["franchise agreement", "franchise owner"], "synonyms": ["license", "authorization"], "antonyms": [], "example": "They decided to open a new franchise of the popular restaurant chain."},
    "further": {"phonetic": "/ˈfɜːrðər/", "pos": "adj./adv.", "meaning": "更進一步的；此外", "phrases": ["further information", "until further notice"], "synonyms": ["additional", "extra"], "antonyms": [], "example": "If you need any further information, please do not hesitate to contact us."},
    "harvest": {"phonetic": "/ˈhɑːrvɪst/", "pos": "n./v.", "meaning": "收穫；收割", "phrases": ["harvest crops", "bountiful harvest"], "synonyms": ["crop", "yield"], "antonyms": [], "example": "The farmers are busy with the harvest during this time of the year."},
    "idle": {"phonetic": "/ˈaɪdl/", "pos": "adj.", "meaning": "閒置的；懶散的", "phrases": ["idle machine", "idle gossip"], "synonyms": ["inactive", "unused"], "antonyms": ["busy", "active"], "example": "The machines have been sitting idle since the factory closed down."},
    "Impede": {"phonetic": "/ɪmˈpiːd/", "pos": "v.", "meaning": "阻礙；妨礙", "phrases": ["impede progress", "impede development"], "synonyms": ["hinder", "obstruct"], "antonyms": ["assist", "promote"], "example": "The bad weather conditions are likely to impede the construction project."},
    "implement": {"phonetic": "/ˈɪmplɪment/", "pos": "v.", "meaning": "實施；執行", "phrases": ["implement a policy", "implement changes"], "synonyms": ["execute", "enact"], "antonyms": ["halt", "suspend"], "example": "We will implement the new security system throughout the building next week."},
    "imply": {"phonetic": "/ɪmˈplaɪ/", "pos": "v.", "meaning": "暗示；意指", "phrases": ["imply that", "not necessarily imply"], "synonyms": ["suggest", "indicate"], "antonyms": ["state", "express"], "example": "The manager's comments seemed to imply that there would be no bonuses this year."},
    "Incline": {"phonetic": "/ɪnˈklaɪn/", "pos": "v.", "meaning": "傾向；偏向", "phrases": ["be inclined to", "inclined towards"], "synonyms": ["tend", "lean"], "antonyms": [], "example": "I am inclined to agree with your suggestion regarding the new project."},
    "induce": {"phonetic": "/ɪnˈduːs/", "pos": "v.", "meaning": "引起；歸納", "phrases": ["induce sleep", "induce vomiting"], "synonyms": ["cause", "persuade"], "antonyms": ["prevent"], "example": "The new government policy is designed to induce investment in renewable energy."},
    "initiate": {"phonetic": "/ɪˈnɪʃieɪt/", "pos": "v.", "meaning": "開始；發起", "phrases": ["initiate a project", "initiate contact"], "synonyms": ["begin", "start"], "antonyms": ["conclude", "finish"], "example": "The company decided to initiate a new training program for its employees."},
    "institute": {"phonetic": "/ˈɪnstɪtuːt/", "pos": "n./v.", "meaning": "機構；制定", "phrases": ["research institute", "institute a policy"], "synonyms": ["organization", "establish"], "antonyms": [], "example": "The government decided to institute new regulations to protect the environment."},
    "insulate": {"phonetic": "/ˈɪnsəleɪt/", "pos": "v.", "meaning": "絕緣；隔離", "phrases": ["insulate a building", "insulate from noise"], "synonyms": ["isolate", "protect"], "antonyms": [], "example": "The house is well-insulated, which helps to keep the heating costs low."},
    "instruct": {"phonetic": "/ɪnˈstrʌkt/", "pos": "v.", "meaning": "指示；教導", "phrases": ["instruct someone to do", "highly instructed"], "synonyms": ["order", "teach"], "antonyms": [], "example": "The manager instructed the team to complete the report by the end of the day."},
    "insult": {"phonetic": "/ɪnˈsʌlt/", "pos": "n./v.", "meaning": "侮辱；冒犯", "phrases": ["add insult to injury", "gross insult"], "synonyms": ["offense", "abuse"], "antonyms": ["compliment", "praise"], "example": "His comments were seen as a direct insult to the hard-working employees."},
    "intend": {"phonetic": "/ɪnˈtend/", "pos": "v.", "meaning": "打算；想要", "phrases": ["intend to do", "fully intend"], "synonyms": ["plan", "mean"], "antonyms": [], "example": "We intend to expand our business into the European market next year."},
    "irritate": {"phonetic": "/ˈɪrɪteɪt/", "pos": "v.", "meaning": "激怒；使惱火", "phrases": ["highly irritating", "irritate the skin"], "synonyms": ["annoy", "bother"], "antonyms": ["soothe", "please"], "example": "The loud noise from the construction site began to irritate the local residents."},
    "judge": {"phonetic": "/dʒʌdʒ/", "pos": "n./v.", "meaning": "法官；判斷", "phrases": ["judge someone by", "final judge"], "synonyms": ["assess", "evaluate"], "antonyms": [], "example": "It is important to judge the project based on its actual results."},
    "justify": {"phonetic": "/ˈdʒʌstɪfaɪ/", "pos": "v.", "meaning": "證明...正當；辯護", "phrases": ["justify the cost", "fully justified"], "synonyms": ["defend", "validate"], "antonyms": ["condemn"], "example": "The manager had to justify the high cost of the new software to the board."},
    "license": {"phonetic": "/ˈlaɪsns/", "pos": "n./v.", "meaning": "執照；授權", "phrases": ["driving license", "business license"], "synonyms": ["permit", "authorization"], "antonyms": [], "example": "The company was granted a license to sell its products in the international market."},
    "lesson": {"phonetic": "/ˈlesn/", "pos": "n.", "meaning": "課程；教訓", "phrases": ["learned a lesson", "private lesson"], "synonyms": ["class", "instruction"], "antonyms": [], "example": "The company learned a valuable lesson after the failure of its last marketing campaign."},
    "mend": {"phonetic": "/mend/", "pos": "v.", "meaning": "修理；修補", "phrases": ["mend a fence", "on the mend"], "synonyms": ["repair", "fix"], "antonyms": ["break", "damage"], "example": "The maintenance team is busy mending the broken fence around the factory."},
    "mollify": {"phonetic": "/ˈmɑːlɪfaɪ/", "pos": "v.", "meaning": "安撫；緩和", "phrases": ["mollify someone", "mollify the situation"], "synonyms": ["pacify", "appease"], "antonyms": ["enrage", "aggravate"], "example": "The manager tried to mollify the angry customer by offering a full refund."},
    "mobilize": {"phonetic": "/ˈmoʊbəlaɪz/", "pos": "v.", "meaning": "動員；調動", "phrases": ["mobilize resources", "mobilize the workforce"], "synonyms": ["assemble", "organize"], "antonyms": [], "example": "The company decided to mobilize all its resources to complete the project on time."},
    "neglect": {"phonetic": "/nɪˈɡlekt/", "pos": "v./n.", "meaning": "疏忽；忽視", "phrases": ["neglect duty", "gross neglect"], "synonyms": ["ignore", "disregard"], "antonyms": ["care", "attend"], "example": "The company was fined for neglecting its safety responsibilities in the factory."},
    "nurse": {"phonetic": "/nɜːrs/", "pos": "n./v.", "meaning": "護士；照料", "phrases": ["registered nurse", "nurse someone back to health"], "synonyms": ["care for", "attend"], "antonyms": [], "example": "The nurse is responsible for looking after the patients in the hospital ward."},
    "obtain": {"phonetic": "/əbˈteɪn/", "pos": "v.", "meaning": "獲得；取得", "phrases": ["obtain permission", "obtain a visa"], "synonyms": ["get", "acquire"], "antonyms": ["lose", "forfeit"], "example": "You need to obtain a permit before you can start the construction project."},
    "occasion": {"phonetic": "/əˈkeɪʒn/", "pos": "n.", "meaning": "場合；時刻", "phrases": ["special occasion", "on several occasions"], "synonyms": ["event", "time"], "antonyms": [], "example": "The company held a special dinner to mark the occasion of its tenth anniversary."},
    "occur": {"phonetic": "/əˈkɜːr/", "pos": "v.", "meaning": "發生", "phrases": ["occur to someone", "natural occurrence"], "synonyms": ["happen", "take place"], "antonyms": [], "example": "The accident occurred during the night shift when only a few workers were present."},
    "occurence": {"phonetic": "/əˈkɜːrəns/", "pos": "n.", "meaning": "發生；事件", "phrases": ["common occurrence", "daily occurrence"], "synonyms": ["event", "incident"], "antonyms": [], "example": "Technical problems are a common occurrence during the initial stage of a project."},
    "omit": {"phonetic": "/əˈmɪt/", "pos": "v.", "meaning": "省略；遺漏", "phrases": ["omit a detail", "deliberately omit"], "synonyms": ["exclude", "leave out"], "antonyms": ["include", "add"], "example": "Please make sure that you do not omit any important information from the report."},
    "operate": {"phonetic": "/ˈɑːpəreɪt/", "pos": "v.", "meaning": "運作；操作；營業", "phrases": ["operate a machine", "operate globally"], "synonyms": ["function", "run"], "antonyms": [], "example": "The company operates in more than twenty different countries around the world."},
    "overlook": {"phonetic": "/ˌoʊvərˈlʊk/", "pos": "v.", "meaning": "俯瞰；忽略", "phrases": ["overlook the city", "overlook a mistake"], "synonyms": ["ignore", "miss"], "antonyms": ["notice", "spot"], "example": "The manager tended to overlook the minor mistakes made by her team members."},
    "oversee": {"phonetic": "/ˌoʊvərˈsiː/", "pos": "v.", "meaning": "監督；管理", "phrases": ["oversee a project", "closely oversee"], "synonyms": ["supervise", "monitor"], "antonyms": ["neglect"], "example": "A senior engineer will oversee the construction of the new production facility."},
    "overwhelm": {"phonetic": "/ˌoʊvərˈwelm/", "pos": "v.", "meaning": "使不堪重負；壓倒", "phrases": ["overwhelmed with work", "overwhelming majority"], "synonyms": ["overpower", "engulf"], "antonyms": [], "example": "The customer service department was overwhelmed with calls after the product launch."}
}

with open('data_green.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_2:
        item.update(enriched_data_2[word])

with open('data_green.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修第 51-100 個高品質單字。")
