import json

# 第 101-150 個高品質單字對應表 (金色等級)
enriched_data_gold_3 = {
    "downsize": {"phonetic": "/ˈdaʊnsaɪz/", "pos": "v.", "meaning": "縮編；裁員", "phrases": ["corporate downsizing"], "synonyms": ["reduce", "cut back"], "antonyms": ["expand"], "example": "The company plans to downsize its workforce by ten percent to reduce operational costs."},
    "restructure": {"phonetic": "/ˌriːˈstrʌktʃər/", "pos": "v.", "meaning": "重組；調整結構", "phrases": ["restructure the debt"], "synonyms": ["reorganize"], "antonyms": [], "example": "The board decided to restructure the company to better adapt to the changing market."},
    "take over": {"phonetic": "/teɪk ˈoʊvər/", "pos": "v. phr.", "meaning": "接管；收購", "phrases": ["hostile takeover"], "synonyms": ["acquire", "seize"], "antonyms": ["surrender"], "example": "A large multinational corporation is planning to take over the local telecommunications firm."},
    "merger": {"phonetic": "/ˈmɜːrdʒər/", "pos": "n.", "meaning": "合併", "phrases": ["merger and acquisition"], "synonyms": ["consolidation", "union"], "antonyms": ["separation", "split"], "example": "The merger between the two airlines is expected to create the largest carrier in the world."},
    "acquisition": {"phonetic": "/ˌækwɪˈzɪʃn/", "pos": "n.", "meaning": "收購", "phrases": ["recent acquisition"], "synonyms": ["purchase", "takeover"], "antonyms": ["divestiture"], "example": "The company's recent acquisition of a technology startup has boosted its research capabilities."},
    "subsidiary": {"phonetic": "/səbˈsɪdiˌeri/", "pos": "n.", "meaning": "子公司", "phrases": ["wholly owned subsidiary"], "synonyms": ["branch", "affiliate"], "antonyms": ["parent company"], "example": "The parent company has several subsidiaries operating in different regions around the world."},
    "affiliate": {"phonetic": "/əˈfɪliˌeɪt/", "pos": "n./v.", "meaning": "關係企業；隸屬於", "phrases": ["affiliated company"], "synonyms": ["associate", "partner"], "antonyms": [], "example": "Our company is affiliated with several international organizations in the industry."},
    "franchise": {"phonetic": "/ˈfræntʃaɪz/", "pos": "n./v.", "meaning": "加盟；特許經營權", "phrases": ["franchise agreement"], "synonyms": ["license"], "antonyms": [], "example": "They decided to open a new franchise of the popular coffee shop chain in the city center."},
    "joint venture": {"phonetic": "/dʒɔɪnt ˈventʃər/", "pos": "n. phr.", "meaning": "合資企業", "phrases": ["form a joint venture"], "synonyms": ["partnership"], "antonyms": [], "example": "The two companies have formed a joint venture to develop new renewable energy technology."},
    "monopoly": {"phonetic": "/məˈnɑːpəli/", "pos": "n.", "meaning": "壟斷；獨佔", "phrases": ["market monopoly"], "synonyms": ["exclusivity"], "antonyms": ["competition"], "example": "The government is taking steps to prevent a single company from having a monopoly in the market."},
    "competition": {"phonetic": "/ˌkɑːmpəˈtɪʃn/", "pos": "n.", "meaning": "競爭", "phrases": ["stiff competition", "unfair competition"], "synonyms": ["rivalry", "contest"], "antonyms": ["cooperation", "monopoly"], "example": "The company faces stiff competition from local and international rivals in the industry."},
    "competitor": {"phonetic": "/kəmˈpetɪtər/", "pos": "n.", "meaning": "競爭者", "phrases": ["major competitor"], "synonyms": ["rival", "opponent"], "antonyms": ["partner", "ally"], "example": "We need to monitor our competitors' marketing strategies to stay ahead in the market."},
    "rival": {"phonetic": "/ˈraɪvl/", "pos": "n./adj.", "meaning": "對手；競爭的", "phrases": ["rival company"], "synonyms": ["competitor", "opponent"], "antonyms": ["ally", "colleague"], "example": "The two rival companies are competing for the same major government contract."},
    "market share": {"phonetic": "/ˈmɑːrkɪt ʃer/", "pos": "n. phr.", "meaning": "市場佔有率", "phrases": ["gain market share"], "synonyms": [], "antonyms": [], "example": "The company has managed to increase its market share despite the economic downturn."},
    "competitive edge": {"phonetic": "/kəmˈpetətɪv edʒ/", "pos": "n. phr.", "meaning": "競爭優勢", "phrases": ["maintain a competitive edge"], "synonyms": ["competitive advantage"], "antonyms": [], "example": "Our innovative technology gives us a significant competitive edge over our rivals."},
    "niche market": {"phonetic": "/niːʃ ˈmɑːrkɪt/", "pos": "n. phr.", "meaning": "小眾市場", "phrases": ["target a niche market"], "synonyms": [], "antonyms": ["mass market"], "example": "The company specializes in providing high-quality organic products for a niche market."},
    "blue-chip company": {"phonetic": "/ˌbluː ˈtʃɪp ˈkʌmpəni/", "pos": "n. phr.", "meaning": "績優公司；藍籌股公司", "phrases": ["invest in blue-chip companies"], "synonyms": [], "antonyms": [], "example": "Investing in blue-chip companies is generally considered to be a safer long-term strategy."},
    "multinational": {"phonetic": "/ˌmʌltiˈnæʃnəl/", "pos": "n./adj.", "meaning": "跨國公司；跨國的", "phrases": ["multinational corporation"], "synonyms": ["global"], "antonyms": ["local", "domestic"], "example": "He works as a senior manager for a large multinational corporation with offices in twenty countries."},
    "corporation": {"phonetic": "/ˌkɔːrpəˈreɪʃn/", "pos": "n.", "meaning": "公司；法人", "phrases": ["large corporation"], "synonyms": ["company", "firm"], "antonyms": [], "example": "The corporation is planning to invest millions of dollars in new research and development."},
    "enterprise": {"phonetic": "/ˈentərpraɪz/", "pos": "n.", "meaning": "企業；事業", "phrases": ["private enterprise", "medium-sized enterprise"], "synonyms": ["business", "venture"], "antonyms": [], "example": "The government is offering financial support to small and medium-sized enterprises."},
    "startup": {"phonetic": "/ˈstɑːrtʌp/", "pos": "n.", "meaning": "創業公司", "phrases": ["tech startup"], "synonyms": [], "antonyms": ["established company"], "example": "The technology startup has recently received a significant amount of venture capital funding."},
    "entrepreneurship": {"phonetic": "/ˌɑːntrəprəˈnɜːrʃɪp/", "pos": "n.", "meaning": "創業精神", "phrases": ["promote entrepreneurship"], "synonyms": [], "antonyms": [], "example": "The university offers courses to encourage entrepreneurship among its business students."},
    "incorporate": {"phonetic": "/ɪnˈkɔːrpəreɪt/", "pos": "v.", "meaning": "註冊成立；包含", "phrases": ["be incorporated in"], "synonyms": ["integrate", "include"], "antonyms": ["separate"], "example": "The business was incorporated in 2010 and has since grown into a large organization."},
    "charter": {"phonetic": "/ˈtʃɑːrtər/", "pos": "n./v.", "meaning": "章程；租用", "phrases": ["corporate charter", "charter a plane"], "synonyms": ["constitution", "rent"], "antonyms": [], "example": "The company's charter outlines its mission, values, and organizational structure."},
    "bylaws": {"phonetic": "/ˈbaɪlɔːz/", "pos": "n.", "meaning": "內部規章；附則", "phrases": ["company bylaws"], "synonyms": ["regulations"], "antonyms": [], "example": "The board members must follow the company's bylaws when making important decisions."},
    "policy": {"phonetic": "/ˈpɑːləsi/", "pos": "n.", "meaning": "政策；規定", "phrases": ["company policy", "insurance policy"], "synonyms": ["rule", "guideline"], "antonyms": [], "example": "The company has a strict policy regarding the use of mobile phones in the workplace."},
    "procedure": {"phonetic": "/prəˈsiːdʒər/", "pos": "n.", "meaning": "程序；步驟", "phrases": ["standard operating procedure"], "synonyms": ["process", "method"], "antonyms": [], "example": "Please make sure you follow the correct procedure when applying for annual leave."},
    "protocol": {"phonetic": "/ˈproʊtəkɑːl/", "pos": "n.", "meaning": "協議；禮儀；規程", "phrases": ["safety protocol", "diplomatic protocol"], "synonyms": ["code", "agreement"], "antonyms": [], "example": "All staff members must follow the security protocol when entering the research facility."},
    "regulation": {"phonetic": "/ˌreɡjuˈleɪʃn/", "pos": "n.", "meaning": "法規；規定", "phrases": ["government regulation", "safety regulation"], "synonyms": ["law", "rule"], "antonyms": ["deregulation"], "example": "The company must comply with all government regulations regarding workplace safety."},
    "compliance": {"phonetic": "/kəmˈplaɪəns/", "pos": "n.", "meaning": "合規；遵守", "phrases": ["in compliance with"], "synonyms": ["adherence", "conformity"], "antonyms": ["defiance", "violation"], "example": "The internal audit was carried out to ensure the company's compliance with financial laws."},
    "standard": {"phonetic": "/ˈstændərd/", "pos": "n./adj.", "meaning": "標準；規格", "phrases": ["quality standard", "standard procedure"], "synonyms": ["criterion", "benchmark"], "antonyms": [], "example": "Our products are manufactured to the highest international quality standards."},
    "benchmark": {"phonetic": "/ˈbentʃmɑːrk/", "pos": "n./v.", "meaning": "基準；標竿", "phrases": ["set a benchmark"], "synonyms": ["standard", "reference point"], "antonyms": [], "example": "The company's performance is used as a benchmark for other firms in the industry."},
    "criterion": {"phonetic": "/kraɪˈtɪriən/", "pos": "n.", "meaning": "標準；準則(單數)", "phrases": ["selection criterion"], "synonyms": ["standard", "requirement"], "antonyms": [], "example": "Experience is the most important criterion for selecting a candidate for this position."},
    "norm": {"phonetic": "/nɔːrm/", "pos": "n.", "meaning": "常態；規範", "phrases": ["social norm", "above the norm"], "synonyms": ["standard", "average"], "antonyms": ["exception"], "example": "Working from home at least one day a week has become the norm for many employees."},
    "ethic": {"phonetic": "/ˈeθɪk/", "pos": "n.", "meaning": "倫理；道德規範", "phrases": ["work ethic", "business ethics"], "synonyms": ["morals", "principles"], "antonyms": [], "example": "The company is committed to maintaining high business ethics in all its operations."},
    "code of conduct": {"phonetic": "/koʊd əv ˈkɑːndʌkt/", "pos": "n. phr.", "meaning": "行為準則", "phrases": ["strict code of conduct"], "synonyms": [], "antonyms": [], "example": "All employees are required to read and sign the company's code of conduct."},
    "transparency": {"phonetic": "/trænsˈpærənsi/", "pos": "n.", "meaning": "透明度", "phrases": ["financial transparency"], "synonyms": ["openness"], "antonyms": ["opacity", "secrecy"], "example": "We are committed to maintaining transparency in our decision-making processes."},
    "accountability": {"phonetic": "/əˌkaʊntəˈbɪləti/", "pos": "n.", "meaning": "問責制度；責任", "phrases": ["ensure accountability"], "synonyms": ["responsibility"], "antonyms": [], "example": "The new system is designed to improve accountability and prevent financial errors."},
    "integrity": {"phonetic": "/ɪnˈteɡrəti/", "pos": "n.", "meaning": "誠信；完整性", "phrases": ["personal integrity", "business integrity"], "synonyms": ["honesty", "reliability"], "antonyms": ["dishonesty", "corruption"], "example": "He is a person of high integrity and is well-respected by all his colleagues."},
    "confidentiality": {"phonetic": "/ˌkɑːnfɪˌdenʃiˈæləti/", "pos": "n.", "meaning": "保密性", "phrases": ["maintain confidentiality", "confidentiality agreement"], "synonyms": ["secrecy"], "antonyms": ["publicity"], "example": "All employees must sign a confidentiality agreement before they start work."},
    "disclosure": {"phonetic": "/dɪsˈkloʊʒər/", "pos": "n.", "meaning": "揭露；公開", "phrases": ["full disclosure"], "synonyms": ["revelation", "exposure"], "antonyms": ["concealment"], "example": "The company made a full disclosure of its financial situation to its shareholders."},
    "liability": {"phonetic": "/ˌlaɪəˈbɪləti/", "pos": "n.", "meaning": "責任；債務", "phrases": ["limited liability", "product liability"], "synonyms": ["responsibility", "debt"], "antonyms": ["asset"], "example": "The company has a significant liability due to the ongoing legal case."},
    "indemnity": {"phonetic": "/ɪnˈdemnəti/", "pos": "n.", "meaning": "賠償；補償", "phrases": ["indemnity insurance"], "synonyms": ["compensation", "reimbursement"], "antonyms": [], "example": "The insurance policy provides an indemnity for any damage caused by the fire."},
    "compensation": {"phonetic": "/ˌkɑːmpenˈseɪʃn/", "pos": "n.", "meaning": "補償金；報酬", "phrases": ["workers' compensation"], "synonyms": ["payment", "remuneration"], "antonyms": [], "example": "The workers are demanding fair compensation for their overtime and hard work."},
    "payout": {"phonetic": "/ˈpeɪaʊt/", "pos": "n.", "meaning": "支出；賠付金", "phrases": ["insurance payout"], "synonyms": ["payment"], "antonyms": [], "example": "The insurance company made a large payout to the business following the accident."},
    "dividend": {"phonetic": "/ˈdɪvɪdend/", "pos": "n.", "meaning": "股利；紅利", "phrases": ["annual dividend"], "synonyms": ["share", "bonus"], "antonyms": [], "example": "Shareholders will receive a yearly dividend based on the company's annual profits."},
    "equity": {"phonetic": "/ˈekwəti/", "pos": "n.", "meaning": "股權；公平", "phrases": ["private equity", "brand equity"], "synonyms": ["ownership", "fairness"], "antonyms": ["debt", "unfairness"], "example": "He owns a significant amount of equity in the technology startup he helped found."},
    "stake": {"phonetic": "/steɪk/", "pos": "n./v.", "meaning": "股份；利害關係", "phrases": ["controlling stake"], "synonyms": ["share", "interest"], "antonyms": [], "example": "The parent company holds a forty percent stake in its international subsidiary."},
    "shareholder": {"phonetic": "/ˈʃerhoʊldər/", "pos": "n.", "meaning": "股東", "phrases": ["majority shareholder"], "synonyms": ["stockholder"], "antonyms": [], "example": "The shareholders will meet next month to vote on the company's new investment plan."},
    "mandatory": {"phonetic": "/ˈmændətɔːri/", "pos": "/ˈmændətɔːri/", "pos": "adj.", "meaning": "強制的；義務的", "phrases": ["mandatory training"], "synonyms": ["compulsory", "required"], "antonyms": ["optional", "voluntary"], "example": "It is mandatory for all new employees to participate in the safety training session."}
}

with open('data_gold.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_gold_3:
        update_info = enriched_data_gold_3[word].copy()
        if 'word' in update_info:
            item['word'] = update_info.pop('word')
        item.update(update_info)

with open('data_gold.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修金色等級第 101-150 個單字。")
